### ISSUE TITLE
Error on second run

### ISSUE THREAD

**Issue by mac-linux-free** [digint/btrbk#1]
Hello,

I just tried out your great backup script and did and Pull based backup from one remote host.

The first time the backup runs fine. But if I did it the second time the error below appears.

please help.

btrbk command line client, version 0.11  (Tue Mar 10 20:45:11 2015)

ERROR: process died unexpectedly (btrbk v0.11)
Please contact the author: Axel Burri <axel@####.##>

Stack Trace:
----------------------------------------
Use of uninitialized value $& in concatenation (.) or string at /usr/sbin/btrbk line 673, <FILE> line 108.
 at /usr/sbin/btrbk line 97, <FILE> line 108.
        main::__ANON__('Use of uninitialized value $& in concatenation (.) or string ...') called at /usr/sbin/btrbk line 673
        main::btr_subtree('/mnt/btrbk/kerio', 'HASH(0x13ca968)') called at /usr/sbin/btrbk line 1222

**Comment by digint** [comment]
Bug fixed in 02acb32: The bug occurred when parsing a sub-subvolume from "btrfs subvolume list" command output
