### ISSUE TITLE
Config parsing fails on subvolume with name "0"

### ISSUE THREAD

**Issue by ochilan** [digint/btrbk#10]
Hi,

I'm using btrbk 0.16 on Arch Linux. I have source subvolumes named 0, 1, 2, ... which I would like to backup. However, the config file parsing fails when encountering the "subvolume 0" line (however, e.g. "subvolume 1" works):

    ...
    config: adding volume "<path omitted>" to root context
    ERROR: Failed to parse configuration file

When I tried to change "0" to "0/" in the config file, the error gets even worse:

    ...
    ERROR: process died unexpectedly (btrbk v0.16)
    Please contact the author: Axel Burri <e-mail address omitted>
    
    Stack Trace:
    ----------------------------------------
    Died at /usr/bin/btrbk line 1371, <FILE> line 116.
     at /usr/bin/btrbk line 101, <FILE> line 116.
	    main::__ANON__("Died at /usr/bin/btrbk line 1371, <FILE> line 116.\x{a}") called at /usr/bin/btrbk line 1371

**Comment by digint** [comment]
fixed in: a90033c1aa79f2efc18ea7411058050cd3c37cfa

**Comment by digint** [comment]
Fix included in btrbk-0.17.0
