### ISSUE TITLE
cron/systemd question

### ISSUE THREAD

**Issue by wcat13** [digint/btrbk#103]
Using Arch I have no cron by default. My question is do I have to install cron? I see two systemd scripts in the repo.

btrbk.service
btrbk.timer

I have enabled the timer
sudo systemctl enable btrbk.timer

When I go to enable the the btrbk.service it is not there and cannot be enabled. I am a novice when it comes to systemd and btrfs and wondering if the timer is enabling the service as needed or if I need to install cronie or crond to get the btrbk working correctly.

Thank you.

**Comment by digint** [comment]
Sorry for the late reply, I'm still in vacation...

First a little disclaimer: I don't use systemd (for various reasons), so all of this post is "as far as I know, and if I recall it correctly". Maybe someone else watching this thread can correct me if I'm wrong.

If you use systemd, you don't need to install cron. You can if you want, but systemd already offers very versatile timer functionality. The Arch Wiki has a pretty nice overview on systemd timers, so if you're not familiar with it, take a look here first:

https://wiki.archlinux.org/index.php/Systemd/Timers

btrbk provides a very basic systemd timer unit: The `btrbk.timer` schedules `btrbk.service` (which again calls `btrbk run`) on a daily basis.

So all you need is to enable the timer, and (if I recall it correctly) you also need to start it:

    sudo systemctl enable btrbk.timer
    sudo systemctl start btrbk.timer

You can see a list of your active timers using:

    systemctl list-timers --all

**Comment by wcat13** [comment]
Oh man, you did not have to engage me during your holiday.  Thank you though. Btrbk has been running smooth for a few days now and if I would have been patient I could have confirmed what I already guessed at and you confirmed.  Have a great vacation and thank you for this back up solution.
