### ISSUE TITLE
Failed to fetch subvolume detail

### ISSUE THREAD

**Issue by menaceone** [digint/btrbk#108]
Hello,
I'm using your great tool for backing up two subvolumes, a and b, to a remote server via ssh.

Since a few weeks I have the problem, that on first run i get the error message:

-- Skipping target "remoteserver:/path/to/a": Failed to fetch subvolume detail --

subvolume b is transferred correctly. 
When I start a second run, a and b will be transferred correctly.

The remoteserver isn't the fastest and the remote filesystem is on an external hdd (I disabled powermanagement)

Could there been a timeout or something?
How can I debug this?

thank you

**Comment by digint** [comment]
This looks like some timeout problem, or maybe something related to automount (I've read about some bugs related to systemd when it comes to automount btrfs filesystems, but I can't really tell as I'm not using systemd). Note that btrbk itself has no timeouts, but maybe you configured ssh to timeout?

If you run `btrbk -l debug`, you will see the btrfs commands called. Look for `btrfs subvolume list` or `btrfs subvolume show`, these are the ones triggering "Failed to fetch subvolume detail" on error. You can then manually call those commands and see what happens. You can see the complete command outputs when running `btrbk -l trace`, be aware that this produces a lot of messages.

**Comment by menaceone** [comment]
Thanks for your reply.
btrbk -l debug shows, that the first attempt of 

`### '/usr/bin/ssh' '-i' '/path/to/key' 'user@remoteserver' 'btrfs' 'subvolume' 'show' '/path/to/a'
Command execution successful
Real path for subvolume "remoteserver:/path/to/a" is: Warning
WARNING: Skipping target "remoteserver:/path/to/a": Failed to fetch subvolume detail`

Switching the order of a and b leads to the same result with b.
I have the default ssh settings (I think there is no timeout for commands, just for the whole session)

As a workaround I will execute the failing command before the run of btrbk, and let this dummy command failing. 

Any hints what could be wrong? 
Manually log in at the machine and `cd /path/to/a` needs about 2 seconds. Even with disabled APM (HDD powermanagement)
I'm wondering what changed, because the last 18 Months everything runs fine (a Kernel update?). 

I'm offline until tuesday evening, so I can't answer to further advice before.
Thanks for your help.

**Comment by digint** [comment]
If it's a timeout problem it has to be ssh related. Filesystem calls are all blocking, your 2s wait on `cd /path/to/a` is not an issue here (btrfs sometimes needs its time to do all the backref walking stuff).

from `man ssh_config`:
```
ConnectTimeout
             Specifies the timeout (in seconds) used when connecting to the SSH server, instead of using the
             default system TCP timeout.  This value is used only when the target is down or really unreach‐
             able, not when it refuses the connection.
```

It would be interesting to know what happens when you call `/usr/bin/ssh -v -i /path/to/key user@remoteserver btrfs subvolume show /path/to/a` manually. For some reason this fails, and results in the btrbk warning.

**Comment by menaceone** [comment]
hmm, the manually call was successfull. 
But I execute it 16 hours after the last call, I will ad the verbose option to my Cron-executed dummy call and will monitor the output. The whole call needs more than 15s. 

`Transferred: sent 3496, received 3392 bytes, in 15.6 seconds
Bytes per second: sent 223.9, received 217.2
debug1: Exit status 0`

Quite slow in my opinion, maybe near to any threshold. The system TCP timeout should be 20s, but imho only for establishing the connection, not the whole command.

**Comment by menaceone** [comment]
I solved the problem. My remote server gets a different IP every day. So the first SSH call outputs a 
`Warning: Permanently added the ECDSA host key for IP address '[84.145.115.169]:1303' to the list of known hosts.`

Is abortion of the backup on a warning intended?

However, adding 
`CheckHostIP no`
to my ssh config prevents the warning and all backups are made correctly.

Thanks a lot for your support!
