### ISSUE TITLE
Unable to satisfy expected syntax or values for "snapshot_preserve_min".

### ISSUE THREAD

**Issue by lweberk** [digint/btrbk#109]
Given the configuration;

```
transaction_log  /var/log/btrbk.log

snapshot_dir     .snapshots
snapshot_create  onchange

snapshot_preserve      no
snapshot_preserve_min  24h 7d 4w 12m *y
target_preserve        no
target_preserve_min    all

incremental  yes

ssh_identity     /root/.ssh/id_rsa
ssh_user         root
ssh_compression  yes

lockfile  /var/run/btrbk.lock
```

I get the following output on:
```
> btrbk -n -c /etc/btrbk/btrbk.conf list
ERROR: Value "24h 7d 4w 12m *y" failed input validation for option "snapshot_preserve_min" in "/etc/btrbk/btrbk.conf" line 12
ERROR: Failed to parse configuration file
```
Having trouble finding out what about "24h 7d 4w 12m *y" is wrong. The error message does not really give me a hint either.

What am I failing to see? Any help appreciated...

Running v0.23.3 on Debian.

Best regards,
~lweberk

**Comment by digint** [comment]
I'm not sure what you want to achieve with `snapshot_preserve_min  24h 7d 4w 12m *y`. Maybe you wanted `snapshot_preserve  24h 7d 4w 12m *y`? From the man page:

```
snapshot_preserve_min  all|latest|<number>{h,d,w,m,y}
    Preserve all snapshots for a minimum amount of hours (h), days (d), weeks (w), months (m) or
    years (y), regardless of how many there are. If set to “all”, preserve all snapshots forever.
    If set to “latest”, preserve latest snapshot. Defaults to “all”.
```

If you simply want to preserve *everything*, set `snapshot_preserve_min all` (the default). If you want btrbk to do more sophisticated preserving, use `snapshot_preserve` (usually in combination with `snapshot_preserve_min`), and make sure you understand the concepts (`man btrbk.conf`, and examples in README.md).

**Comment by lweberk** [comment]
Thank you for the prompt response. 

Got the snapshot_preserve_min with the snapshot_preserve confused. It seemed the both kind of express the same yet not the same thing. Is the *_min a dragnet for the other option?. Event the docs, thou very thorough did not seem clear on the relationship between both.

Either way you pointing that out fixed my problem. Many thanks.

**Comment by digint** [comment]
The key difference is that the `_min` preserves "all snapshots, **regardless of how many there are**". So for example if you have `snapshot_preserve 7d`, but you run btrbk more than once a day, there will be **only one** snapshot preserved every day, for 7 days back. If you have `snapshot_preserve_min 7d`, **all** snapshots will be preserved for 7 days.

So yes, kind of a dragnet.

**Comment by lweberk** [comment]
Ok, that sorted out my confusion. Thank you a lot!

**Comment by DL6AKU** [comment]
> So for example if you have snapshot_preserve 7d, but you run btrbk more than once a day, there will be only one snapshot preserved every day, for 7 days back. If you have snapshot_preserve_min 7d, all snapshots will be preserved for 7 days.

Oh, I did not know this either. I thought _min would just more agressively try to keep snapshots. I just realized it had this meaning after you explained it in those words.

Maybe this explanation should make it verbatim into the ```--help``` or ```manpage```?
