### ISSUE TITLE
Issue with multiple backups per day and snapshot_preserve_* 0 (plus a suggestion)

### ISSUE THREAD

**Issue by ochilan** [digint/btrbk#11]
Hey,

I like the ability to quickly run btrbk whenever I feel like it, e.g. before an update, experimental work and so forth. In particular, I may run it multiple times a day. At the same time, I don't preserve snapshots (i.e. all snapshot_preserve_* options are set to "0", all target_preserve_* to "all").

The problem is that in this case, the first run will generate the snapshot

    SomeSub.YYYYMMDD

The second run will create a new snapshot and delete the old one, so we have in the source directory (as per the documentation)

    SomeSub.YYYYMMDD_1

Now if I run btrbk a third time, it fails because the next snapshot it creates has once again the name SomeSub.YYYYMMDD and a subvolume with this name already exists at the target location.

There are several ways this could be fixed, e.g. looking for the highest _N there is in the source folder (taking into account missing folders) and use _(N+1), or using random suffixes. However, my suggestion would be (and it would be much more informative also!) to use not only the date but also the time as the timestamp suffix. Maybe I'm overlooking something, but this would even make it more elegant since you don't have to look up the largest existing _N. Okay, two gotchas could be multiple snapshots within a second (or whatever precision is chosen for the timestamp), and possibly snapshots taken during daylight saving time changes (in particular, duplicate names may arise, and timestamps may not be ordered chronologically, in case this matters). But anyway, just as a thought, maybe this could be made an option.

**Comment by digint** [comment]
As you stated correctly, introducing a time suffix does not solve the problem. In a very early version of btrbk there were time suffixes, but I removed them for readability reasons (in most cases you are not interested in the timestamp anyways, and if you are, you can still get it with `btrfs subvolume show`).

I'll fix this issue by also checking for already present `_N` counters on the targets. Should have been done anyways, guess I thought it was not necessary.

**Comment by digint** [comment]
fixed in: 8f9cafb35900f1e64903b783807afae54946eec2

**Comment by digint** [comment]
Fix included in btrbk-0.17.0
