### ISSUE TITLE
Question / clarification: ambiguous ssh url

### ISSUE THREAD

**Issue by CountZukula** [digint/btrbk#118]
Hi all,

I'm trying out btrbk for the first time and i'm facing an unclear error message while doing a dry run of a test config file:

`btrbk -c root.conf -v dryrun`

ERROR: Ambiguous ssh url for option "target"

The file's content:

`ssh_identity ~/.ssh/theidfile`
`volume /mnt`
`  subvolume @home`
`    target send-receive ssh://root@192.168.0.2/pool/backup/@home`

The btrfs volume (/dev/sda5) is mounted on /mnt, with the two standard subvolumes @ and @home in it. I'd like to backup both to a NAS using SSH.

Can anyone put me on the right path? Also, I'm unsure as to where to post this message, google does not seem to be all that helpful yet about btrbk.
Thanks!

**Comment by digint** [comment]
Hi! 

You can not have `user@host` type urls. you need to specify a line: `ssh_user myuser` in the configuration (see `man btrbk.conf`). User `root` is the default, so you can skip this and just have:

```
ssh_identity ~/.ssh/theidfile
volume /mnt
subvolume @home
target send-receive ssh://192.168.0.2/pool/backup/@home
```

**Comment by CountZukula** [comment]
Ok, great, that clears that hurdle :). Thanks for the quick reply! I'm off to the next problem.
