### ISSUE TITLE
Incorrect usage filesystem size when using btrfs raid

### ISSUE THREAD

**Issue by icewind1991** [digint/btrbk#119]
When using btrfs raid1 the filesystem usage incorrectly adds the total size of the 2 disks in the raid when calculating the total space.

`btrbk -v  usage`

    host         path                    size       used      free
    -----------  ----------------------  ---------  --------  ---------
    remote_name  /path/to/remote         7.28TiB    6.37TiB   462.08GiB

`sudo btrfs fi show /path/to/remote`

    Label: none  uuid: f95dc11e-d2f2-4040-bbb3-36768b39e4da
            Total devices 2 FS bytes used 3.19TiB
            devid    1 size 3.64TiB used 3.19TiB path /dev/sda
            devid    2 size 3.64TiB used 3.19TiB path /dev/sdb

`sudo btrfs fi df /path/to/remote`

    Data, RAID1: total=3.13TiB, used=3.13TiB
    System, RAID1: total=8.00MiB, used=464.00KiB
    Metadata, RAID1: total=58.00GiB, used=56.55GiB
    GlobalReserve, single: total=512.00MiB, used=0.00B

**Comment by digint** [comment]
btrbk directly maps the output of `btrfs filesystem usage`, and NOT `btrfs filesystem df`: https://github.com/digint/btrbk/blob/master/btrbk#L735

Free space calculation in btrfs is somehow complicated, the output of btrfs usage/df shows you different views on the btrfs information. See the btrfs wiki for details about this. For a "general" usage, `filesystem usage` gives provides a better (in my opinion less confusing) view on the usage.

**Comment by icewind1991** [comment]
`sudo btrfs filesystem usage /path/to/remte`

    Overall:
        Device size:                   7.28TiB
        Device allocated:              6.44TiB
        Device unallocated:          860.03GiB
        Device missing:                  0.00B
        Used:                          6.43TiB
        Free (estimated):            430.78GiB      (min: 430.78GiB)
        Data ratio:                       2.00
        Metadata ratio:                   2.00
        Global reserve:              512.00MiB      (used: 0.00B)
    
    Data,RAID1: Size:3.16TiB, Used:3.16TiB
       /dev/sda        3.16TiB
       /dev/sdb        3.16TiB
    
    Metadata,RAID1: Size:58.00GiB, Used:56.84GiB
       /dev/sda       58.00GiB
       /dev/sdb       58.00GiB
    
    System,RAID1: Size:8.00MiB, Used:464.00KiB
       /dev/sda        8.00MiB
       /dev/sdb        8.00MiB
    
    Unallocated:
       /dev/sda      430.01GiB
       /dev/sdb      430.01GiB

Looks like the "Data ratio" could be used to get the "correct" size values for raid setups

**Comment by digint** [comment]
Aah I see, you are right. I actually did not want to confuse people by showing different numbers than the ones shown by `btrfs fi usage`, but I agree that usually you want to know about "actual data", and not disk size or btrfs internas (if you want this, you can still use `btrbk usage --format=long`).

Implemented changes in: b69e9ebf349c5430fbfa8d1b31a80b254eda0441

@icewind1991 can you please double check if the output is now as you expect it to be?

**Comment by icewind1991** [comment]
remote  /path/to/remote    3.64TiB   3.22TiB  429.31GiB

:+1:
