### ISSUE TITLE
save raw target send file temporary local

### ISSUE THREAD

**Issue by Micha-Btz** [digint/btrbk#122]
Hi there,

this is not a bug, more a wish i have. I use btrbk to create backups on a 2nd internal btrfs hdd
and a nfs share on my vu+ receiver compressed with xz and encrypted with gpg. The subvol is nearly 200GB big.

Since my pc has only a old amd dual core processor it takes more than 48h to create the backup.
And if the connection between my pc and receiver is gone my complete backup is trash.

I need some ideas how i get done one complete backup at month. To disable encryption is not an option for me, so maybe i don't compress the backup.  
One great thing would be to write the file locally to a given directory, encrypt the whole file at once and then send it to my vu. So that I'm able to copy the file again if the connection is lost.

Btrfs send / receive are designed to copy the whole subvolume. The question is, can a possibility to exclude some directorys be added?

TIA Micha

**Comment by digint** [comment]
#### compression
Disabling compression does not make much sense when using encryption. Without compression, there will be much more data to encrypt, which I presume takes more time than compressing. Use a fast compression algorithm like lzo or lz4 (e.g. `raw_target_compress lz4` should give best performance).

#### resume transfers
btrbk cannot resume a partially transferred stream. What you can do is to configure btrbk to create the raw backup locally, and send it to your destination by other means (e.g. using rsync).

#### exclude directories
You can not exclude a directory from a btrfs send. What you can do is create sub-subvolumes for separation, these will not appear in a snapshot / backup. Example:
```
/data  <-- btrfs subvolume you want to backup
# btrfs subvolume create /data/some_subdirs/big_unimportant_stuff
```
If you backup `/data` with btrbk, the `/data/some_place/big_unimportant_stuff` subvolume will be excluded. You will have to specify it separately in btrbk.conf if you still want backups for it. Note that restoring backups get more complicated the more nested subvolumes you have.

**Comment by digint** [comment]
> can restore btrbk images for raw targets with gpg encryption?

You have to do it manually. Something like:

```
gpg -d <backup.lz4.gpg> | lz4 -d | btrfs receive /path/to/restore_dir/
```

**Comment by Micha-Btz** [comment]
ok, thanks
