### ISSUE TITLE
ERROR: Unsupported value "syslog" for option "transaction_syslog" in "/etc/btrbk/btrbk.conf" line XX

### ISSUE THREAD

**Issue by HaleTom** [digint/btrbk#128]
I'm trying to work out what value to use for transaction_syslog for Manjaro Linux, based on Arch.

The manual doesn't list all the available values... how do I find out what they are?

**Comment by digint** [comment]
Thanks for mentioning this, the available facilities are missing in the btrbk man page, I will add them. Supported values are:
`user mail daemon auth lpr news cron authpriv local0 local1 local2 local3 local4 local5 local6 local7`

If you don't do special filtering in syslog.conf, you can use any of these, `user`, `cron` or `localX` make most sense I'd say.

If you are unfamiliar with syslog, see `man 3 syslog` for a description of these.

**Comment by digint** [comment]
added documentation in: a7f52785bd2fa83966dbc40da4cad308a0a7c42b
