### ISSUE TITLE
btrbk is sending full backup with pre-existing backups

### ISSUE THREAD

**Issue by TH3L0N3WOLF** [digint/btrbk#13]
I left the backup volume disconnected from my laptop for about a week or two, and went to reconnect it today to transfer over the missing snapshots. The most recent backup on the drive is from March 25th, and the laptop has snapshots from April 5th to today. I was expecting btrbk to continue incremental backups using the March backup as the parent source, but instead it started a full backup from April. 
```
Creating subvolume snapshot for: /mnt/subvolroot/rtfs
>>> /mnt/subvolroot/.snapshots/rtfs.20150415
Checking for missing backups of subvolume "/mnt/subvolroot/rtfs" in: /mnt/backups/Laptop/btrbk/
Resuming subvolume backup (send-receive) for: /mnt/subvolroot/.snapshots/rtfs.20150405
Receiving from snapshot: /mnt/subvolroot/.snapshots/rtfs.20150405
No common parent subvolume present, creating full backup
>>> /mnt/backups/Laptop/btrbk/rtfs.20150405
At subvol /mnt/subvolroot/.snapshots/rtfs.20150405
At subvol rtfs.20150405
```

The laptop snapshot directory
```
root [/root]$ ls /mnt/subvolroot/.snapshots
boot.20150405  boot.20150410  boot.20150415  etc.20150409  etc.20150414   home.20150410  home.20150415  rtfs.20150410  rtfs.20150415
boot.20150406  boot.20150411  etc.20150405   etc.20150410  etc.20150415   home.20150411  rtfs.20150405  rtfs.20150411
boot.20150407  boot.20150412  etc.20150406   etc.20150411  home.20150405  home.20150412  rtfs.20150406  rtfs.20150412
boot.20150408  boot.20150413  etc.20150407   etc.20150412  home.20150406  home.20150413  rtfs.20150407  rtfs.20150413
boot.20150409  boot.20150414  etc.20150408   etc.20150413  home.20150407  home.20150414  rtfs.20150409  rtfs.20150414
```

the backup volume directory
```
root [/root]$ ls /mnt/backups/Laptop/btrbk 
boot.20150323  boot.20150325  etc.20150324  home.20150323  home.20150325  rtfs.20150324  rtfs.20150405
boot.20150324  etc.20150323   etc.20150325  home.20150324  rtfs.20150323  rtfs.20150325
```

I understand that the backup volume snapshots are relatively old, but shouldn't an incremental send still be possible with the March snapshots as a parent? There is little difference between the March backups and the recent ones (the differences only being a couple of documents that I worked on and some downloads, no updates or significant changes were made).

**Comment by digint** [comment]
As I can see, there are no march snapshots of `rtfs` in `/mnt/subvolroot/.snapshots/`. This means an incremental btrfs send/receive is not possible anymore, since there is "No common parent subvolume present" (see your btrbk log).
btrfs always needs an anchor on both sides for incremental backup, since "btrfs send -p" does not know anything about the target.

I have a question though: Did btrbk delete the march snapshots, or did you do it by hand? btrbk should never delete snapshots if backup failed (which is true if btrbk could not find the target volume)

**Comment by TH3L0N3WOLF** [comment]
Okay, I understand now. 

I only delete snapshots when I need to transfer them to the backup drive to prevent the creation of currentdate_1snapshots. However, I only delete the current day and nothing before. 

systemctl -u btrbk showed that it didn't delete any snapshots, so it was probably another program on my end. I'll do a closer inspection now.

**Comment by TH3L0N3WOLF** [comment]
Upon closer inspection, I found a program that does bi-weekly defragments to blame. Since btrfs is unable to do snapshot-aware defrags, it compromised by wiping out my snapshots. 

I'll go submit a bug report on their end (if this "is" is a bug).
Sorry about that, another hit and miss.
