### ISSUE TITLE
How does btrbk handle snapshot removals? 

### ISSUE THREAD

**Issue by ceremcem** [digint/btrbk#136]
How does `btrbk` behave in [such a scenario](https://superuser.com/questions/1198251/how-to-guarantee-integrity-of-snapshots-of-a-btrfs-filesystem): 

# Removing one or more differencing snapshots

Say the snapshots I have so far are as follows:

* v1: Initial snapshot (23 GB)
* v2: First differencing snapshot (1 GB) (added 100 MB and 900 MB files)
* v3: Second differencing snapshot (1 GB) (deleted 900MB file, added a 400MB file, and a 600 MB file)
* v4: Third differencing snapshot (100 MB) (added a 100 MB file) 
* v5: I'm out of space, I need to delete snapshots `v2` and `v3`.
* v6: Fourth differencing snapshot (50 MB) 

There are problems: 

1. One MUST not be able to delete `v2` and `v3`. (If that person wants to make room, then merge of `v2` and `v3` MUST be created and named as `v3.1`, where `v3.1` SHOULD obsolete `v2` and `v3`, then `v2` and `v3` SHOULD be deleted on every backup location.)
2. If any of differencing snapshots are deleted accidentally(!), we have to take a full snapshot next time. So, creating a differencing snapshot called `v6` is totally useless (this magical tool should warn us for that). We should create a full snapshot called `v6` and  delete all old (`v{1..5}`) snapshots afterwards. In order to minimize the transferred data, remote backup location(s) should merge all of its backups (`v{1..5}`) with a `rw` layer, and use `rsync` to propogate (download) the changes.

**Comment by digint** [comment]
I'm not sure if I fully understand your scenario, especially what you call "differencing snapshots". If you want to make room, deleting `v2` would be the best option, as it is the only snapshot still holding references to the 900MB file. After deletion, the references are gone and the space can be reused by btrfs.

Now what btrbk always does is to make sure that the latest snapshot is never deleted. The most aggressive policy is to configure `snapshot_preserve=no, snapshot_preserve_min=latest`, which results in deletion of all snapshot except the latest (after send/receiving the incremental backup). This makes sure that incremental backups always work as long as you don't delete the latest common snapshots manually. This matches with your description in (2).

What I don't understand here is why you want to `rsync` stuff, as the situation on the backup disk is the same as on the source. You say that "If any of differencing snapshots are deleted accidentally(!), we have to take a full snapshot next time", which is not true. You can delete any of the snapshots except `v6` and you will still be able to make incremental backups, using `v6` as parent (which is exactly what btrbk does).

If you accidentaly deleted `v6`, btrbk will find the *latest common subvolumes* by comparing UUID's and use this as parent for the next incremental backup, which yould be `v5` in your scenario.

**Comment by ceremcem** [comment]
A-ha! Btrfs snapshots work just like hardlinks then?

**Comment by digint** [comment]
yes, kind-of, but deeper down in the file system layer, where the references are not per-file, but rather per-extent (low-level data blocks).

**Comment by ceremcem** [comment]
Thank you for your explanation. I think I should give `btrbk` a try (with my fancy scenarios) and then come back here if I have any further questions.

**Comment by ceremcem** [comment]
I was actually curious about the question: "Who is calculating the difference then?" at that time. Now I understand that `btrfs send -p first second` calculates the difference and `btrfs receive` checks if it has the `first` snapshot, if it has, it builds `second` snapshot with the difference.
