### ISSUE TITLE
Backups don't resume

### ISSUE THREAD

**Issue by HaleTom** [digint/btrbk#137]
Key features says:
> Resume of backups (if backup target was not reachable for a while)

How do I simulate "target not reachable" so as to be able to resume a backup?

Or in other words: How do I interrupt (or invoke)`btrbk` such that it will resume?

Pressing `^C` during a `btrbk archive` and then running the same command again gives:

```!!! Target "/mnt/backup/btrbk-home" aborted: Target subvolume "/mnt/backup/btrbk-home/home.20170219T2100" already exists```

**Comment by digint** [comment]
> Pressing `^C` during a `btrbk archive` and then running the same command again gives:
> 
> ```!!! Target "/mnt/backup/btrbk-home" aborted: Target subvolume "/mnt/backup/btrbk-home/home.20170219T2100" already exists```

`btrbk archive` is special on this behalf, as it works without config files. This means if you have unfinished backups you cannot simply run `btrbk clean`, as btrbk does not know where to look for unfinished backups, and you have to delete the subvolume by hand: `btrfs sub delete /mnt/backup/btrbk-home/home.20170219T2100`.

The "resume of backups" feature is related to "normal" operation `btrbk run`, which automatically handles backup tasks that could not be performed in a previous run in case of unmounted disks or unavailable network.

> How do I simulate "target not reachable" so as to be able to resume a backup?

Hitting ctrl-c is a bad idea, as it leaves behind unfinished backups ("garbled subvolumes" as btrbk calls it), which have to be removed using `btrbk clean`. Better ways to test it is to execute `btrbk run` after unplugging the network cable or unmounting the target disks. btrbk will create all the snapshots an keep them as long as the target is unavailable. As soon as you run it with targets available again, the backups of the snapshots from previous runs will be resumed.

**Comment by HaleTom** [comment]
Thanks, the not being able to auto-clean using `archive` makes sense.

1. So if a `target` is offline, then local `snapshot`s will be preserved based on `target_preserve` until the target comes online and the backups succeed?

1. My question was actually about resuming the `target`'s receiving of a snapshot (especially the large initial one). Eg, if `--progress` is 50% and the connection dies, can it continue from there or does it need to start again?

**Comment by digint** [comment]
> So if a target is offline, then local snapshots will be preserved based on target_preserve until the target comes online and the backups succeed?

Yes, actually ALL snapshots (which are related to the disconnected target) are preserved in such a condition, as btrbk does not know anything about the target.

> Eg, if --progress is 50% and the connection dies, can it continue from there or does it need to start again?

No, btrbk cannot resume partial transmits, all data have to be re-transmitted (after `btrbk clean`). Maybe one day btrfs-progs offer such a resume option of send/receive, but I guess this one is pretty hard to implement.

**Comment by LollenJumplan** [comment]
Just noting here, that I regularly have these garbled suvolumes doe to various reasons, and my backup script always calls "btrbk clean" first. If everything is ok the "btrbk clean" does nothing, else the garbled subvolumes will be removed. This approach has always worked flawlessly for me.

**Comment by HaleTom** [comment]
Thanks @digint and @LollenJumplan.

To resume a `btrfs send` of an initial backup, check out [`buttersync`](https://github.com/mehlbox/buttersync).

**Comment by digint** [comment]
@HaleTom As far as I know buttersync does resume only for it's Amazon S3 feature, which is not on a btrfs file system (more like btrbk's "target raw" feature). I quickly checked the code and could not see anything related to resuming a btrfs send stream. Please correct me if I'm wrong, as it would be really nice to have something like this in btrbk.

**Comment by ceremcem** [comment]
Did anyone try `buttersink` resume feature out? I didn't even perform a successful transfer over SSH with `buttersink`.

**Comment by mehlbox** [comment]
Some of you guys mix up ```buttersync``` with ```buttersink```

**Comment by HaleTom** [comment]
Thanks @mehlbox, I did mix up [buttersync](https://github.com/mehlbox/buttersync) with [buttersink](https://github.com/AmesCornish/buttersink).

**Both** claim to be able to deal with resuming via ssh to a btrfs target:

[buttersync](https://github.com/mehlbox/buttersync):
> buttersync-remote-sync.sh:
> * transfer snapshot to a remote destination
> * interrupted transfer will be resumed by next run


[buttersink](https://github.com/AmesCornish/buttersink):
> * Transfers between a local btrfs filesystem, Amazon S3 bucket, other local btrfs filesystems, or remote btrfs filesystems over ssh
