### ISSUE TITLE
Diff function broken in .16

### ISSUE THREAD

**Issue by grondinm** [digint/btrbk#14]
Not sure if this is something i am doing of if it's really broken. I know i did a diff before just can remeber on what version. With .16 this is the output of trying to diff 2 sub volumes

 btrbk -c /etc/btrbk/btrbk.conf diff "/media/Storage3/Backup/@HomeBackup/@Home.20150417" "/media/Storage3/Backup/@HomeBackup/@Home.20150420"

ERROR: process died unexpectedly (btrbk v0.16)
Please contact the author: Axel Burri <axel@tty0.ch>

Stack Trace:
----------------------------------------
Died at /usr/bin/btrbk line 204.
 at /usr/bin/btrbk line 101.
        main::__ANON__("Died at /usr/bin/btrbk line 204.\x{a}") called at /usr/bin/btrbk line 204
        main::config_key(undef, "btrfs_progs_compat") called at /usr/bin/btrbk line 523
        main::btr_subvolume_list("/media/Storage3/Backup/\@HomeBackup/\@Home.20150417", undef, "subvol_only", 0) called at /usr/bin/btrbk line 649
        main::btr_tree("/media/Storage3/Backup/\@HomeBackup/\@Home.20150417") called at /usr/bin/btrbk line 1220

My btrbk.conf

http://pastebin.com/9J9w6ZaU

**Comment by digint** [comment]
I'm currently doing a big refactoring and code-cleanup of btrbk. Expect this issue to be fixed in the next clean and shiny version :)

**Comment by grondinm** [comment]
Cool. Thanx for all your work.

**Comment by digint** [comment]
Fixed in: 01a25ad4df4c5e3c0fa43798f0b86ab43a9f09ea

**Comment by digint** [comment]
Fix included in btrbk-0.17.0
