### ISSUE TITLE
Consider adding "Integrate with package install hooks" section in FAQ

### ISSUE THREAD

**Issue by ceremcem** [digint/btrbk#148]
We should add "Integrate with package install hooks" section in FAQ in order to achieve `snapper`'s `apt-get` hook goal. 

Snapper takes a snapshot before `apt-get install` runs, which is handy for resolving any problems occurred after a package install.

**Comment by digint** [comment]
does anybody know how this is done? unfortunately, I don't have any boxes which run debian-based distros, and I actually have no clue how package install hooks are triggered.

**Comment by ceremcem** [comment]
Actually this was a kind of "note to myself", I'm on it :)

**Comment by PsyBlade42** [comment]
This is actually quite easy to do. Simply put a file into `/etc/apt/apt.conf.d/` (e.g. `70btrbk`) that has the following content:

    // create a btrfs snapshot before (un)installing packages
    Dpkg::Pre-Invoke {"/usr/sbin/btrbk run";};

Been running that with a different command for years.

**Comment by ceremcem** [comment]
Thank you, works great!

**Comment by digint** [comment]
@PsyBlade42 something like this looks of for you? 5b47f6190794e169c4bc56f64443d2ecb386db93

**Comment by PsyBlade42** [comment]
Looks good to me.

**Comment by digint** [comment]
merged in: 83a38cb39069618bc35916750294c460a267fc97, thanks
