### ISSUE TITLE
Create LXC virtual machines from any snapshot

### ISSUE THREAD

**Issue by ceremcem** [digint/btrbk#153]
I don't know if this is the correct location for any announcements but `btrbk` users might be interested in: 

If anyone is interested in creating an LXC virtual machine from any of his/her snapshots (like me), you can use following script: https://github.com/aktos-io/lxc-to-the-future

**Comment by digint** [comment]
> I don't know if this is the correct location for any announcements

It's not, posts like this pollute the issues tracking system with things unrelated to btrbk. As far as I know, github does not provide a mechanism for this.

Maybe I'll create some wiki pages one day, these could then also have a "further links", or "related projects" page.
