### ISSUE TITLE
the snapshots container has to be a subvolume?

### ISSUE THREAD

**Issue by diraimondo** [digint/btrbk#155]
I'm using the following config to keep snapshots of a remote server to be keep in sync using `rsync` as explained in the documentation:

```
volume /mnt/btrfs-backup-pool/remote-server
  snapshot_preserve_min latest
  snapshot_preserve no
  subvolume ROOT-sync
    snapshot_name ROOT
    snapshot_preserve 5d 10w 3m
```
in order to make it works I had to convert the regular folder '/mnt/btrfs-backup-pool/remote-server` in a subvolume: I'm wondering why this is strictly necessary as it should be sufficient to be a container of subvolumes (as I use in other configurations).

**Comment by digint** [comment]
The `volume` needs to be a btrfs subvolume (can be the root subvolume id=5 or any other). The `snapshot_dir` (relative to "volume", where the snapshots are created) can be a regular directory. As this option is not set, the snapshots are created directly in `volume` with your config.

Note that `subvolume` can be a relative path, so you can change your config (assuming that `/mnt/btrfs-backup-pool` is a subvolume) as follows:

```
volume /mnt/btrfs-backup-pool
  snapshot_dir remote-server/btrbk_snapshots
  subvolume remote-server/ROOT-sync
```
With this config, `remote-server` can be a regular directory.

**Comment by diraimondo** [comment]
It looks a bit arbitrary: I agree that the `snapshot_dir` can be a folder (as usually done) and that the `subvolume` has to be a btrfs volume. I don't see the necessity to use the requirement that the path denoted by `volume' has to be a btrfs volume (it is usually the root of the pool but I don't see the point). In all the examples in the documentation the `volume` is the root of the pool but in order to use the "Example: multiple btrbk instances" I have to use the `snapshot_dir` field: this is not a big deal but I think that the code is too restrictive about this. You can close this report if you don't think so.

my 2¢

**Comment by digint** [comment]
It looks arbitrary, agreed. Fact is that btrbk needs some "root anchor" to call `btrfs subvolume list` on (`volume` in btrbk.conf), in order to get/parse all the subvolumes below. As I have to rely on btrfs-progs (I don't want to re-implement all low-level stuff), there is no way around this, as `btrfs subvolume list` can give ambiguous results (see my old post on linux-btrfs: https://www.spinics.net/lists/linux-btrfs/msg47822.html).
