### ISSUE TITLE
Is it safe to run btrbk while receiving?

### ISSUE THREAD

**Issue by ian-kelling** [digint/btrbk#158]
If I run btrbk on host a sending to host b, and btrbk -r on b sending to host c, at different overlapping times, will b send the snapshots it got from a on to c? Or will btrbk on b be confused by a partially sent subvolume from a? I suggest adding the answer to the documentation.

**Comment by digint** [comment]
btrbk will identify the partially sent subvolume as incomplete/garbled, and should skip sending the snapshot from a to c. I think I never really tested this use case, but in theory it should wokr this way.

**Comment by ian-kelling** [comment]
Thanks. I will be testing it. I'll review docs to see if an addition is appropriate so closing this.
