### ISSUE TITLE
btrbk does not work if a subvol being backed up was received from somewhere else

### ISSUE THREAD

**Issue by bestmethod** [digint/btrbk#159]
So, I have a subvolume on source machine, which has been received from somewhere else (data migration). When I back that up (ssh to target btrfs too), btrbk, on next run, says that the target subvolume is not the target of source.

This is due to the comparison of btrfs subvolume UUIDs. In a normal world:
source UUID->target received UUID
In a world where you are backing up a subvolume that was once in the past received from somewhere else:
source UUID != target received UUID.
source received UUID == target received UUID.

For fix, if source->UUID != target->received_UUID, then source->received_UUID should be compared as well.

Below, 2 volumes, @lxc in source is correct, and has been created on source. Second subvolume, apache, has been received from another machine to source, and so backup to target no longer works due to UUID comparison issue.

For workaround, at the moment, I have enabled progs compat, which skips UUID checks, but would be nice if that worked in this scenario in machine migrations.

Source:
--------
root@s20237969:~# btrfs subvol show /data/@snapshots/@lxc.20170627
/data/@snapshots/@lxc.20170627
        Name:                   @lxc.20170627
        UUID:                   8aa09dcb-6a52-7543-b9df-e1ae8d2a0438
        Parent UUID:            d37d3c46-97d6-854b-813f-8b3142568e74
        Received UUID:          -
        Creation time:          2017-06-27 11:26:29 +0100
        Subvolume ID:           1106
        Generation:             116566
        Gen at creation:        116565
        Parent ID:              999
        Top level ID:           999
        Flags:                  readonly
        Snapshot(s):

root@s20237969:~# btrfs subvol show /data/@snapshots/apache2.20170627
/data/@snapshots/apache2.20170627
        Name:                   apache2.20170627
        UUID:                   2eb678f2-613f-4741-96a6-b3ddece01e21
        Parent UUID:            d393402a-36a1-ab47-ae0b-2807e635addf
        Received UUID:          2f6ee9b9-0dda-0c42-96bc-51e596bf3608
        Creation time:          2017-06-27 11:26:46 +0100
        Subvolume ID:           1109
        Generation:             116569
        Gen at creation:        116568
        Parent ID:              999
        Top level ID:           999
        Flags:                  readonly
        Snapshot(s):

Target:
------
root@glonekbackup:/data/@backups# btrfs subvol show /data/@backups/@lxc.20170627                                                                                                 
/data/@backups/@lxc.20170627
        Name:                   @lxc.20170627
        UUID:                   78410e93-2b79-d34d-ae0a-297aab90287a
        Parent UUID:            -
        Received UUID:          8aa09dcb-6a52-7543-b9df-e1ae8d2a0438
        Creation time:          2017-06-27 12:27:11 +0200
        Subvolume ID:           274
        Generation:             2366
        Gen at creation:        47
        Parent ID:              259
        Top level ID:           259
        Flags:                  readonly
        Snapshot(s):
                                @backups/@lxc.20170628

root@glonekbackup:/data/@backups# btrfs subvol show /data/@backups/apache2.20170627
/data/@backups/apache2.20170627
        Name:                   apache2.20170627
        UUID:                   c9cbcf79-96cc-c645-986e-034902001e23
        Parent UUID:            -
        Received UUID:          2f6ee9b9-0dda-0c42-96bc-51e596bf3608
        Creation time:          2017-06-28 10:48:56 +0200
        Subvolume ID:           1032
        Generation:             2477
        Gen at creation:        2470
        Parent ID:              259
        Top level ID:           259
        Flags:                  readonly
        Snapshot(s):

Kind Regards,

Robert Glonek

**Comment by digint** [comment]
What version of btrbk do you use? There was a fix for this in v0.25.0 (see #114, fixed in d02f67a9248c6eac5e918ab4d43056baf2d5c11e):

btrbk regards two subvolumes as "identical", if:
- src.uuid == target.received_uuid
- src.received_uuid == target.received_uuid
- src.received_uuid == target.uuid (since btrbk-v0.25.0)

Also note that Kernels <4.4 have a bug when re-sending subvolumes (the received subvolumes will have incorrect received_uuid, see <http://thread.gmane.org/gmane.comp.file-systems.btrfs/48798>)

**Comment by bestmethod** [comment]
Hello,

You are right and I feel as sheepish. ubuntu 1604 has got 0.22.2 and it has link to github in description, so I clicked on that and assumed that's the latest version. Terribly sorry, and many thanks for the fast turnaround. I'll update to 0.25 :)

Regards,

Rob

**Comment by Geremia** [comment]
You can comment out [lines 5364](https://github.com/digint/btrbk/blob/v0.27.1/btrbk#L5364)-5368 (in v0.27.1) if you don't like that it aborts when the Received UUID is set:
```
      if($svol->{node}{received_uuid} ne '-') {
        ABORTED($svol, "\"Received UUID\" is set");
        WARN "Skipping subvolume \"$svol->{PRINT}\": $abrt";
        next;
}
```
Those lines don't seem necessary to me.

**Comment by digint** [comment]
> You can comment out lines 5364-5368 (in v0.27.1) if you don't like that it aborts when the Received UUID is set

@Geremia You'll get into trouble when doing this, see FAQ entry: [I'm getting an error: Aborted: "Received UUID" is set](/digint/btrbk/blob/master/doc/FAQ.md#im-getting-an-error-aborted-received-uuid-is-set). Follow the instructions there to get rid of the received_uuid.
