### ISSUE TITLE
Example of restoring

### ISSUE THREAD

**Issue by grondinm** [digint/btrbk#16]
So this is probably somewhere on the net but i can't seem to find anything with good examples. It would be nice to have an example of how one would go about restoring from an incremental snapshot/backup. Now that i think about it if the original full backup is gone due to retention policy then are any files not modified between it and the last incremental before it was deleted no longer a part of the "backup". The reason i ask is because i'm thinking of switching distros and would like to just use the snapshots/backups i already have to restore my home partition instead of creating a new one.

**Comment by grondinm** [comment]
Ok I think i finally found the proper documentation and have understood that i can restore from a snapshot using rsync or the like or simply copy and past...if that is wrong please let me know. Sorry for posting this here my lack of understanding was frustrating had to post somewhere(sometimes it take me a little bit to grab or remember concepts)

**Comment by digint** [comment]
However, I added a "Restoring Backups" section in `README.md`: c4550e87d9c46507ef710b46c200b0b3a67968b7

**Comment by grondinm** [comment]
Thank you
