### ISSUE TITLE
Support Samba vfs_shadow_copy2 timeformat for "Previous Versions" to Windows clients

### ISSUE THREAD

**Issue by Gatak** [digint/btrbk#170]
It is very useful to export snapshots as "Previous Versions" to Windows clients. The Samba VFS module vfs_shadow_copy2 requires a specific time format to work. It is  described here: https://www.samba.org/samba/docs/man/manpages/vfs_shadow_copy2.8.html

The snapshot naming convention is @GMT-YYYY.MM.DD-hh.mm.ss, where:

> YYYY is the 4 digit year
> MM is the 2 digit month
> DD is the 2 digit day
> hh is the 2 digit hour
> mm is the 2 digit minute
> ss is the 2 digit second.
> The vfs_shadow_copy2 snapshot naming convention can be produced with the following date(1) command:
> 
> 	TZ=GMT date +@GMT-%Y.%m.%d-%H.%M.%S

Defaullt format is: 
> shadow:format = "@GMT-%Y.%m.%d-%H.%M.%S"

The format used by btrbk "short", "long" or "long-iso" does not work. 
The following works:
> snapshot_%Y%m%d-%H%M%S
>![snap1](https://user-images.githubusercontent.com/1469150/28522815-d4d06ab8-7079-11e7-8441-176e17584a6f.PNG)

This does not:
> snapshot.%Y%m%dT%H%M
>![snap2](https://user-images.githubusercontent.com/1469150/28522814-d4cfe958-7079-11e7-8cf9-33d526b9577e.PNG)

Windows seems to require the specific GMT format:
![snap3](https://user-images.githubusercontent.com/1469150/28523082-1773bd2e-707b-11e7-9ce6-663cf895b7dc.PNG)

**Comment by digint** [comment]
Guess it needs the seconds then.
What about `snapshot.%Y%m%dT%H%M%S%z` along with `timestamp_format long-iso`? If samba really uses strptime(3) internally, this should work.

I'd hate to implement more time formats just for this purpose, that's why I implemented "iso" time format in the first place...

**Comment by Gatak** [comment]
After checking some more, it seems to be a problem on samba and subfolders of a share, and not directly related to the time format. Though seconds would be nice, it may not be needed for Samba. I need to do some more debugging on Samba side to find out.

**Comment by Gatak** [comment]
It seems to be a fully Samba issue with Win10 clients. The time format from btrbk work with Samba and Win7.
