### ISSUE TITLE
ERROR numbers need some documentation

### ISSUE THREAD

**Issue by ian-kelling** [digint/btrbk#177]
For example, in my syslog:

    Aug 27 15:11:12 hostname btrbk[24880]: send-receive ERROR 27 /mnt/root/btrbk/o.20170827T151042-0700 ssh://hostname/mnt/root/btrbk/o.20170827T151042-0700 ssh://x2/mnt/root/btrbk/o.20170823T095412-07

I've also seen error 606. There is nothing in the btrbk manuals about these codes.

Both times the error was resolved when I updated btrbk, but I can't tell if it would still output these codes in the newer version. Close this if it doesn't output them anymore.

**Comment by digint** [comment]
Heh, well yes looks like error codes, but it's actually "duration":

```
transaction_log
    [...]
    format: "localtime type status duration target_url source_url parent_url message".
```

Guess I really need to change this (probably completely drop "duration" in transaction lines).

**Comment by digint** [comment]
Removed confusing "duration" column for transaction_log/transaction_syslog: 88aa8c1fea6eb4205b9acaa15efaeccf46c0b309
