### ISSUE TITLE
btrbk fails to handle subvolumes whose names contain spaces

### ISSUE THREAD

**Issue by c-14** [digint/btrbk#181]
When trying to backup a subvolume containing spaces with btrbk, it fails with:
```
ERROR: Ambiguous file for option "subvolume" in "/etc/btrbk/4TB.conf" line 54: Test/Test String
ERROR: Failed to parse configuration file
```

If replace the subvolume name in /etc/btrbk/4TB.conf with Test* instead of Test String, I get:
```
ERROR: Unsafe command `btrfs subvolume snapshot -r /media/Test/Test String /media/backups/Test String.20170908` (offending string: "/media/Test/Test String", "/media/backups/Test String.20170908")
ERROR: Failed to create btrfs subvolume snapshot: /media/Test/Test String -> /media/backups/Test String.20170908

ERROR: process died unexpectedly (btrbk v0.25.1)
Please contact the author: Axel Burri <axel@tty0.ch>

Stack Trace:
----------------------------------------
invalid url: /media/Test/Test String at /usr/sbin/btrbk line 1775.
 at /usr/sbin/btrbk line 262.
        main::__ANON__("invalid url: /media/Test/Test String at /usr/sbin/btrbk line "...) called at /usr/sbin/btrbk line 1775
        main::vinfo("/media/Test/Test String", HASH(0x561c59cc17a0)) called at /usr/sbin/btrbk line 359
        main::ABORTED(HASH(0x561c59da09c0), "Failed to create snapshot: /media/Test/Test String -> /media/"...) called at /usr/sbin/btrbk line 5126
```

Removing mentions of the subvolume containing spaces allows btrbk to run successfully (for the other subvolumes)

**Comment by ck-kc** [comment]
So how do I specify a subvolume containing a space? Putting in quotes or escaping with backslash doesn't work?

**Comment by digint** [comment]
> So how do I specify a subvolume containing a space?

You can't. The commands/tools used by btrbk all have their own semantics and escapes, which makes it really painful to implement correctly.

The trick is not to create subvolumes containing spaces, sorry for the inconvenience.

**Comment by ck-kc** [comment]
I had a workaround using symlinks that don't contain spaces. This worked very well for years, but that workaround seems to have broken on latter versions of btrbk.
