### ISSUE TITLE
pruning snapshots

### ISSUE THREAD

**Issue by jmgant** [digint/btrbk#186]
New to btrfs.

I have regular, hourly snapshots of /home. If I need to prune those snapshots, what is the best means to remove unwanted snaps yet preserve the btrbk workflow i.e. creating child snapshots of parent snaps if one of the parents is gone?

**Comment by asymmetric** [comment]
Should this be closed?

**Comment by digint** [comment]
> Should this be closed?

thanks, yes, `btrbk prune` is the answer, included in btrbk-0.26.0
