### ISSUE TITLE
Request: add quota group (qgroup) support to the `archive` command

### ISSUE THREAD

**Issue by dpantel** [digint/btrbk#189]
I've been running the 'qgroup' branch for a bit now and it seems to work well.  The one thing that is missing is qgroup support to the `archive` command.  Quota groups are (automatically) created for new snapshots, but not deleted on pruning.

See #49 for details on qgroups.

**Comment by digint** [comment]
qgroup support is now in master branch, including a fix for this issue: e9a517f161fa4803651dd3ec9855d00ed464e56f
