### ISSUE TITLE
No real path provided by "btrfs subvolume show" for subvolume

### ISSUE THREAD

**Issue by Geremia** [digint/btrbk#193]
With btrfs-progs-v4.13.2 and btrbk 0.25.1, I get this error:
```
No real path provided by "btrfs subvolume show" for subvolume
```

**Comment by digint** [comment]
duplicate of #192, should be fixed on master branch

**Comment by digint** [comment]
On second thought, I'm not sure if this is really related. I can't reproduce the error here.

@Geremia Can you please check if the problem persists with latest version from master?

**Comment by Geremia** [comment]
@digint Yes, master works. thanks
