### ISSUE TITLE
snapshot_preserve_min has no effect

### ISSUE THREAD

**Issue by Geremia** [digint/btrbk#194]
In my btrbk.conf, I have:
```
snapshot_preserve_min       latest
snapshot_preserve           no
```
Yet, btrbk doesn't delete the older snapshots. I'm having this problem with btrbk 0.26.0 and btrfs-progs-v4.13.2. I wasn't having this problem before.

**Comment by digint** [comment]
I'm not able to reproduce this. Could you please provide me a debug log of this?

```
# btrbk -l debug --print-schedule dryrun
```

**Comment by Geremia** [comment]
`ls /mnt/btr_pool/btrbk_snapshots/`:
```
rootfs.20171021
rootfs.20171022
rootfs.20171023
```
Here's [the output of `btrbk -l debug --print-schedule dryrun`](https://gist.githubusercontent.com/Geremia/1d8853f30f61b6133047589fb4e57a44/raw/d9501aeb4490c7c3750057d46a36de4baad7f907/btrbk.log).

**Comment by digint** [comment]
In the output, I see "scheme: 1d+", which is printed for `snapshot_preserve_min 1d`. Are you sure that your config line `snapshot_preserve_min latest` is not superseded by another `snapshot_preserve_min` setting? Can you paste your full config for further analysis?

**Comment by Geremia** [comment]
@digint Here's [my log for today](https://gist.githubusercontent.com/Geremia/52a9cee9b48fa12ee9902f077cb47362/raw/5d3f77c1980e0dd7467572f8cd121e874805474e/gistfile1.txt) and [`btrbk.conf`](https://gist.githubusercontent.com/Geremia/61092eaf125467ba1ba31e382355dc7e/raw/254d56f53089126f5de59a87c6dc3d819a0e0daa/gistfile1.txt).

**Comment by digint** [comment]
As I suspected, you have:

```
snapshot_preserve_min       1d
snapshot_preserve           no
```

This means that all snapshots from last day are preserved, not only the latest.

I can not see why the send/receive aborted (from your transaction log), probably the disk was not mounted?

**Comment by Geremia** [comment]
@digint The disk was mounted, but I think it was full.
I think `1d` instead of `latest` was the issue.

**Comment by Geremia** [comment]
@digint 
>I can not see why the send/receive aborted (from your transaction log), probably the disk was not mounted?

I think the issue was that the disk was too full, and for some reason it said:
>No common parent subvolume present, creating full backup...
Why would there be no common parent subvolume present?

**Comment by Geremia** [comment]
I'm still getting the original problem again, even with `snapshot_preserve_min       latest`; it keeps all snapshots and not simply the latest.

Also, I'm still getting this issue:

> 2017-10-28T01:45:09-0700 send-receive ERROR /run/media/Geremia/Backup/mylaptop/rootfs.20171027 /mnt/btr_pool/btrbk_snapshots/rootfs.20171027 - -

I haven't had a successful backup in over a month now. I'm not sure what's causing this send/receive error. The destination drive has plenty of space to do a full backup.

**Comment by digint** [comment]
If an error occurs while doing a send/receive operation, btrbk does not delete any source subvolumes. 

I can't tell by your transaction-log line what exactly failed, but sometimes this happens, and it's usually related to "broken" subvolumes on either source or target side (see #91). The btrfs command which failed here is:

```
btrfs send /run/media/Geremia/Backup/mylaptop/rootfs.20171027 | btrfs receive /mnt/btr_pool/btrbk_snapshots/
```

 For further analysis, I would need the STDERR output of btrbk, ideally with `btrbk -l debug`.

**Comment by Geremia** [comment]
@digint 
```
[send/receive] source: /mnt/btr_pool/btrbk_snapshots/rootfs.20171030_2
[send/receive] target: /run/media/Geremia/Backup/mylaptop/rootfs.20171030_2
### btrfs send /mnt/btr_pool/btrbk_snapshots/rootfs.20171030_2 | btrfs receive /run/media/Geremia/Backup/mylaptop/
Command execution failed (exitcode=1): `btrfs send /mnt/btr_pool/btrbk_snapshots/rootfs.20171030_2 | btrfs receive /run/media/Geremia/Backup/mylaptop/`
WARNING: [send/receive] (send=/mnt/btr_pool/btrbk_snapshots/rootfs.20171030_2, receive=/run/media/Geremia/Backup/mylaptop) At subvol /mnt/btr_pool/btrbk_snapshots/rootfs.20171030_2
WARNING: [send/receive] (send=/mnt/btr_pool/btrbk_snapshots/rootfs.20171030_2, receive=/run/media/Geremia/Backup/mylaptop) At subvol rootfs.20171030_2
ERROR: send ioctl failed with -2: No such file or directory
ERROR: unexpected EOF in stream
ERROR: Failed to send/receive btrfs subvolume: /mnt/btr_pool/btrbk_snapshots/rootfs.20171030_2  -> /run/media/Geremia/Backup/mylaptop
send/received failed, deleting (possibly present and garbled) received subvolume: /run/media/Geremia/Backup/mylaptop/rootfs.20171030_2
```
Perhaps this is a Btrfs issue, but why would send/receive hit an unexpected EOF?

**Comment by digint** [comment]
another user had this before, see #162
