### ISSUE TITLE
multi targets not working with subvolume

### ISSUE THREAD

**Issue by yrpeng** [digint/btrbk#197]

**Comment by yrpeng** [comment]
I have two confs:
==> /etc/btrbk/btrbk.conf <==
ssh_identity               /etc/btrbk/ssh/id_rsa

snapshot_preserve_min      1d
snapshot_preserve          3d 1w

target_preserve_min        no
target_preserve            0d 2w 1m

snapshot_dir               SnapShot

volume /partition/nvme1
  target_preserve 1d 1w 1m
  subvolume home
  subvolume home/Documents
    target send-receive /backup/

==> /etc/btrbk/Documents.conf <==
ssh_identity               /etc/btrbk/ssh/id_rsa
ssh_port 12222

timestamp_format long
stream_compress lz4

snapshot_preserve_min      1h
snapshot_preserve          3h 3d 2w

target_preserve_min        1h
target_preserve            2h 1d 1w

snapshot_dir               SnapShot

volume /partition/nvme1
  subvolume home/Documents
    target send-receive ssh://SOMEHOST/partition/ssd1/SnapShot

Then btrbk.conf is executed in cron.daily while Documents.conf is in hourly

The home folder is backed up fine.
However, only SOMEHOST received the backup of Documents but not backup/.

**Comment by digint** [comment]
Is this resolved?

Bug:
```
volume /partition/nvme1
  target_preserve 1d 1w 1m
  subvolume home
  # ^^^ no target defined here, this will NOT be sent to "/backup/" !
  subvolume home/Documents
    target send-receive /backup/
```

You probably want this:
```
volume /partition/nvme1
  target_preserve 1d 1w 1m
  target send-receive /backup/
  # ^^^ targets defined in front of subvolume sections propagate to all subvolume sections
  subvolume home
  subvolume home/Documents
```

Hint: run `btrbk config print` to see how btrbk interprets this.
