### ISSUE TITLE
Make error - generating manpages - xsltproc returned exit status 5

### ISSUE THREAD

**Issue by channeladam** [digint/btrbk#199]
This error is occurring when building btrbk from the latest Arch AUR:

a2x: **ERROR: "xsltproc"**  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/etc/asciidoc/docbook-xsl/manpage.xsl" "/tmp/pamac-build-adam/btrbk/src/btrbk-0.26.0/doc/btrbk.1.xml" **returned non-zero exit status 5**                                                                                                                             

More trace context:

generating manpages...
make[1]: Entering directory '/tmp/pamac-build-adam/btrbk/src/btrbk-0.26.0/doc'
a2x -L -d manpage -f manpage btrbk.1.asciidoc
a2x: **ERROR: "xsltproc"**  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/etc/asciidoc/docbook-xsl/manpage.xsl" "/tmp/pamac-build-adam/btrbk/src/btrbk-0.26.0/doc/btrbk.1.xml" **returned non-zero exit status 5**                                                                                                                             
make[1]: *** [Makefile:46: btrbk.1] Error 1                                                                                              
make[1]: Leaving directory '/tmp/pamac-build-adam/btrbk/src/btrbk-0.26.0/doc'                                                            
make: *** [Makefile:76: man] Error 2          

thanks

**Comment by digint** [comment]
Sorry I can't reproduce it. I'm on gentoo here, using:
  - app-text/asciidoc-8.6.9-r2  (provides `a2x` command)
  - dev-libs/libxslt-1.1.29-r1  (provides `xsltproc`)

What version of libxslt are you using?

Trace:
```
# a2x -v -v -L -d manpage -f manpage btrbk.1.asciidoc
a2x: args: ['-v', '-v', '-L', '-d', 'manpage', '-f', 'manpage', 'btrbk.1.asciidoc']
a2x: resource files: []
a2x: resource directories: ['/usr/share/asciidoc/images', '/usr/share/asciidoc/stylesheets']
a2x: executing: "/usr/bin/asciidoc.py" --backend docbook -a "a2x-format=manpage"  --doctype manpage --verbose  --out-file "/home/axel/devel/btrbk/doc/btrbk.1.xml" "/home/axel/devel/btrbk/doc/btrbk.1.asciidoc"

asciidoc: reading: /usr/share/asciidoc/asciidoc.conf
asciidoc: reading: /home/axel/devel/btrbk/doc/btrbk.1.asciidoc
asciidoc: reading: /usr/share/asciidoc/docbook45.conf
asciidoc: reading: /usr/share/asciidoc/filters/code/code-filter.conf
asciidoc: reading: /usr/share/asciidoc/filters/graphviz/graphviz-filter.conf
asciidoc: reading: /usr/share/asciidoc/filters/latex/latex-filter.conf
asciidoc: reading: /usr/share/asciidoc/filters/music/music-filter.conf
asciidoc: reading: /usr/share/asciidoc/filters/source/source-highlight-filter.conf
asciidoc: reading: /usr/share/asciidoc/lang-en.conf
asciidoc: writing: /home/axel/devel/btrbk/doc/btrbk.1.xml

a2x: chdir /home/axel/devel/btrbk/doc
a2x: executing: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/usr/share/asciidoc/docbook-xsl/manpage.xsl" "/home/axel/devel/btrbk/doc/btrbk.1.xml"

Note: Writing btrbk.1

a2x: chdir /home/axel/devel/btrbk/doc
a2x: deleting /home/axel/devel/btrbk/doc/btrbk.1.xml
```

**Comment by channeladam** [comment]
Sorry for the delay, but that appears to have been fortunate. It is magically working again...
