### ISSUE TITLE
Allow to specify preserve_hour_of_day.

### ISSUE THREAD

**Issue by DL6AKU** [digint/btrbk#202]
As of now, btrbk always tries to save the midnight snapshots for the daily backups.

I run hourly snapshots and I am also often working late after midnight, so I would like my work to be saved at a configurable hour for my daily snapshots. For example at 0600 hours and not at midnight. 
btrbk would then try to preserve the next closest snapshot to 0600 hours for the daily snapshots.

This is important for me because I often have very large files (disk images) open, some are only temporary, that I have uncompressed while working and compressed while not working. If btrbk preserves the snapshots at midnight, when I am working on these and they are large, it wastes a lot of space in the backups even with dedup and file-system level compression.

**Comment by digint** [comment]
Sounds useful, added as enhancement (and I thought I'd never have to touch the scheduler again...).

I'm afraid I have no time for btrbk at the moment, I guess this will come some time at beginning of next year.

Note to self: adaption somewhere around here:
https://github.com/digint/btrbk/blob/master/btrbk#L3788

**Comment by ian-kelling** [comment]
This would be a good feature. As an example of another program with this feature, org-mode in emacs has this feature for time tracking, and calls it "extend-today-until" documented as "The hour when your day really ends.  Must be an integer."

**Comment by digint** [comment]
This one has finally made it to master: 5791d7217177df888e071f8c361b32e9601af8c0, e4a0938712c4b7543b3fd39a3aaa127d25f18f22

**Comment by digint** [comment]
Included in [btrbk-0.27.0](/digint/btrbk/releases/tag/v0.27.0)
