### ISSUE TITLE
encrypted home folder backup to external btrfs drive

### ISSUE THREAD

**Issue by vadimkim** [digint/btrbk#216]
Hello, 
     I would like to ask if doing backups of encrypted  `@home` folder to external hard drive that is also formated as btrfs makes it unencrypted by default? And what about snapshots - are they also unencrypted? 

Thanks

**Comment by digint** [comment]
I assume you are using disk encryption (such as dm-crypt with LUKS):

1. External harddrive: as long as this disk is not encrypted (which is a separate layer below btrfs), the data sent there will not be encrypted. If you want this, you also need to enable disk encryption on the external disk. Maybe your distro has some automagic support for this, a common way is using "cryptsetup".

2. Snapshots are always created on the same filesystem, so yes, these are also encrypted.

**Comment by vadimkim** [comment]
I am using only /home folder encryption. Think it is ecryptfs. I think I got your point - to encrypt entire external hard drive and just forget about anything else. Since encryption is not btrfs part than btrbk suppose to work above this layer. Thank you for the tip!
