### ISSUE TITLE
document examples in manpage

### ISSUE THREAD

**Issue by rickysarraf** [digint/btrbk#218]
The examples listed in the README.md file are very very useful. It would be nice to have these documented in the manpage, thus helping users who may not have an internet connection at that moment.

These days, manpages have embraced inclusion of examples and other section into them. So it should be fine to include it. Thoughts ?

**Comment by digint** [comment]
I already thought of this before, but my main concern is that this is quite a lot of text.

> These days, manpages have embraced inclusion of examples and other section into them. So it should be fine to include it. Thoughts ?

Maybe only put some basic examples in btrbk(1) ? I don't think that would help a lot.

Or create a separate "btrbk-examples" man page, this could at least be referenced from btrbk(1) and btrbk.conf(5).

> [...] thus helping users who may not have an internet connection at that moment

I hope that most distros also ship the README, e.g. on gentoo I can find it in `/usr/share/doc/btrbk-0.26.1/README.md.bz2`, which is where I always look for documentation when internet is down.

**Comment by Gatak** [comment]
I've seen that some apps include a thorough .config-example file. Perhaps that's an option too, unless that's already done? (it was a while since I installed btrbk from scratch)
