### ISSUE TITLE
Snapshot creation fails because backup target is unavailable

### ISSUE THREAD

**Issue by Witiko** [digint/btrbk#224]
Since my backup target is not always online, I would like to completely separate snapshot creation and backups and perform them at different times. The table in [the documentation](https://digint.ch/btrbk/doc/btrbk.1.html) suggests that the following command should not touch backups:

    # btrbk snapshot

However, when I run the command without my backup target available (at 10.0.0.10), the above command ends with error code 10 and the following stderr output:

```
WARNING: Skipping target "10.0.0.10:/media/backups": Failed to fetch subvolume detail
WARNING: Skipping target "10.0.0.10:/media/backups": Failed to fetch subvolume detail
WARNING: Skipping target "10.0.0.10:/media/backups": Failed to fetch subvolume detail
WARNING: Skipping target "10.0.0.10:/media/backups": Failed to fetch subvolume detail
WARNING: Skipping cleanup of snapshots for subvolume "/media/witiko/subvolume1", as at least one target aborted earlier
WARNING: Skipping cleanup of snapshots for subvolume "/media/witiko/subvolume2", as at least one target aborted earlier
WARNING: Skipping cleanup of snapshots for subvolume "/media/witiko/subvolume3", as at least one target aborted earlier
WARNING: Skipping cleanup of snapshots for subvolume "/media/witiko/subvolume4", as at least one target aborted earlier
```

I would expect the command to succeed regardless of whether or not the backup target is online.

**Comment by digint** [comment]
I already added a note about this in: c65f9374735c85b29f2bfeed364b75ddb7efaa2c (not yet released)

For snapshot deletion, the target is still required in order to determine the latest snapshot/backup pair (which is always preserved in order to keep the incremental backups possible).

This would work:
```
btrbk snapshot --preserve
```

**Comment by Witiko** [comment]
Come to think of it, that is actually a more sensible behavior than the one I was aiming at. I will postpone the snapshot deletion until the backup as suggested:

    # btrbk snapshot --preserve  # create snapshots
    # btrbk resume  # perform backup, prune snapshots and backups

Thank you for the clarification and the great tool.

**Comment by Witiko** [comment]
With c65f937, I am still getting error code 10 even when I specify the `--preserve` option:

```
# btrbk snapshot --preserve
WARNING: Skipping target "10.0.0.10:/media/backups": Failed to fetch subvolume detail
WARNING: Skipping target "10.0.0.10:/media/backups": Failed to fetch subvolume detail: not a subvolume: /media/backups
WARNING: Skipping target "10.0.0.10:/media/backups": Failed to fetch subvolume detail: not a subvolume: /media/backups
WARNING: Skipping target "10.0.0.10:/media/backups": Failed to fetch subvolume detail: not a subvolume: /media/backups

[... snip]

/media/witiko/subvolume4
+++ /media/witiko/subvolume4/btrbk_snapshots/subvolume4.20180505
!!! Target "10.0.0.10:/media/backups" aborted: Failed to fetch subvolume detail: not a subvolume: /media/backups

NOTE: Some errors occurred, which may result in missing backups!
Please check warning and error messages above.
# echo $?
10
```

**Comment by Witiko** [comment]
I have hotfixed this (see be653884a45cb6343dc36fe34043de5f720cc728) by putting lines 5209 through 5313 behind a `unless($preserve_snapshots && $preserve_backups)` condition.

**Comment by digint** [comment]
Thanks, I will have a look at this as soon as things get more quiet around here...
