### ISSUE TITLE
Subvolume wildcards are not recursive

### ISSUE THREAD

**Issue by lenucksi** [digint/btrbk#230]
Hi,
congrats to the nice tool you've created! 

However, here's one more usecase revolving around containers (or a general nested use). Consider this 101 standard setup of LXD (the cgroups-based container solution promoted by Ubuntu / Canonical)

```
274	156	262		var/lib/lxd/storage-pools/default
275	1038	274		var/lib/lxd/storage-pools/default/containers
276	154	274		var/lib/lxd/storage-pools/default/snapshots
277	27166	274		var/lib/lxd/storage-pools/default/images
278	156	274		var/lib/lxd/storage-pools/default/custom
283	63353	275		var/lib/lxd/storage-pools/default/containers/champion-arachnid
```
This is not catched by a configuration as visible here:

```
volume ssh://host/var/lib/lxd/storage-pools/default
  target send-receive      /some/target/btrfs/pool
  subvolume *
```
In this case, everything directly in the default folder will be transmitted, however, the actual container volume in ```containers``` will not be transmitted as it is one level below containers.
This should not happen, i.e. ```subvolume *``` should be recursive.

Also, this host has a subvolume for ```/var``` called ```var```. This subvolume contains a number of normal directories and files and the subvolumes visible above. 
Attempting to set the volume line to either of 

```
volume ssh://host/var/lib/
volume ssh://host/var/lib/lxd/
volume ssh://host/var/lib/lxd/storage-pools/
```
does not work since they are normal directories within a volume that are then rejected for not being a subvolume and thus being unable to fetch btrfs information.
It would be very useful if the relevant subvolume could be inferred up the path. Recursive processing down the path already has been mentioned.

As for a comparison zfs send/receive would probably be useful. It acts entirely recursive across volumes and accross snapshots. Especially for backup purposes, this is very useful.

Also, since, due to the required separate configurations for varies layers of nesting, these volumes end up in separate directories, restoring these nested constructions is made unnecessarily hard. (Although parts of this might be the fault of btrfs way of construction, too.)

Potentially relevant, related tickets are: #71, #127

**Comment by digint** [comment]
Thanks for the feedback!

The wildcards in btrbk do not expand directories, they work the same way as shell globs. You can use `*/*` if you want to expand all subdirectories.

The "storage-pools/default/snapshots/*" are probably read-only snapshots (I suppose these are created on every container launch), and as such can not be backed up by btrbk. The suggested strategy would be to have the snapshots managed by btrbk instead, i.e. running `btrbk snapshot` in the LXD start script with a config like this:
```
volume /mnt/btr_pool
  subvolume var/lib/lxd/storage-pools/default/containers/*/*

    # dont forget to create this directory first
    snapshot_dir    var/lib/lxd/storage-pools/btrbk_snapshots
```
With multiple containers, you probably hit the problem described in #127, so unless this is fixed you need to specify every container in btrbk.conf, e.g.:
```
  subvolume var/lib/lxd/storage-pools/default/containers/first_container/*
    snapshot_dir    var/lib/lxd/storage-pools/btrbk_snapshots/first_container
  subvolume var/lib/lxd/storage-pools/default/containers/second_container/*
    snapshot_dir    var/lib/lxd/storage-pools/btrbk_snapshots/second_container
  [...]
```

> Also, this host has a subvolume for /var called var. This subvolume contains a number of normal directories and files and the subvolumes visible above.

The "volume" always needs to point to a btrfs subvolume (or btrfs root, usually the mountpoint), and is used as anchor for the rest of the btrfs subvolume tree. This should be no problem, you probably need to change the config to something like:
```
# assuming "/" is the btrfs mountpoint containing the lxd subvolumes on "myhost"
volume ssh://myhost/
subvolume var/lib/lxd/storage-pools/default/containers/first_container/*
```

> Also, since, due to the required separate configurations for varies layers of nesting, these volumes end up in separate directories, restoring these nested constructions is made unnecessarily hard. (Although parts of this might be the fault of btrfs way of construction, too.)

Sadly btrfs does not offer any recursive snapshotting or send/receive. On the other hand, things are kept much simpler as in zfs, which allows me to easily write fancy tools like btrbk on top of it!

If I had more time I'd fix #127 (or similar), also allowing full recursion. This requires quite some changes in the framework, and can't be done "on a quiet evening"...

**Comment by lenucksi** [comment]
Good to know about the ```*/*``` usage.
I've tried it with ```config print``` and found out that e.g. 

````
var/lib/lxd/storage-pools/default/containers/
var/lib/lxd/storage-pools/default/containers/champion-arachnid
````

is catched but the saved volumes end up on the same level, thus loosing their hierarchical order. I've added a few volume + subvolume statements plus the required _btrbr_snap directories to somehow preserve the order.

And advantage of LXD is that there appear to be no duplicated volume names anymore (as far as I could observe until now).

All in all this makes the result at least partially acceptable, however, as you correctly stated, btrfs lacks the send/receive features of ZFS. Thus, send/restore and thus backup/restore is made a bit more tedious.

**Comment by digint** [comment]
> [...] but the saved volumes end up on the same level, thus loosing their hierarchical order.

Yes, currently (as long as #127 is not implemented) btrbk needs a `snapshot_dir` assigned to each `subvolume`. So they all end up in the same directory if you use wildcards.
