### ISSUE TITLE
At least one backup task aborted

### ISSUE THREAD

**Issue by huegelc** [digint/btrbk#232]
I have some trouble running btrbk from cron. I have following crontab:

`30 18 * * * root /usr/sbin/btrbk -q -c /etc/btrbk/btrbk-test.conf run`

And I always get this error in syslog:
`At least one backup task aborted`
I can´t figure out what it is as `/usr/sbin/btrbk -q -c /etc/btrbk/btrbk-test.conf run`from the CLI works.

Thx.

**Comment by digint** [comment]
You probably have an empty `PATH` environment variable, see #231

**Comment by huegelc** [comment]
This is the complete file:
```
# Shell variable for cron
SHELL=/bin/bash
# PATH variable for cron
PATH=/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/bin:/usr/bin
# rootserver backup
30 18 * * * root /usr/sbin/btrbk -q -c /etc/btrbk/btrbk-test.conf run
```

**Comment by digint** [comment]
So PATH seems to be ok.

Try running it with `-l debug` instead of `-q`.
Debug log goes to stderr, so if you can't see the it, try:
```
/usr/sbin/btrbk -l debug -c /etc/btrbk/btrbk-test.conf run 2> /tmp/btrbk.debug.log
```

**Comment by huegelc** [comment]
```
btrbk command line client, version 0.26.0  (Wed May 16 16:38:01 2018)
Using configuration: /etc/btrbk/btrbk-test.conf
Initializing volume section: example.com:/mnt/btrfs
### ssh -q -p 2006 -i /root/.ssh/id_rsa root@example.com 'btrfs subvolume show /mnt/btrfs'
Command execution failed (exitcode=255): `ssh -q -p 2006 -i /root/.ssh/id_rsa root@example.com 'btrfs subvolume show /mnt/btrfs'`
Unparsed error:
WARNING: Skipping volume "example.com:/mnt/btrfs": Failed to fetch subvolume detail
Opening syslog
Syslog enabled
Completed within: 0s  (Wed May 16 16:38:01 2018)
Closing syslog
```

**Comment by digint** [comment]
```
Command execution failed (exitcode=255): `ssh -q -p 2006 -i /root/.ssh/id_rsa root@example.com 'btrfs subvolume show /mnt/btrfs'`
```
For some reason the ssh command returns exit status 255. Maybe it's not running as root?
Sadly, btrbk runs `ssh -q` (d265c3414937f0c415c51c7c2eb1d3eaad2210f3, #179) , so if you want to see what's really happening, change:
```
---  my @ssh_options = ('-q');
+++  my @ssh_options;
```
in [btrbk line 2298](/digint/btrbk/blob/v0.26.0/btrbk#L2298)

**Comment by huegelc** [comment]
Directly from the cli:
```
ssh -p 2006 root@example.com 'btrfs subvolume show /mnt/btrfs'
/mnt/btrfs is toplevel subvolume
```

**Comment by huegelc** [comment]
Found the issue: needed to source the pid of the ssh agent
