### ISSUE TITLE
fstab mount with space gives unparseable file warning

### ISSUE THREAD

**Issue by vvolas** [digint/btrbk#234]
Hello, 
fstab mount with space gives unparseable file warning
`
WARNING: Skipping non-parseable file in btrfs mounts of localhost: "/home/virtualbox/VirtualBox\040VMs"`
`UUID=0618dbb1-6ae2-4284-a885-068828ff1341 /home/virtualbox/VirtualBox\040VMs    btrfs   relatime,subvol=@virtualbox 0       2`
\040 is "space".

**Comment by digint** [comment]
This is actually an "informative" message, thanks for reporting.

Fixed in: 391e50b8727cf77503d818f6f83ec0851bf2d0b9

Btrbk will now silently ignore unparseable mount ponts as described in btrbk.conf.5.
