### ISSUE TITLE
Usage of ssh_filter_btrbk.sh

### ISSUE THREAD

**Issue by sudouser2018** [digint/btrbk#246]
Dear community,

i'm trying to set up a backup process which is nearly the same as the example for multiple btrbk instances. But I'm getting errors during the dryrun I can't fix.

```
name@server:~$ sudo btrbk -v -l debug dryrun
btrbk command line client, version 0.26.0  (Fri Aug 10 10:34:44 2018)
Using configuration: /etc/btrbk/btrbk.conf
Initializing volume section: myipaddress:/mnt/btrfspool
### ssh -q -p 222 -i /etc/btrbk/ssh/id_rsa btrbk@myipaddress 'btrfs subvolume show /mnt/btrfspool'
Command execution failed (exitcode=126): `ssh -q -p 222 -i /etc/btrbk/ssh/id_rsa btrbk@myipaddress 'btrfs subvolume show /mnt/btrfspool'`
Unparsed error: sh: 1: /usr/share/btrbk/ssh_filter_btrbk.sh: Permission denied
WARNING: Skipping volume "myipaddress:/mnt/btrfspool": Failed to fetch subvolume detail: sh: 1: /usr/share/btrbk/ssh_filter_btrbk.sh: Permission denied
Completed within: 2s  (Fri Aug 10 10:34:46 2018)
--------------------------------------------------------------------------------
Backup Summary (btrbk command line client, version 0.26.0)

    Date:   Fri Aug 10 10:34:44 2018
    Config: /etc/btrbk/btrbk.conf
    Dryrun: YES

Legend:
    ===  up-to-date subvolume (source snapshot)
    +++  created subvolume (source snapshot)
    ---  deleted subvolume
    ***  received subvolume (non-incremental)
    >>>  received subvolume (incremental)
--------------------------------------------------------------------------------
myipaddress:/mnt/btrfspool/workspace
!!! Volume "myipaddress:/mnt/btrfspool" aborted: Failed to fetch subvolume detail: sh: 1: /usr/share/btrbk/ssh_filter_btrbk.sh: Permission denied

NOTE: Some errors occurred, which may result in missing backups!
Please check warning and error messages above.

NOTE: Dryrun was active, none of the operations above were actually executed!
```

---
The setup is very easy:
Fileserver with a btrfs mount in a btrfs mountpool: /mnt/btrfspool/workspace/
btrfspool is a subvol 5, and workspace a subsubvol 257
the snapshots are stored in a seperate subsubvol /mnt/btrfspool/snaps/

Backupserver with /mnt/btrfspool/backup/ which pulls the data from the fileserver

The ssh-setup is the same as in "Setting up ssh"
`command="/backup/scripts/ssh_filter_btrbk.sh --info -l --send -p /workspace" <pubkey>...`
There is a sudo user btrbk on the fileserver, so he should be able to run all the commands

The btrbk.conf on the backupserver looks like:
```
transaction_log            /var/log/btrbk.log
stream_buffer              512m
incremental                yes
timestamp_format long-iso
# Specify SSH private key for "ssh://" volumes / targets:
ssh_identity               /etc/btrbk/ssh/id_rsa
ssh_user                  btrbk
target_preserve_min     no
target_preserve         0d 10w *m

volume ssh://myipaddress/mnt/btrfspool
  subvolume  workspace
     snapshot_dir             snaps
     snapshot_preserve_min    all
     snapshot_create          no
     target send-receive      /mnt/btrfspool/backup
```

The btrbk.conf on the fileserver looks like:
```
transaction_log            /var/log/btrbk.log
stream_buffer              512m
snapshot_dir               snaps
snapshot_create            always
timestamp_format long-iso
snapshot_preserve_min   2d
snapshot_preserve       30d
volume /mnt/btrfspool/
  subvolume workspace

```
Greetings
sudouser2018

**Comment by sudouser2018** [comment]
I hope you've recovered well. The file existed in several places because I played around with it. The file rights are now assigned correctly. I got other error messages where you had no rights to execute btrfs commands. The problem is here:

### ssh -q -p 222 -i /etc/btrbk/ssh/id_rsa btrbk@myip 'btrfs subvolume show /mnt/btrfspool'
Command execution failed (exitcode=1): `ssh -q -p 222 -i /etc/btrbk/ssh/id_rsa btrbk@myip 'btrfs subvolume show /mnt/btrfspool'`
WARNING: Skipping volume "1myip2:/mnt/btrfspool": Failed to fetch subvolume detail: ssh command rejected (please fix ssh_filter_btrbk.sh)

I had to modify the Filter Script:

ssh_filter_btrbk.sh:31
`allow_exact_cmd()
{
    allow_exact_list="**_${sudo_prefix}_**${allow_exact_list}|$1"
}`


ssh_filter_btrbk-sh:86
    `**_temp_cmd="${sudo_prefix}${SSH_ORIGINAL_COMMAND}"_**
    if [[ **_$temp_cmd_** =~ $btrfs_cmd_match ]] ; then
        return 0
    fi
    exact_cmd_match="^${allow_exact_list}$";
    if [[ **_$temp_cmd_** =~ $exact_cmd_match ]] ; then
        return 0
    fi`

I also disabled these:
`allow_rate_limit=
allow_stream_buffer=
allow_compress=`

Now it works for me.

**Comment by digint** [comment]
If you set `backend btrfs-progs-sudo` in btrfs.conf, your patch should not be necessary:
```
volume ssh://myipaddress/mnt/btrfspool
  subvolume  workspace
     [...]
     target send-receive      /mnt/btrfspool/backup
       backend btrfs-progs-sudo
```

This way btrbk runs btrfs commands prefixed with "sudo -n" (since btrbk-0.25.0).

**Comment by sudouser2018** [comment]
Hello,

I'm so sorry for the long responding time. The problem could be solved with both options mentioned above.

Thank you.
