### ISSUE TITLE
Prune snapshots to match backup retention policy

### ISSUE THREAD

**Issue by HaleTom** [digint/btrbk#248]
Is there a way to prune all snapshots except those required by the backup retention policy?

I'm trying to free some space, but without affecting any long term data retention.

**Comment by HaleTom** [comment]
BTW, thanks for creating and maintaining the premier btrfs backup tool. This is an invaluable tool for me.

**Comment by digint** [comment]
I'm afraid there is no such option. Of course you can set `snapshot_preserve` / `snapshot_preserve_min` equal to `target_preserve` / `target_preserve_min` (either in `btrbk.conf` or using `--override=`).

I'll leave this issue open as "enhancement", maybe I'll find a decent way to add such a feature (not much time to work on btrbk right now...).

**Comment by Micha-Btz** [comment]
I have a question releated to this, I backup on a NAS via raw target gpg encrypted. 
My target_preserve is set to 20d 4w 4m, but I have files from 2017 on the NAS.
An example:
 # btrbk prune --print-schedule

> BACKUP SCHEDULE
> action  host  subvol                                                                    scheme                     reason
> /mnt/backup/_btrbk/homefs.20181229                                        20d 4w 2m (sunday, 00:00)  preserve weekly: 2 weeks ago, 6d after sunday
>/mnt/backup/_btrbk/homefs.20190102                                        20d 4w 2m (sunday, 00:00)  preserve weekly: 1 weeks ago, 3d after sunday
> /mnt/backup/_btrbk/homefs.20190106                                        20d 4w 2m (sunday, 00:00)  preserve monthly: first weekly of month 2019-01 (0 months ago, at sunday)
>/mnt/vuplus/sysiphus/btrbk/homefs.20170830.btrfs.lz4.gpg                  20d 4w 4m (sunday, 00:00)  preserve forced: parent of another raw target
>  /mnt/vuplus/sysiphus/btrbk/homefs.20170903.btrfs.lz4.gpg                  20d 4w 4m (sunday, 00:00)  preserve forced: parent of another raw target
> /mnt/vuplus/sysiphus/btrbk/homefs.20170910.btrfs.lz4.gpg                  20d 4w 4m (sunday, 00:00)  preserve forced: parent of another raw target
> /mnt/vuplus/sysiphus/btrbk/homefs.20170917.btrfs.lz4.gpg                  20d 4w 4m (sunday, 00:00)  preserve forced: parent of another raw target

Seems to be, that auto deletion not work, because the files has depends togehter. Can I solve the deletion with btrbk or should I delete this by hand?

Normally I create incremental weekly backups, but I don't want to restore multiple incremental backups im recovery fall so I create monthly a full backup, so that max 4 incremental backups needed to recovery. Maybe I should rethink about this, can you give some advice what would be the best strategy?
Thanks Micha

**Comment by digint** [comment]
I'm afraid that there is still no way to automate this. So little time to work on the cool stuff :(

> Can I solve the deletion with btrbk or should I delete this by hand?

If I recall correctly, even after triggering a full backup btrbk ignores target_preserve scheme and keeps all backups. So yes, you need to delete the backups by hand.

> ... so I create monthly a full backup, so that max 4 incremental backups needed to recovery.

This seems to be a decent strategy.

**Comment by Massimo-B** [comment]
Today there is `btrbk prune`. Isn't that what HaleTom asked for?

**Comment by HaleTom** [comment]
@Massimo-B Yes, thanks!

From the [man page](https://manned.org/btrbk):

       prune [filter...]
           Prune snapshots and backups: skips snapshot and backup creation
           (steps 1, 2), only deletes snapshots and backups in order to
           satisfy their configured retention policy. Useful for cleaning the
           disk after changing the retention policy. Use in conjunction with
           --preserve-backups, --preserve-snapshots if you want to skip backup
           or snapshot deletion (steps 3, 4).

           Note that deletion is skipped if source or target is not
           accessible, as it is still required in order to determine the
           latest snapshot/backup pair (which is always preserved, regardless
           of the retention policy).
