### ISSUE TITLE
snapshot_preserve_min latest also keeps last hourly

### ISSUE THREAD

**Issue by Gatak** [digint/btrbk#252]
With the following config I assumed that btrbk would keep only one source snapshot. Instead it keeps one current and one hourly snapshot.

I run btrbk every 5 minutes.

```
snapshot_preserve   no
snapshot_preserve_min latest
target_preserve_min no
target_preserve     10h 0d 0w 0m 0y
timestamp_format    long

snapshot_dir        snapshots
snapshot_create     onchange

volume /mnt/zram/
  subvolume volume/mysql
    target send-receive /mnt/systemRoot/mysql
```
```
 /mnt/zram # ll snapshots/
total 4
drwxr-xr-x 1 root  root   76 Oct  1 13:31 ./
drwxr-xr-x 1 root  root   30 Sep 30 15:44 ../
drwxr-xr-x 1 mysql mysql 466 Sep 30 15:50 mysql.20181001T1303/
drwxr-xr-x 1 mysql mysql 466 Sep 30 15:50 mysql.20181001T1331/
```

**Comment by Gatak** [comment]
So it's the same every hour:

```
ll snapshots/
total 4
drwxr-xr-x 1 root  root   76 Oct  1 15:39 ./
drwxr-xr-x 1 root  root   30 Sep 30 15:44 ../
drwxr-xr-x 1 mysql mysql 466 Sep 30 15:50 mysql.20181001T1500/
drwxr-xr-x 1 mysql mysql 466 Sep 30 15:50 mysql.20181001T1539/
```

**Comment by digint** [comment]
This is "functions as designed". Btrbk needs to keep the latest common snapshot/backup pair for incremental send/receive.

See btrbk(1): COMMANDS -> Actions -> run -> Step 4: Delete Snapshots:
"Note that the latest snapshot (the one created in step 1) **as well as the latest snapshot/backup pair** are always preserved, regardless of the retention policy."

**Comment by digint** [comment]
> I want to avoid doubling the data consumption which happen if I keep an hour long snapshot.

Well you DO need to keep the latest common, or incremental will not work: if the first hourly (the one that is also present on the target side) was deleted, the data for incremental send would be missing!

If you don't want this, you must set `incremental no` (which still keeps the latest common snapshot (BUG!) at the time of writing, will fix soon). This way your source disk usage will drop a bit, at the cost of larger copy every hour. Note that btrfs does not deduplicate data on target, meaning that (with your config above) the target will have to hold 10x the size of the source subvolume (which is not the case when using incremental transfers).

**Comment by digint** [comment]
Fixed in master: 3528927ea6e60d358ea254870efb0eb138c3a74a

If you set `incremental no`, you will see expected behavior (hint: `btrbk dryrun --print-schedule`).

**Comment by Gatak** [comment]
Thanks!

So maybe I went on about this the wrong way. Perhaps you can help me do it correctly.

Background:
I have an application that has intence needs on a mysql (mariadb) database. Both writes and reads. Performance on a SSD disk isn't good enough and even if it was, it might ware out quicker.

Solution:
The solution is to run the db on a ram block device (rbd) with Btrfs and transfer the data every few minutes to a SSD backing disk. Running full transfers takes too much time and stalls the application due to i/o wait.

**Contents of btrbk.conf**

```
transaction_syslog  daemon
lockfile        /run/lock/btrbk-mysql.lock

#snapshot_preserve_min  24h
#snapshot_preserve  168h 31d 12w *m *y

snapshot_preserve   no
snapshot_preserve_min latest
target_preserve_min no
target_preserve     10h 0d 0w 0m 0y
timestamp_format    long

snapshot_dir        snapshots
snapshot_create     onchange

volume /mnt/zram/
  subvolume volume/mysql
    target send-receive /mnt/systemRoot/mysql

```

**Snapshot script**
```
#!/bin/bash

while [ 1 ]
do
    echo `date`
    df -h /mnt/zram
    echo Running btrbk snapshots...
    btrbk run -c /etc/btrbk/mysql.conf >>/var/log/mysql-snap.log 2>&1
    echo Waiting 60 seconds...
    sleep 60
done
```
**Output:
Source volume:**
```
# ll /mnt/zram/snapshots/
total 4
drwxr-xr-x 1 root  root   76 Oct  2 18:06 ./
drwxr-xr-x 1 root  root   30 Oct  2 17:45 ../
drwxr-xr-x 1 mysql mysql 526 Oct  2 17:43 mysql.20181002T1801/
drwxr-xr-x 1 mysql mysql 526 Oct  2 17:43 mysql.20181002T1806/
```
**Source volume a minute later:**
```
# ll /mnt/zram/snapshots/
total 4
drwxr-xr-x 1 root  root   76 Oct  2 18:07 ./
drwxr-xr-x 1 root  root   30 Oct  2 17:45 ../
drwxr-xr-x 1 mysql mysql 526 Oct  2 17:43 mysql.20181002T1801/
drwxr-xr-x 1 mysql mysql 528 Oct  2 18:07 mysql.20181002T1807/
```

**Target volume:**
```
# ll /mnt/systemRoot/mysql/
total 16
drwxr-xr-x 1 root  root   76 Oct  2 18:01 ./
drwxr-xr-x 1 root  root   40 Sep  3 09:44 ../
drwxr-xr-x 1 mysql mysql 526 Oct  2 17:43 mysql.20181002T1744/
drwxr-xr-x 1 mysql mysql 526 Oct  2 17:43 mysql.20181002T1801/
```
Now, I think this is where the problem is. The target never seems to get every **_minute_** snapshot that is created, only the hourly snapshots. 

Can it be fixed so that every minute snapshot is transferred and only the last two source snapshots are preserved on the source and 10hours worth of minute snapshots are preserved on the target?

**Comment by Gatak** [comment]
Update:
I think that the problem is solved. I made a mistake on the configuration. I did not realize **target_preserve_min** could have hours. I set it to 10h and now it seems to work as expected.

```
transaction_syslog  daemon
lockfile        /run/lock/btrbk-mysql.lock

snapshot_preserve   no
snapshot_preserve_min latest
target_preserve_min 10h
target_preserve     10h 5d 0w 0m 0y
timestamp_format    long

snapshot_dir        snapshots
snapshot_create     onchange

volume /mnt/zram/
  subvolume volume/mysql
    target send-receive /mnt/systemRoot/mysql
```

**Output:**
```
# ll /mnt/systemRoot/mysql/
total 16
drwxr-xr-x 1 root  root  266 Oct  2 18:31 ./
drwxr-xr-x 1 root  root   40 Sep  3 09:44 ../
drwxr-xr-x 1 mysql mysql 526 Oct  2 17:43 mysql.20181002T1744/
drwxr-xr-x 1 mysql mysql 526 Oct  2 17:43 mysql.20181002T1801/
drwxr-xr-x 1 mysql mysql 532 Oct  2 18:07 mysql.20181002T1808/
drwxr-xr-x 1 mysql mysql 532 Oct  2 18:07 mysql.20181002T1815/
drwxr-xr-x 1 mysql mysql 532 Oct  2 18:07 mysql.20181002T1820/
drwxr-xr-x 1 mysql mysql 538 Oct  2 18:26 mysql.20181002T1826/
drwxr-xr-x 1 mysql mysql 538 Oct  2 18:26 mysql.20181002T1831/
# ll /mnt/zram/snapshots/
total 4
drwxr-xr-x 1 root  root   38 Oct  2 18:31 ./
drwxr-xr-x 1 root  root   30 Oct  2 17:45 ../
drwxr-xr-x 1 mysql mysql 538 Oct  2 18:26 mysql.20181002T1831/
```

**Comment by Gatak** [comment]
It's been a couple of hours now and it seems to work as it should. Thank you. :)

**Comment by digint** [comment]
Guess you got the trick ;-)

Sidenote: performance wise it's a bad idea to run databases on btrfs (or more general: on COW filesystems). See discussions on linux-btrfs mailinglist or other resources. This also applies to ram block devices, probably to a much lower degree.

That sait, I also use mysql on btrfs for small installations (few users, low traffic) where I don't care that much about performance but want the flexibility I have with btrbk. For larger installations, there's more elaborated things like database replication, but this usually comes with more complexity.
