### ISSUE TITLE
Question: Encrypting backups with ecryptfs

### ISSUE THREAD

**Issue by grondinm** [digint/btrbk#26]
I'm looking at encrypting my main btrfs pool using dm-crypt/luks and wonder about backups using btrbk(really in general i suppose) if i setup a ecryptfs folder on my backup harddrive ex: /mnt/usbdrive/.backup mounted at /mnt/usbdrive/backup and create a subvol called @HomeBackup inside this ecryptfs mount would this cause any potential problems to btrbk? In the end i suppose this is more a general "how well does ecryptfs work with btrfs subvols" but i figured this was as good a place as any to ask plus it might help others.

**Comment by digint** [comment]
This is no problem to btrbk (as dmcrypt is a transparent layer on top or btrfs).

btrbk will simply abort (soft fail) when either the source or the target is not mounted.

**Comment by digint** [comment]
Answering your second question:  **"how well does ecryptfs work with btrfs subvols"**

I use luks/dmcrypt on some machines (even btrfs RAID1 on dmcrypt/luks), which do btrbk backups (on both encrypted and unencrypted external disks), and I never had any problems with it.

**Comment by grondinm** [comment]
Thank you for the response and all your work. This confirms what I was hopping for.

**Comment by grondinm** [comment]
So after doing some more research i have come to find out that a BTRFS subvolume cannot be created inside a Ecryptfs encrypted folder. I'm a little disappointed as now i will need to find a different way of encrypting my backups without having to do full disk encryption(altho that maybe my only option)

**Comment by digint** [comment]
You could setup dmcrypt on a file on any filesystem `dd if=/dev/zero of=/path/to/btrfs.img bs=1g count=10`, then mount this as a loop device and create dmcrypt and btrfs there. This is a bit cumbersome though.

I'm currently working on *raw target support* for btrbk, which will send btrfs subvolumes to a file (on any filesystem), with optional gpg encryption. I hope I'll have something working within a week or two.

**Comment by grondinm** [comment]
i thought about doing that but went with full disk encryption since the other route i would have to know and allocate the exact amount of space i would need
