### ISSUE TITLE
Zero snapshots on host

### ISSUE THREAD

**Issue by vvolas** [digint/btrbk#261]
Hello, I have problem doing zero snapshots policy on host

my settings (specific for subvolume) are
                snapshot_preserve_min   1h
                snapshot_preserve       no
                target_preserve         3d 3w 

after few hours I tried executing "prune" and it still doesnt delete last snapshot. I m doing something wrong? Or there is no possibility currently to delete last snapshot?

**Comment by digint** [comment]
This is "functions as designed": If `incremental yes` is configured (the default), the latest snapshot/backup pair is always preserved (regardless of the retention policy), as these are needed for the next incremental backup.

This one probably still needs better documentation:

> btrbk(1) : COMMANDS -> Actions -> prune
>
> Note that deletion is skipped if source or target is not accessible, as it is still required in order to determine the latest snapshot/backup pair (which is always preserved, regardless of the retention policy).

**Comment by vvolas** [comment]
Ok I just understood that I asked really stupid question. I guess without incremental option backups would be space ineffective?

**Comment by digint** [comment]
Yes, without incremental you are duplicating all data for each backup.

Note that btrbk runs "manual commands", based on analysis of source and destination subvolumes. Run `btrbk -l debug` to see the commands issued.
Manually, you would run `btrfs subvolume send -p <parent> <snapshot>` for incremental send.

**Comment by vvolas** [comment]
Thanks for quick answers.
