### ISSUE TITLE
simple snapshot-only setup for "/"

### ISSUE THREAD

**Issue by johnwmail** [digint/btrbk#264]
Hi, would anyone share, how to make snapshot for / and /home, and store the snapshot with same disk /.snaphost/{root,home}/? (I only have one harddisk, no usb, no ssh server)
Thanks.

**Comment by digint** [comment]
Create a simple setup like the one in ["Example: laptop with usb-disk for backups"](/digint/btrbk#example-laptop-with-usb-disk-for-backups). As you only want snapshotting, remove the `target` lines and you are ready to go: `btrbk dryrun`, `btrbk run`.

Note that if "/" is your root subvolume (subvolid=5), read the FAQ entries on this:

 - https://github.com/digint/btrbk/blob/master/doc/FAQ.md#why-is-subvolume--configuration-not-recommended
 - https://github.com/digint/btrbk/blob/master/doc/FAQ.md#how-do-i-convert--subvolid5-into-a-subvolume

**Comment by johnwmail** [comment]
Hi,

> Create a simple setup like the one in ["Example: laptop with usb-disk for backups"](/digint/btrbk#example-laptop-with-usb-disk-for-backups). As you only want snapshotting, remove the `target` lines and you are ready to go: `btrbk dryrun`, `btrbk run`.
I still very confuse of the config/example

> 
> Note that if "/" is your root subvolume (subvolid=5), read the FAQ entries on this:
> 
>     * https://github.com/digint/btrbk/blob/master/doc/FAQ.md#why-is-subvolume--configuration-not-recommended
> 
>     * https://github.com/digint/btrbk/blob/master/doc/FAQ.md#how-do-i-convert--subvolid5-into-a-subvolume

But I find the recommendation  very useful, I changed my root to subvol now,
Thank you anyway.
