### ISSUE TITLE
ssh_filter_btrbk.sh problem: different btrbk versions on client/target

### ISSUE THREAD

**Issue by andreas-h** [digint/btrbk#268]
I'm having trouble using the `ssh_filter_btrbk.sh` script:

- using btrbk v0.27.1 from Debian/Buster (on the client) and v0.24.0 from Debian/Stretch (on the target)
- `.ssh/authorized_keys` has the line

      command="/usr/share/btrbk/scripts/ssh_filter_btrbk.sh -l --target --delete" ssh-ed25519 AAAAmypubkey root@alniyat
- when running `btrbk dryrun -v`, I the the following error:

      ERROR: Command execution failed (exitcode=1): `ssh -q -i /etc/btrbk/ssh/id_ed25519 root@raspi1 'cat /proc/self/mountinfo'`: ERROR: ssh_filter_btrbk.sh: ssh command rejected: disallowed command: cat /proc/self/mountinfo

I'd appreciate any help in resolving this.

**Comment by digint** [comment]
The `ssh_filter_btrbk.sh` script on the target needs to be updated to 0.27.1 (matching btrbk on the client, as this is the one issuing commands).

Note that btrbk is not required on the target if it is only controlled by the client (i.e. no split configs).

**Comment by andreas-h** [comment]
Thanks, that should have been obvious.  I had a strange feeling while writing about the different version numbers :-/  Anyways, thanks so much for the quick help!
