### ISSUE TITLE
SSH agent not used

### ISSUE THREAD

**Issue by plchldr** [digint/btrbk#269]
When running btrbk I get the error:
```
WARNING: No SSH identity provided (option ssh_identity is not set) for: ssh://[domain]/mnt/btr_pool
WARNING: Skipping volume "[domain]:/mnt/btr_pool": Failed to fetch subvolume detail
[...]
Command execution failed (exitcode=255): `ssh -q root@[domain] 'readlink -e /mnt/btr_pool'`
```
Server log:
```
sshd: Connection from [client IP] port [client port] on [server IP] port [server port]
sshd: Connection closed by [client IP] port [client port] [preauth]
sshguard: Attack from "[client IP]" on service 100 with danger 10.
```
Running the failed command directly succeeds though. The reason would have to be that when executed by `btrbk` the `ssh` client can't see the `SSH_AUTH_SOCK` environment variable that would usually make it use an SSH agent to connect to my hardware token.
The strange thing is that this worked some time ago and I can't tell what changed (it could also be the  [packaging](https://github.com/NixOS/nixpkgs/blob/release-18.09/pkgs/tools/backup/btrbk/default.nix), but I can't find a change on the stable branch I'm using).

When it worked in the past there was a minor annoyance by the way: `btrbk` opened SSH connections 4+ times making me press the button on the hardware token each time and as this happens before each snapshot transfer it's easy to miss when multiple snapshots are transferred; Setting up a shared connection once would be nice.

**Comment by digint** [comment]
This should work, environment variables are passed to ssh. If you are using `ssh_filter_btrbk.sh`, make sure to use the newest version, as `readlink` has been added to the set of allowed commands.

> When it worked in the past there was a minor annoyance by the way: btrbk opened SSH connections 4+ times making me press the button on the hardware token each time and as this happens before each snapshot transfer it's easy to miss when multiple snapshots are transferred; Setting up a shared connection once would be nice.

Yes, this can be annoying. SSH has a "ControlMaster" option (see [ssh_config(5)](https://www.mankier.com/5/ssh_config)) which can be enabled on a per-host basis in `/etc/ssh/ssh_config`. This should allow you to create a setup for your remote hosts, something like:

```
# /etc/ssh/ssh_config
Host 192.168.0.42
  ControlMaster yes
  ControlPath '/root/ssh_btrbk_sockets/myhost
```

Then, after running btrbk, make sure to close the socket: `ssh -O exit`

Long time ago I made some experiments supporting this natively in btrbk, but then dropped it for security reasons, as it creates sockets for every remote host which need to be set up / cleared properly.

**Comment by plchldr** [comment]
I was using `sudo btrbk run` which resulted in the described behavior. Removing `sudo` actually made the SSH connection succeed, but obviously btrfs commands fail.
After some searching around it turned out that `sudo -E btrbk run` was the solution. So some security related change to my system might have been the cause of this and not btrbk, as you say. The issue is that it's now back to working without the `-E` ...
Anyway, sorry for the noise and thanks for the help and this great tool!
