### ISSUE TITLE
Allow an incremental backup between unrelated ids

### ISSUE THREAD

**Issue by ian-kelling** [digint/btrbk#273]
This is a feature request.

Use case: I have my production machine, it does backups to a local backup machine and a remote backup machine. The production machine dies, and the local backup becomes the new production machine. Now I want to send an incremental backup from the new production machine to the remote backup, but btrbk doesn't see the ids as being related, even though they contain identical snapshots. I think I can send an incremental backup with btrfs send. I should be able to tell btrbk that this is ok to do.

**Comment by digint** [comment]
@ian-kelling have you tried latest btrbk master? I just pushed a fix yesterday (fixing issue #255), and I think your case should also be covered.

**Comment by ian-kelling** [comment]
@digint I have not. I will give it a shot.

**Comment by ian-kelling** [comment]
Works! Thank you!
