### ISSUE TITLE
btrbk hung at 100% cpu with <=mbuffer-20150412

### ISSUE THREAD

**Issue by ian-kelling** [digint/btrbk#275]
```
# cat btrbk.conf
...
stream_buffer 512m
volume ssh://kw/mnt/root
subvolume o
target send-receive /mnt/root/btrbk


# btrbk -v --progress run
btrbk command line client, version 0.28.0-dev  (Sat Apr 20 09:50:18 2019)
Using configuration: /etc/btrbk.conf
Creating subvolume snapshot for: kw:/mnt/root/o
[snapshot] source: kw:/mnt/root/o
[snapshot] target: kw:/mnt/root/btrbk/o.20190420T095018-0400
Checking for missing backups of subvolume "kw:/mnt/root/o" in "/mnt/root/btrbk/"
Creating subvolume backup (send-receive) for: kw:/mnt/root/btrbk/o.20190418T213529-0400
Creating incremental backup...
Creating backup: /mnt/root/btrbk/o.20190418T213529-0400
[send/receive] target: /mnt/root/btrbk/o.20190418T213529-0400
[send/receive] source: kw:/mnt/root/btrbk/o.20190418T213529-0400
[send/receive] parent: kw:/mnt/root/btrbk/o.20190416T140439-0400
[send/receive] clone-src: kw:/mnt/root/btrbk/o.20190418T100754-0400
10.1MiB 0:00:06 [1.63MiB/s] [1.63MiB/s]

# pstree -ap
  |   |                   `-btrbk,20556 /usr/sbin/btrbk -v --progress run
  |   |                       `-sh,20613 -c...
  |   |                           `-mbuffer,20616 -q -m 512m
  |   |                               `-{mbuffer},20634

strace -p 20634 |& head
strace: Process 20634 attached
write(4, 0x7f78d31dee65, 10240)         = -1 EPIPE (Broken pipe)
write(4, 0x7f78d31dee64, 10240)         = -1 EPIPE (Broken pipe)
write(4, 0x7f78d31dee63, 10240)         = -1 EPIPE (Broken pipe)
write(4, 0x7f78d31dee62, 10240)         = -1 EPIPE (Broken pipe)
write(4, 0x7f78d31dee61, 10240)         = -1 EPIPE (Broken pipe)
write(4, 0x7f78d31dee60, 10240)         = -1 EPIPE (Broken pipe)
write(4, 0x7f78d31dee5f, 10240)         = -1 EPIPE (Broken pipe)
write(4, 0x7f78d31dee5e, 10240)         = -1 EPIPE (Broken pipe)
write(4, 0x7f78d31dee5d, 10240)         = -1 EPIPE (Broken pipe)

# strace -p 20616 |& head
strace: Process 20616 attached

^C
( no output for a few seconds)

# top

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                   
20616 root      20   0  545440 527300   1892 S 100.0  3.2  54:52.19 mbuffer 

```

I did ctrl-c on btrbk, ran btrbk clean, removed the stream_buffer option and everything ran fine. I'm not planning to use stream_buffer anymore as I don't think its as reliable. I'm thinking a warning should be added in the manual.

My mbuffer version is 20150412-3. btrbk is ff23e9605b.

**Comment by digint** [comment]
I traced this down to a **fix in mbuffer-20151002** (ChangeLog says: "fix: potential infinite loop on output error"). So you were very unlucky with your version of mbuffer. I will add a warning about this in the docs, and adapt the [debian package](https://github.com/digint/btrbk-packaging/blob/debian/debian/control#L17) accordingly.

I'm not using `stream_buffer` myself (for exactly this reason, as I don't care about speed I don't want additional "potential breakers" in the pipe), and now I'm not sure if I can still recommend it, as my trust in the reliability of mbuffer has dropped some more after this bug (and having looked at the code)...

I guess I'll change the doc to something like: "This can give a speed improvement (measured up to 20%) on both local or remote operations, but also increases system load *and adds a source of potential errors to your precious backup process*."

Steps to reproduce:
```
dd if=/dev/zero | mbuffer -m 10m | dd of=/dev/null
```
In another shell, kill the process:
```
pkill -f 'dd of'
```

While mbuffer-20150412 shows the behavior described above, mbuffer-20151002 exits correctly with:
```
mbuffer: warning: error during output to <stdout>: Broken pipe
Terminated
```

**Comment by digint** [comment]
50267f1ca93f534d8271298d2f561670b32e59ea: documentation: btrbk.conf.5: add warning on old versions of mbuffer

**Comment by Gatak** [comment]
It is a 4 year old version. There are several new releases of mbuffer since then.

**Comment by DL6AKU** [comment]
> and adds a source of potential errors to your precious backup process.

As @Gatak said and I say it as well. This is in a very old version of mbuffer. I don't believe such a severe measure is needed. Don't Panic.

> now I'm not sure if I can still recommend it, as my trust in the reliability of mbuffer has dropped some more after this bug

Especially don't panic like that. This is a minor bug (except if btrbk does not return an exit code of != 0).
Just don't use ancient software and if you do, you already know there's unfixed bugs and you have to live with that.

**Comment by digint** [comment]
> This is in a very old version of mbuffer [...]

Well, many people stick with old versions (especially on productive servers, for good reasons), and the btrbk problem is that the mbuffer dependencies are on the receiving host, which is not necessarily where you installed btrbk, depending on the config.

> This is a minor bug

No, I would not call this minor. I'm pretty sure this is also triggered on network failures, e.g. if sshd on the receiving side gets killed, leaving a mbuffer process that eats up 100% cpu.

I un-panicked a bit when actually changing the documentation:

 * The recommendation in `btrbk.conf.example` is still there, as I think a buffer really is "generally a good idea": https://github.com/digint/btrbk/blob/master/btrbk.conf.example#L16

 * In the man page, I added a warning on the old versions, along with "if your main concern is a stable backup process, leave this option disabled" (this still sounds a bit harsh, suggestions?): 50267f1ca93f534d8271298d2f561670b32e59ea

**Comment by ian-kelling** [comment]
Btw, the mbuffer version is from ubuntu 16.04 (and trisquel 8 which I use), and is widely in use due to being in those distros. It could be in other distros as well, I haven't checked. Anyways, I think the doc change looks good to me so I'm going to close this.
