### ISSUE TITLE
Possible time zone change bug?

### ISSUE THREAD

**Issue by ian-kelling** [digint/btrbk#277]
```
btrbk-run: btrbk -v --progress run
btrbk command line client, version 0.28.0-dev  (Mon Apr 29 10:51:38 2019)
Using configuration: /etc/btrbk.conf
Creating subvolume snapshot for: tp:/mnt/root/o
[snapshot] source: tp:/mnt/root/o
[snapshot] target: tp:/mnt/root/btrbk/o.20190429T105138-0400
Checking for missing backups of subvolume "tp:/mnt/root/o" in "/mnt/root/btrbk/"
Creating subvolume backup (send-receive) for: tp:/mnt/root/btrbk/o.20190428T180704+0000                                       
Creating incremental backup...                                                                                                
Creating backup: /mnt/root/btrbk/o.20190428T180704+0000                                                                       
[send/receive] target: /mnt/root/btrbk/o.20190428T180704+0000                                                                 
[send/receive] source: tp:/mnt/root/btrbk/o.20190428T180704+0000                                                              
[send/receive] parent: tp:/mnt/root/btrbk/o.20190424T090355-0400                                                              
[send/receive] clone-src: tp:/mnt/root/btrbk/o.20190426T142935+0000                                                           
 275KiB 0:00:01 [ 214KiB/s] [ 214KiB/s]                                                                                       
WARNING: [send/receive] (send=/mnt/root/btrbk/o.20190428T180704+0000, receive=/mnt/root/btrbk) At subvol /mnt/root/btrbk/o.20190428T180704+0000                                                                                                             
WARNING: [send/receive] (send=/mnt/root/btrbk/o.20190428T180704+0000, receive=/mnt/root/btrbk) ERROR: clone: did not find source subvol                                                                                                                     
WARNING: [send/receive] (send=/mnt/root/btrbk/o.20190428T180704+0000, receive=/mnt/root/btrbk) At snapshot o.20190428T180704+0000                                                                                                                           
[send/receive] checking target metadata: /mnt/root/btrbk/o.20190428T180704+0000
ERROR: Failed to send/receive btrfs subvolume: tp:/mnt/root/btrbk/o.20190428T180704+0000 [/mnt/root/btrbk/o.20190424T090355-0400] -> /mnt/root/btrbk
[delete] options: commit-after
[delete] target: /mnt/root/btrbk/o.20190428T180704+0000
WARNING: Deleted partially received (garbled) subvolume: /mnt/root/btrbk/o.20190428T180704+0000
ERROR: Error while resuming backups, aborting
Created 0/2 missing backups
WARNING: Skipping cleanup of snapshots for subvolume "tp:/mnt/root/o", as at least one target aborted earlier
Completed within: 9s  (Mon Apr 29 10:51:47 2019)
--------------------------------------------------------------------------------
Backup Summary (btrbk command line client, version 0.28.0-dev)

    Date:   Mon Apr 29 10:51:38 2019
    Config: /etc/btrbk.conf

Legend:
    ===  up-to-date subvolume (source snapshot)
    +++  created subvolume (source snapshot)
    ---  deleted subvolume
    ***  received subvolume (non-incremental)
    >>>  received subvolume (incremental)
--------------------------------------------------------------------------------
tp:/mnt/root/o
+++ tp:/mnt/root/btrbk/o.20190429T105138-0400
!!! /mnt/root/btrbk/o.20190428T180704+0000
!!! Target "/mnt/root/btrbk" aborted: Failed to send/receive subvolume

NOTE: Some errors occurred, which may result in missing backups!
Please check warning and error messages above.
```

Btrbk was seeming to tell me that
tp:/mnt/root/btrbk/o.20190428T180704+0000 did not exist, so I checked
and it did.

While checking I noticed that on `tp`, there existed a snapshot o.20190428T143214-0400
which ls sorted before o.20190428T180704+0000 even though its a
later snapshot. I saw there were 2 nonessential snapshots that came
from a machine which was +000 time zone, and which was a misconfiguration,
it should have been -04000, so I just deleted those snapshots,
o.20190428T180704+0000, and o.20190426T142935+0000, and than
reran btrbk, and ran btrbk clean, and then reran btrbk, and everything
worked. This was some data I needed so I didn't take time to investigate
further, but my suspicion was that it was related to the time zone.

**Comment by digint** [comment]
> Btrbk was seeming to tell me that
tp:/mnt/root/btrbk/o.20190428T180704+0000 did not exist, so I checked and it did.

btrbk (or more specifically, btrfs-progs `btrfs receive`) did not find a snapshot correlated to the **clone source**, not the source itself:
```
[...] ERROR: clone: did not find source subvol
```
In your case this is 
```
[send/receive] clone-src: tp:/mnt/root/btrbk/o.20190426T142935+0000                                                           
```

"correlated" means that on target `/mnt/root/btrbk`, btrfs-progs could not find any readonly subvolume having received-uuid matching with either uuid or received-uuid of `tp:/mnt/root/btrbk/o.20190426T142935+0000`.

The strange thing here is that btrbk *did* find a correlated subvolume, or it would not have picked it as a clone source (see commit message in c407d41db2e2a246685c792d7b4952e3473584e2 for a description on what snapshots are used as clone sources).

> While checking I noticed that on tp, there existed a snapshot o.20190428T143214-0400
which ls sorted before o.20190428T180704+0000 even though its a
later snapshot.

Sorted where? Do you mean "processed before by btrbk"?

**Comment by ian-kelling** [comment]
I said sorted by the `ls` command, so I think the timezone issue was just a red herring, you can forget about that.

Based on your comment, the failure is because I did a used btrbk to send backups among hosts like this: a->b, b->c, c->a, a->b, and the last a->b failed because the c->a backup didn't exist on b.

My kernel is `4.15.0-46-generic #49~16.04.1+8.0trisquel3` and btrfs-progs is `4.15.1-1build1`.

What do you think about this?

**Comment by digint** [comment]
> Based on your comment, the failure is because I did a used btrbk to send backups among hosts like this: a->b, b->c, c->a, a->b, and the last a->b failed because the c->a backup didn't exist on b.

Actually, this does not matter much. The received-uuid is always inherited (`btrfs receive`), and btrbk identifies them as "[correlated](https://github.com/digint/btrbk/blob/v0.28.0/btrbk#L3034)". With your kernel versions, this is fine (Kernels >=4.1 and <4.4 are buggy here, for some reason I removed this from the docs: 756e1e94493bc1c71d83dc66e54715117c649706). 

What I'm still puzzeled with is why btrbk still found the subvolume `tp:/mnt/root/btrbk/o.20190426T142935+0000` on the target. It must have been present in `btrfs subvolume list`, but for some reason not accessible by `btrfs receive` (which gets a uuid from the `btrfs send` stream, to match with a received-uuid).

There has been some changes in btrbk-0.28.0 regarding matching of best parents, the "clone source" feature is new, but should not cause problems, I'm confident upstream handles the clone-src correctly. Try to always use latest possible btrfs-progs, even if there have not been major issues lately (4.15.1 seems fine to me).

Regarding time-zones ("time is a bitch"): btrbk is agnostic of the time zone specified on remote hosts (source `ssh://tp` in your case): If long-iso is configured, btrbk uses [gmtime](https://github.com/digint/btrbk/blob/v0.28.0/btrbk#L2549) to resolve the timestamp of the filename, which has some implications for the scheduler (see [btrbk.conf(5) RETENTION POLICY (caveats)](https://digint.ch/btrbk/doc/btrbk.conf.5.html#_retention_policy)), but should work fine, the code has not been touched for a long time. Honestly I don't have much feedback on this (and all hosts I'm managing myself all share the same time zone). Keep an eye on the parents and clone-src for send/receive (on linear operations there should be no clone-src needed), and have a look at `btrkb run -n --print-schedule` from time to time.

**Comment by ian-kelling** [comment]
I hit this issue again. Im not exactly sure what is going on, I suspect somehow I got a subvolume with no parent which broke the chain and btrbk doesn't like that. I didn't have time to investigate before just blowing away some subvolumes in order to continue the backups, but if it happens again, I will figure it out.
