### ISSUE TITLE
Failed to fetch subvolume detail using btrbk-0.22.2

### ISSUE THREAD

**Issue by cmaurand** [digint/btrbk#284]
Hello,
Currently working a problem.  I had a working setup.  The target machine had a meltdown and I had to reinstall linux from scratch.  I set it up with the same fstab entries as before.  reset the root access on the target, copied the ssh key over. reset the known host entry.

a dry run shows that we're failing to fetch subvolume detail.  the target is a btrfs subvolume on the target server.
<pre>btrbk command line client, version 0.22.2  (Fri Jun 28 10:16:01 2019)
Using configuration: /etc/btrbk/btrbk.conf
### 'btrfs' 'subvolume' 'show' '/mnt/btrfs_pool'
Command execution successful
found btrfs root: /mnt/btrfs_pool
### 'btrfs' 'subvolume' 'list' '-a' '-c' '-u' '-q' '-R' '/mnt/btrfs_pool'
Command execution successful
Parsed 17 total subvolumes for filesystem at: /mnt/btrfs_pool
Found 17 subvolume children of: /mnt/btrfs_pool
### '/usr/bin/ssh' '-p' '22333' '-i' '/root/.ssh/id_rsa' 'root@home.xyonet.com' 'btrfs' 'subvolume' 'show' '/mnt/Data/Files/backups'
Command execution successful
Real path for subvolume "home.xyonet.com:/mnt/Data/Files/backups" is: Files/backups
WARNING: Skipping target "home.xyonet.com:/mnt/Data/Files/backups": Failed to fetch subvolume detail
Snapshot creation skipped: snapshot_create=ondemand, and no target is present for: /mnt/btrfs_pool/@home
WARNING: Skipping cleanup of snapshots for subvolume "/mnt/btrfs_pool/@home", as at least one target aborted earlier
Completed within: 1s  (Fri Jun 28 10:16:02 2019)
--------------------------------------------------------------------------------
Backup Summary (btrbk command line client, version 0.22.2)

    Date:   Fri Jun 28 10:16:01 2019
    Config: /etc/btrbk/btrbk.conf
    Dryrun: YES

Legend:
    ===  up-to-date subvolume (source snapshot)
    +++  created subvolume (source snapshot)
    ---  deleted subvolume
    ***  received subvolume (non-incremental)
    >>>  received subvolume (incremental)
--------------------------------------------------------------------------------
/mnt/btrfs_pool/@home
!!! Target "home.xyonet.com:/mnt/Data/Files/backups" aborted: Failed to fetch subvolume detail

NOTE: Some errors occurred, which may result in missing backups!
Please check warning and error messages above.

NOTE: Dryrun was active, none of the operations above were actually executed!
</pre>
If I run the command manually:

<pre>root@sirius:/usr/local/bin# ssh -i '/root/.ssh/id_rsa' -p 22333 home.xyonet.com btrfs sub show /mnt/Data/Files/backups/Sirius
Files/backups/Sirius
	Name: 			Sirius
	UUID: 			9f7098f5-a86c-614b-90c2-1ba19f99165d
	Parent UUID: 		-
	Received UUID: 		-
	Creation time: 		2019-06-28 08:25:49 -0400
	Subvolume ID: 		2359
	Generation: 		118710
	Gen at creation: 	118654
	Parent ID: 		2154
	Top level ID: 		2154
	Flags: 			-
	Snapshot(s):
</pre>

I can't see what the problem is.  None of the other listings that I found here cover this error.  It looks like everything should be working.  Thinking I missed something somewhere.

more detail from running btrbk -l trace dryrun

<pre>
... vinfo created: ssh://home.xyonet.com/mnt/Data/Files/backups/Sirius
### '/usr/bin/ssh' '-p' '22333' '-i' '/root/.ssh/id_rsa' 'root@home.xyonet.com' 'btrfs' 'subvolume' 'show' '/mnt/Data/Files/backups/Sirius'
... Executing command: '/usr/bin/ssh' '-p' '22333' '-i' '/root/.ssh/id_rsa' 'root@home.xyonet.com' 'btrfs' 'subvolume' 'show' '/mnt/Data/Files/backups/Sirius' 2>&1
... Command output:
Files/backups/Sirius
	Name: 			Sirius
	UUID: 			9f7098f5-a86c-614b-90c2-1ba19f99165d
	Parent UUID: 		-
	Received UUID: 		-
	Creation time: 		2019-06-28 08:25:49 -0400
	Subvolume ID: 		2359
	Generation: 		118710
	Gen at creation: 	118654
	Parent ID: 		2154
	Top level ID: 		2154
	Flags: 			-
	Snapshot(s):
Command execution successful
Real path for subvolume "home.xyonet.com:/mnt/Data/Files/backups/Sirius" is: Files/backups/Sirius
... config_key: context=target, key=ssh_port
... config_key: found value=22333
... config_key: context=target, key=ssh_user
... config_key: found value=root
... config_key: context=target, key=ssh_identity
... config_key: found value=/root/.ssh/id_rsa
... config_key: context=target, key=ssh_compression
... config_key: found value=<undef>
... config_key: context=target, key=ssh_cipher_spec
... config_key: found value=default
... config_key: context=target, key=btrfs_progs_compat
... config_key: found value=<undef>
... vinfo created: ssh://home.xyonet.com/mnt/Data/Files/backups/Sirius
WARNING: Skipping target "home.xyonet.com:/mnt/Data/Files/backups/Sirius": Failed to fetch subvolume detail
</pre>

**Comment by digint** [comment]
Sorry for the late reply, I kind of missed that one...

Have you tried with latest btrbk version? I *strongly recommend* upgrading to newest btrbk-0.28.3: read the [upgrade guide]: https://github.com/digint/btrbk/blob/master/doc/upgrade_to_v0.23.0.md

Old btrbk versions fail to read subvolume data when using with new btrfs-progs versions (check btrbk ChangeLog).

**Comment by schildbach** [comment]
I'm running into this issue on every ~10th btrbk invocation, version 0.27.1. Annoyingly, that's the latest version available for Ubuntu and Debian.

@digiint Is there an issue or commit description somewhere that explains the root cause? Specifically, I'm interested in if data loss could occur due to this issue.

**Comment by digint** [comment]
There's more recent builds in "experimental": https://packages.debian.org/source/experimental/btrbk

Or simply download latest revision directly from github, there is no dependencies:
```
wget https://raw.githubusercontent.com/digint/btrbk/v0.30.0/btrbk
chmod +x btrbk
sudo ./btrbk
```
Recent versions of btrbk dump the command error to stderr, this would make it easier to debug. Else, run `btrbk -l debug` and pinpoint the failed command (lines starting with `###`) and its error messages.

if you fear data loss, try running a scrub first `btrfs scrub start -B /mnt/btr_pool`, and check the kernel log. Also check the btrfs wiki for more information.

**Comment by schildbach** [comment]
Just for the record, btrbk 0.27.1 prints this line:

```
ERROR: Command execution failed (child died with signal 11): `btrfs subvolume list -a -c -u -q -R /mnt/xxx`
```

and in the syslog I find this:

```
Nov  2 17:00:16 xxx kernel: [959427.949348] btrfs[2159420]: segfault at 7ffd3cd1873a ip 000055af0107b264 sp 00007ffcdd32ee10 error 4 in btrfs[55af01037000+6c000]
Nov  2 17:00:16 xxx kernel: [959427.949384] Code: 44 24 14 00 00 00 00 31 c0 4c 8d bc 24 c0 00 00 00 8b 7c 24 14 3b bc 24 98 00 00 00 0f 83 ed 01 00 00 49 8d 14 07 48 83 c0 20 <8b> 72 18 8b 4a 1c 48 89 44 24 08 48 8b 6a 08 4c 8b 62 10 89 74 24
```

Kernel version is:

```
$ uname -a
Linux nas 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Since btrbk is self-healing it's not a terrible issue. I'll look into manually upgrading, but in general I'd like to stay with packaged releases. If there was a specific fix-commit that could be cherry-picked, that would be useful to get the fix into the current Debian/Ubuntu packages.

**Comment by digint** [comment]
> Nov  2 17:00:16 xxx kernel: [959427.949348] btrfs[2159420]: segfault at 7ffd3cd1873a ip 000055af0107b264 sp 00007ffcdd32ee10 error 4 in btrfs[55af01037000+6c000]

This means that btrfs-progs (the package providing `btrfs`) have a bug, so try updating those first, ask on the mailing list [1] and/or file a bug there. I can't help much in this regard... For the record: what version of btrfs-progs are you running? (`btrfs --version`)

  [1] https://btrfs.wiki.kernel.org/index.php/Btrfs_mailing_list

**Comment by schildbach** [comment]
> For the record: what version of btrfs-progs are you running? (`btrfs --version`)

```
$ btrfs --version
btrfs-progs v5.4.1
```

**Comment by schildbach** [comment]
I just noticed this has been filed in the Ubuntu bug tracker already:

https://bugs.launchpad.net/ubuntu/+source/btrfs-progs/+bug/1902525
