### ISSUE TITLE
Return error code if unrecoverable problem

### ISSUE THREAD

**Issue by kolcon** [digint/btrbk#285]
Hello,

If there is an unrecoverable problem in if($exit_status || scalar(@unrecoverable)),
btrbk should return exit status to let any other scripts know there was a problem.

I will send you pull request for your consideration.

Thnks

Lubos

**Comment by digint** [comment]
fixed in:
 - 836efa472ba6a93416471dac43703901ed35e41a: btrbk: return error code 10 if unrecoverable problem
 - e7787e8a44feef9ba15f887f4066f5eef0dfb81c: btrbk: replace "unrecoverable" hack by FIX_MANUALLY framework

**Comment by digint** [comment]
included in [btrbk-0.29.0](digint/btrbk/releases/tag/v0.28.3)
