### ISSUE TITLE
Bash completion: Looking for input on implementation

### ISSUE THREAD

**Issue by aude** [digint/btrbk#298]
@digint, I'm thinking about contributing a Bash completion to the project. I've got some years of experience, Bash completion is one of my niche interests :nerd_face: 

Before potentially starting, I'd like to clarify the design:

1. Would you prefer to leverage the [Bash completion framework](https://github.com/scop/bash-completion/blob/master/bash_completion) as much as possible[⁰], or to be as independent as possible[¹]?
2. Would you prefer to hardcode the completion[²], or generate it from `btrbk --help`[³]?
2. Is it okay that I start with a basic implementation, an MVP?

[⁰]: https://github.com/scop/bash-completion/blob/master/completions/vipw
[¹]: https://git.zx2c4.com/password-store/tree/src/completion/pass.bash-completion
[²]: https://github.com/scop/bash-completion/blob/master/completions/rsync
[³]: https://github.com/scop/bash-completion/blob/master/completions/filefrag

My answers are:

1. I'd prefer to integrate with Bash completion framework, but I respect staying independent if you want to.
2. I'd prefer to generate from `btrbk --help`, to DRY.
3. I'd prefer an MVP. I think that could be motivating, then I could improve the already merged completion with more advanced functionality incrementally.

What are your answers?

**Comment by digint** [comment]
Thanks, and sorry for the late reply (I'm pretty busy at the moment).

I would appreciate to have bash completion in btrbk. While I dont use bash-completion at all, I know that many people love to have this feature.

1. I'm not sure about best-practises here, but using the bash completion framework sounds reasonable to me.
2. I would go on static (hardcoded) completion for the commands (actions), unless you can reliably extract it from `--help`. For the options, using `btrbk --help` sounds reasonable.
3. agreed.

If I understand it correctly, there will be a single sh file to be added (`btrbk-completion` ?)

**Comment by aude** [comment]
No problem, GitHub can be async.

Thanks for the feedback. Sounds good, I can work with this.

Yes, a single bash completion file, for example `contrib/bash/completion.bash`. It would be installed at `/usr/share/bash-completion/completions/btrbk` or other vendor specific location.

**Comment by aude** [comment]
Closing this issue, it has served it's purpose.

Further work can be done in a pull request.
