### ISSUE TITLE
Question : compression on transfer to remote hosts

### ISSUE THREAD

**Issue by Gatak** [digint/btrbk#303]
Hi,

Is it possible to configure btrbk to use compression in the pipeline when sending to remote hosts? 

For example something like this to use with zstd 4 threads
```
btrfs send foo | mbuffer | zstd -T4 |
```

**Comment by fallenguru** [comment]
Does `stream_compress` in the config file not work?

**Comment by digint** [comment]
This is exactly what `stream_compress` does. See [btrbk.conf.5, Data Stream Options](https://digint.ch/btrbk/doc/btrbk.conf.5.html#_data_stream_options)

**Comment by Massimo-B** [comment]
Is there any reason to additionally set ssh_compression, when a stron stream_compress is already used?

**Comment by digint** [comment]
No. If `stream_compress` is enabled, ssh compression will always be disabled for send/receive operations.

Adapted man page, see: a447c4b939c5582221e7f5880cec8a9fbc5b8ad0

**Comment by fallenguru** [comment]
> Is there any reason to additionally set ssh_compression

In my tests, over a 1 Gb/s link, admittedly with a NAS cobbled together from old parts an the receiving side, ssh_compression took 3-4 times(!) as long as lz4 compression, and no compression at all was a bit faster still. IMHO, ssh_compression doesn't make sense outside of niche applications, having some compression in the pipe still might, depending on your setup -- but you'll have to benchmark it yourself.
