### ISSUE TITLE
option to make warnings to change the exit status

### ISSUE THREAD

**Issue by ian-kelling** [digint/btrbk#306]
This is an enhancement proposal.

When btrbk outputs things like this:

WARNING: Please delete stray subvolume

For me, I'm not expecting any warnings and so I know something went wrong. I would like an option to make this be a nonzero exit status so I don't have to parse logs.

**Comment by digint** [comment]
This is fixed in v0.29.0, see bug #285

btrbk-0.29.0 now correctly returns exit code 10 ("Backup abort: At least one backup task aborted") on these warnings.

Feel free to re-open this issue if I am missing something.
