### ISSUE TITLE
Chroot environment - wrong entries in /proc/self/mountinfo (resolved)

### ISSUE THREAD

**Issue by frasou** [digint/btrbk#315]
**At first, I would like to thank you for this wonderful script, it helps me a lot and saved my day many times.**

While reading readme instructions in _"Setting up SSH"_ section at the end in _"Further considerations"_ paragraph you mentioning that chroot will be another security enhancement. I agree and decided to implement it.

So I've set up the backup server, using ssh, btrbk standard user and btrbk-progs-sudo. I've also set up ssh_filter_btrbk.sh --sudo in authorized_keys.  Everything works flawlessly unless I switch sshd to the chroot environment.

### Problem:
1. Chroot is set to /mnt/chroot.
2. Output of btrfs list subvolumes is for example /mnt/chroot/backup/gaia/root/root-sub.20191226T0155. As the user is locked in the chroot, it sees only /backup/gaia/root/root-sub.20191226T0155. Failure of operation is than inevitable, because btrbk cannot see the whole path and thus cannot find the snapshot.

**_Am I missing something? Maybe some option in config file which would tell btrbk to strip part of a path while locked in chroot?_**

### Installed software and config files on the server: (named labase)
`btrfs --version` 
btrfs-progs v5.4 

`uname -srp`
Linux 5.4.6-1.el7.elrepo.x86_64 x86_64

prefix: /mnt/chroot
[/proc/self/mountinfo](https://github.com/digint/btrbk/files/4014030/mountinfo.txt)
[/proc/self/mounts](https://github.com/digint/btrbk/files/4014031/mounts.txt)
[/tmp/btrbk/.ssh/authorized_keys](https://github.com/digint/btrbk/files/4014102/authorized_keys.txt)
[/etc/sshd/sshd_config](https://github.com/digint/btrbk/files/4014099/sshd_config.txt)
[/etc/sudoers.txt](https://github.com/digint/btrbk/files/4014100/sudoers.txt)

### Installed software and config files on the sender: (named gaia)
btrfs-progs v4.19
Linux 4.19.86-gentoo
btrbk command line client, version 0.29.0

[/etc/btrbk/labase-chroot.conf](https://github.com/digint/btrbk/files/4014619/labase-chroot.conf.txt)

### Output of btrbk
**For the first time:**
`btrbk -c /etc/btrbk/labase-chroot.conf -l debug run`
[btrbk-chroot-debug-run-1st-pass.txt](https://github.com/digint/btrbk/files/4014621/btrbk-chroot-debug-run-1st-pass.txt)

**For the second time:** (same command)
[btrbk-chroot-debug-run-2st-pass.txt](https://github.com/digint/btrbk/files/4014622/btrbk-chroot-debug-run-2st-pass.txt)

**Finally:**
`btrbk -c /etc/btrbk/labase-chroot.conf -l debug clean`
[btrbk-chroot-debug-clean.txt](https://github.com/digint/btrbk/files/4014623/btrbk-chroot-debug-clean.txt)

**Comment by digint** [comment]
Thanks for the detailed report!

I suspect this has something to do with the way btrbk assembles the paths by first resolving the mount point from /proc/self/mounts, and then build the btrfs tree structure on top of this.

What does `btrbk ls --format=rel /` show (from inside / outside of chroot)?

Maybe simply setting symlinks helps as a workaround?

**Comment by frasou** [comment]
Thank you for your answer. 

Both outputs of `btrbk ls --format=rel /` are identical. (regardless chroot or non-chroot).
[btrbk-ls-output.txt](https://github.com/digint/btrbk/files/4017058/btrbk-ls-output.txt)

If I understood your hint about symlinks correctly should I do this:
(where backup dir absolute path is /mnt/chroot/backup)

`cd /mnt/chroot`
`mkdir -p mnt/chroot/`
`ln -sr backup/ mnt/chroot/`
?

**Comment by digint** [comment]
Have you tried this:
```
cd /mnt/chroot
mkdir -p mnt/chroot
ln -s /backup mnt/chroot/backup
```

Your log says (for `btrfs subvolume show`):
```
ERROR: ... cannot find real path for '/backup/gaia/root/root-sub.20191227T0255': No such file or directory
```
This means that this subvolume is not accessible there (realpath() fails in btrfs-progs).
From inside the chroot, you need to provide a valid mount point reflecting `/proc/self/mountinfo`:
```
51 50 0:41 /backup-sub /mnt/chroot/backup rw,relatime shared:30 - btrfs /dev/sda4 rw,space_cache,subvolid=261,subvol=/backup-sub
```

**Comment by frasou** [comment]
The issue is solved!

Symlinks idea was great, but it doesn't work.
Y

**Comment by frasou** [comment]
**The issue is solved!**

Symlinks idea was great and easy, but unfortunately it doesn't work. Why not, is mystery for me.

Your last sentence was important though.

> From inside the chroot, you need to provide a valid mount point **reflecting** **/proc/self/mountinfo:**

_So what I did:_
Deleted symlink and additional directories:
`unlink /mnt/chroot/mnt/chroot/backup`
`rm -rf /mnt/chroot/mnt`

_Altering content in /mnt/chroot/proc/self/ this way:_
`sed 's/\/mnt\/chroot\/backup/\/backup/g' /proc/self/mountinfo > /mnt/chroot/proc/self/mountinfo`
`sed 's/\/mnt\/chroot\/backup/\/backup/g' /proc/self/mounts > /mnt/chroot/proc/self/mounts`

_So finally, there are only two files in proc dir in chroot:_
`ls -lR /mnt/chroot/proc`
[content](https://github.com/digint/btrbk/files/4023823/h.txt)

This was it. Chroot environment is now working without any issues.

**Thank's for your help, Axel!**

**Comment by digint** [comment]
Thanks for reporting!

Makes sense. btrbk needs `/proc/self/mountinfo` as an anchor (prefix) for assembling the paths from the internal btrfs subvolume structure. This makes it simpler / more correct as the symlinks hack.

Would you mind contributing a little FAQ entry with your setup? Seems that you have a nice basic setup!

Btw. have you considered using btrfs-progs-btrbk? Helps restricting access even more, see:
https://github.com/digint/btrfs-progs-btrbk#btrfs-progs-btrbk
(ebuilds [here](https://github.com/digint/btrfs-progs-btrbk#gentoo-linux) just in case you're on gentoo)

**Comment by frasou** [comment]
Hello and sorry for late answer.
I was pretty busy last days.

I would love to contribute, but I do not know how exactly, as I am not a developer and quite new on github. If you do not mind, I will close this topic and write you an PM how you would imaging my contribution?

**Comment by digint** [comment]
It's very simple, just browse to [FAQ.md](https://github.com/digint/btrbk/blob/master/doc/FAQ.md) ant click on "edit". When finished editing, click "propose file change", which will trigger a merge request. After that I can review and merge it.

**Comment by frasou** [comment]
I am happy to do that. Thanks. 
Meanwhile I close this topic, as it is already solved.
