### ISSUE TITLE
Restore after a died harddisk

### ISSUE THREAD

**Issue by citronbleuv** [digint/btrbk#316]
Hi,

What is the best solution to restore a complete btrfs filesystem after a crach ? I explain me.

Imagine, I have 2 hard disk : 
/media/data : Died data disk (contains normaly just the last snapshot)
/media/backup : Backup disk that contains 3 months of backups.

I changed the data disk, recreated btrfs filesystem and I runned the btrfs command send/receive of /media/backup/.backups/data/document-2019-01-01 to /media/backup/document by exemple.

Now, If I run the btrbk backup, Will the files be duplicated with between the new snapshot/backup and the backups subvolume /media/backup/.backups/data/document-* ? I don't know if the link will be lose with the previous backups and if I could lose many disk space with this operation.

**Comment by digint** [comment]
> Now, If I run the btrbk backup, Will the files be duplicated with between the new snapshot/backup and the backups subvolume /media/backup/.backups/data/document-* ?

No, the data will not be duplicated, as long as there are related backups on both sides (which should be true for the initial send/receive of `document-2019-01-01`, as you restored it from the btrbk backups and btrfs preserves the received_uuid in this case).

Hint: If you enable `incremental strict` in your btrbk.conf (or run `btrbk --override=incremental=strict`), you can prevent non-incremental send/receive to happen.

>  I don't know if the link will be lose with the previous backups and if I could lose many disk space with this operation.

Technically, all that matters is the relations between uuid, received_uuid and parent_uuid.
As of btrbk-0.29.0, type `btrbk ls -L /media` to see the uuids (e.g. uuid == received_uuid  <== "same content").

**Comment by citronbleuv** [comment]
Thanks for answere,

Yes but to restore I used this procedure of the doc : 
....
btrfs send /mnt/btr_backup/data.20150101 | btrfs receive /mnt/btr_pool/
btrfs subvolume snapshot /mnt/btr_pool/data.20150101 /mnt/btr_pool/data
btrfs subvolume delete /mnt/btr_pool/data.20150101

But we lose all uuid between the 2 disks.

**Backup disk:**
        Name:                   document.20200102
        UUID:                   27e77c37-203a-4040-862b-83c687193eee
        Parent UUID:            becb0306-6c57-4d47-8168-d6d8520cdea5
        Received UUID:          1f6bdce2-af72-2c40-b9b0-ae28b5245e29

**Send / Receive to new disk:**
        Name:                   document.20200102
        UUID:                   c876664e-625e-a843-a5a0-3ba2cf1af1a1
        Parent UUID:            - **(because not exists on new disk)**
        Received UUID:          1f6bdce2-af72-2c40-b9b0-ae28b5245e29

**Snapshot on new disk (to have write possibility and finaly location) :** 
        Name:                   document
        UUID:                   eb28fec7-e924-624f-a83d-885172034229
        Parent UUID:            c876664e-625e-a843-a5a0-3ba2cf1af1a1
        Received UUID:          - **It's removed**

Have you create a procedure to restore from backup disk to a new disk ?
In my case, I duplicated the data with above solution.

When there are problem, it's too complex to resolve and risky I find.
I think for backup I will use a solution with rsync + snapshots. So no send/receive.
But that will be slower and no top if I move the files.

Or another tool like backuppc/ext4 for backup disk only.

**Comment by digint** [comment]
Everything seems fine:

1. Received UUID: 1f6bdce2-af72-2c40-b9b0-ae28b5245e29
on backup/document.20200102 ==  newdisk/document.20200102

This means that they are correlated / identical (`received_uuid == received_uuid` is the same as `uuid == parent_uuid` as explained above), and btrbk should take this as a send-receive parent

2. document `parent_uuid = c876664e...` ==  `uuid = c876664e...`

This means that the read-write subvolume "document" was snapshotted from  "document.20200102", and btrbk will use this relation when transferring subsequent snapshots of "document"

3. received_uuid on rw-snapshot "document" is removed, as it is not identical to " document.20200102" any more. This is correct as it is read-write.

Theoretically, a btrbk config like this should work now:
```
volume /mnt/btr_pool
subvolume document
target /media/backup/
```
If not, please provide output from `btrbk run -n -l debug`


> btrfs subvolume delete /mnt/btr_pool/data.20150101

Oh I hope you did not delete this one, this is important for keeping subsequent btrbk backups alive (will fix this in the doc asap)

**Comment by citronbleuv** [comment]
> btrfs subvolume delete /mnt/btr_pool/data.20150101

> Oh I hope you did not delete this one, this is important for keeping subsequent btrbk backups alive (will fix this in the doc asap)

Yes my second, I conserved, That work.

**Comment by citronbleuv** [comment]
Sorry I clicked on close

**Comment by citronbleuv** [comment]
I'm doing a complete test. 

I think I found a bug. I created a new subvolume and configured a backup for it with the option incremental strict.

Next I run the first backup, and I have this error (snapshot created but not the backup) :

> WARNING: Backup to /media/storage2/.backups/storage failed: no common parent subvolume found for "/media/storage/.snapshots/test.20200104", and option "incremental" is set to "strict"
ERROR: Error while resuming backups, aborting
WARNING: Skipping cleanup of snapshots for subvolume "/media/storage/test", as at least one target aborted earlier

Maybe do not apply this error if the remote backup dir is empty ?

I do the first backup without the option, and after readd and it's ok now

**Comment by citronbleuv** [comment]
Thanks for your help,

My tests are good now  👍 that work.

You can maybe also indicate in the documentation that we can delete the received subvolume (btrfs subvolume delete /mnt/btr_pool/data.20150101) but **warning** to do only after running a backup.
