### ISSUE TITLE
Question: read-write snapshots

### ISSUE THREAD

**Issue by dusanmsk** [digint/btrbk#317]
I am running out of disk space on backup disk. I am pretty sure this is because there are many backups (readonly snapshots) on backup disk which contains the same files but in differrent folders etc ...

... So I need to run bedup to deduplicate backup disk filesystem, but all target snapshots are readonly, so deduplication will not work (I am using bedup for this).

My question is - is it possible to make them read-write and not to break btrbk incremental backup feature? I know that I can't change readonly flag on existing snapshot because I will corrupt it, but what about:
- rename readonly snapshot to "snapshot-XYZ.ro"
- do a read-write snapshot from that readonly snapshot with the same name like original snapshot
- delete ".ro" snapshot
- repeat it for all snapshots EXCEPT the last one (because it will be used as parent for next incremental backup)

Will that work?

Thx

**Comment by Gatak** [comment]
No sure about that.
Why don't you make a new folder called `rw`
Then do `btrfs sub snap snapshot-XYZ rw/snapshot-XYZ`
This way you do not intefere with the btrbk system.

**Comment by dusanmsk** [comment]
Because all readonly btrbk snapshots will remain on the disk and will not be deduplicated.

**Comment by Gatak** [comment]
If you want to deduplicate ro-snapshots you can use duperemove with the -A flag. But you cant make a btrbk snapshot rw and keep the chain intact.

**Comment by dusanmsk** [comment]
I'd like to say you are me hero, but tested it and its results aren't so shine as I expected. Problem no.1 - it reads all files from all snapshots, so if I have 20 snapshots of 1 TB data, it will read 20 TB from disk for a years... But I tried it on a smaller chunk of data, started on 633 GB used, then copied and btrbk-ed single 4GB file multiple times, after duperemove there is 645 GB used (might be 637 [633+4]).

When I use bedup with read-write snapshots, I get exactly 637 GB and deduplication is much much faster.

What about to configure btrbk to create only single backup - then making rw "historical" backups by rw snapshotting that backup using btrfs tools?

**Comment by digint** [comment]
As far as I know snapshot-aware dedupe is still an unsolved problem in btrfs. I know there has been some work done, but I'm not actively using it.

@dusanmsk Hint: there is a btrbk feature-branch [extents-diff-v2](https://github.com/digint/btrbk/tree/extents-diff-v2) which implements `btrbk extents-diff` command, useful for determining what is eating up the disk space:

```
wget https://raw.githubusercontent.com/digint/btrbk/extents-diff-v2/btrbk
chmod +x btrbk
sudo ./btrbk extents-diff <path>
```

 - still beta, but should work as expected (make sure to understand the output)
- [documentation](https://github.com/digint/btrbk/blob/extents-diff-v2/doc/btrbk.1.asciidoc#informative-commands)
 - #280

**Comment by digint** [comment]
Answering your original question:

> -  rename readonly snapshot to "snapshot-XYZ.ro"
> -   do a read-write snapshot from that readonly snapshot with the same name like original snapshot
> -   delete ".ro" snapshot
> -   repeat it for all snapshots EXCEPT the last one (because it will be used as parent for next incremental backup)
>
> Will that work?

This will still work for btrbk send-receive, as long as you keep the last one on both sides. Note that creating a read-write snapshot removes the received_uuid, and so the link between original / backup is gone.

**Comment by dusanmsk** [comment]
Yes I am aware of that. Thank you, will try.
