### ISSUE TITLE
Can btrbk replace snapper?

### ISSUE THREAD

**Issue by bard** [digint/btrbk#32]
I've been using [snapper](http://snapper.io) to maintain snapshots on my laptop's to and recover accidentally deleted files. I found btrbk while looking for something that would provide the same onto external hardware, but it seems to me that it fits that requirement AND can replace snapper, since it maintains in-volume snapshots anyway. Is that so or am I missing something?

**Comment by digint** [comment]
For the use-case you are describing, I'd say yes. Snapper provides some functionality that btrbk does not (e.g. rollback or comparison, which has to be done by hand in btrbk), while btrbk provides support for managing multiple hosts. I don't use snapper myself, but when looking at its feature list I'd say:
- For backup purposes, use btrbk
- For local subvolume management (like experimenting on filesystem and switch back easily), use snapper

**Comment by bard** [comment]
Thanks. btrbk looks better by the minute, I think I'll handle everything with it since I'm not using the fancy parts of snapper anyway. Just one thing is giving me pause: is it possible to simulate hourly snapshots? I guess running in cron.hourly instead of cron.daily might be enough since btrbk, when `foobar` exists, creates `foobar_1`, `foobar_2` etc. Would that get in the way of the old-snapshot cleanup procedure?

**Comment by digint** [comment]
Exactly, simply run it in cron.hourly, and it will create `foobar.YYYYMMDD_0`, `foobar.YYYYMMDD_1`, ...
Cleanup is independent of this, the preserve rules only look at the `YYYYMMDD` part.

**Comment by bard** [comment]
Great, thanks!

**Comment by Massimo-B** [comment]
I also thought about replacing snapper by btrbk. But as snapper is highly integrated into zypper, YaST down to the boot loader, I kept snapper and have setup btrbk for the home sub only.
**How would I use btrbk to send/receive the snapper snapshots to a remote btrfs?**

This is the current subvolume layout on OpenSuse LEAP 15.0, with a first btrbk snapshot at the end:
```
ID 257 gen 30 top level 5 path @
ID 258 gen 3251 top level 257 path @/var
ID 259 gen 385 top level 257 path @/usr/local
ID 260 gen 3251 top level 257 path @/tmp
ID 261 gen 1836 top level 257 path @/srv
ID 262 gen 3251 top level 257 path @/root
ID 263 gen 196 top level 257 path @/opt
ID 264 gen 3250 top level 257 path @/home
ID 265 gen 3251 top level 257 path @/.snapshots
ID 266 gen 3250 top level 265 path @/.snapshots/1/snapshot
ID 441 gen 1807 top level 265 path @/.snapshots/15/snapshot
ID 443 gen 1812 top level 265 path @/.snapshots/16/snapshot
ID 444 gen 1836 top level 265 path @/.snapshots/18/snapshot
ID 445 gen 1837 top level 265 path @/.snapshots/19/snapshot
ID 448 gen 1979 top level 265 path @/.snapshots/22/snapshot
ID 449 gen 1980 top level 265 path @/.snapshots/23/snapshot
ID 450 gen 2003 top level 265 path @/.snapshots/24/snapshot
ID 451 gen 2004 top level 265 path @/.snapshots/25/snapshot
ID 453 gen 3207 top level 265 path @/.snapshots/26/snapshot
ID 454 gen 3208 top level 265 path @/.snapshots/27/snapshot
ID 455 gen 3250 top level 265 path @/.snapshots/home/home.20180807T111135+0200
```

**Comment by rickysarraf** [comment]
More than replace, I think `btrbk` could also stand as snapper's backup tool. The integration efforts should be very minor, in that they only need to follow snapper's naming convention and secondly use `snapper` for the snapshotting. I think, with `snapper` providing the ability to have user snapshotable volumes, `btrbk` could become a backup tool not requiring `root` privileges in this special case.
