### ISSUE TITLE
audit-proof/append-only backups

### ISSUE THREAD

**Issue by schildbach** [digint/btrbk#322]
Currently if you use the ssh feature to backup to a remote system, as far as I understand there is always the possibility that someone (or some malicious program) can misuse the ssh access for spying on, or altering/deleting the backups stored on the remote system. In times of extortion trojans this is suboptimal.

I think it would be great if btrbk could write into some sort of remote data sink that only allows for appending. On the remote system, there would sit some deamonized btrbk instance that would process the data written into the sink and run the snapshotting/archiving as it does today.

Obviously, for restoring backups then some other channel would need to be used. But that's likely a manual process that can be much better protected.

**Comment by digint** [comment]
You can achieve this by restricting ssh access with [ssh_filter_btrbk.sh](https://digint.ch/btrbk/doc/ssh_filter_btrbk.1.html), allowing only btrbk target operations with the `--target` option.

Another (more robust, more complicated) way is to install [btrfs-progs-btrbk](https://github.com/digint/btrfs-progs-btrbk) and only install btrfs-subvolume-show, btrfs-subvolume-list and btrfs-receive.

**Comment by schildbach** [comment]
Cool, I didn't notice ssh_filter_btrbk.sh. Seems indeed to do what I want, although it feels a bit weird.

Your second suggestion I don't understand. If there is root access, an attacker can install whatever s/he wants.

Anyway, I'm closing this. Thanks for the great tool!
