### ISSUE TITLE
Feature request: mark parents of incremental backups

### ISSUE THREAD

**Issue by Micha-Btz** [digint/btrbk#323]
hi there,

I make backups on an external nas, since it is not btrfs and not encrypted, I do it on ext4 with gpg encryption. To lower the parts I have in case of emergency restored I make monthy complete backups with the --override=incremental=no option. This results in:

> -rw-r--r-- 1 root    root    1,2G Sep  8  2019 mediafs.20190901.btrfs.lz4.gpg
> -rw-r--r-- 1 root    root     225 Sep  8  2019 mediafs.20190901.btrfs.lz4.gpg.info
> -rw-r--r-- 1 root    root    1,5G Sep  8  2019 mediafs.20190902.btrfs.lz4.gpg
> -rw-r--r-- 1 root    root     225 Sep  8  2019 mediafs.20190902.btrfs.lz4.gpg.info
> -rw-r--r-- 1 root    root    1,5G Sep  8  2019 mediafs.20190908.btrfs.lz4.gpg
> -rw-r--r-- 1 root    root     225 Sep  8  2019 mediafs.20190908.btrfs.lz4.gpg.info
> -rw-r--r-- 1 root    root    5,2G Sep 15 12:00 mediafs.20190915.btrfs.lz4.gpg
> -rw-r--r-- 1 root    root     225 Sep 15 12:00 mediafs.20190915.btrfs.lz4.gpg.info
> -rw-r--r-- 1 root    root    7,0G Sep 23 20:03 mediafs.20190923.btrfs.lz4.gpg
> -rw-r--r-- 1 root    root     225 Sep 23 20:03 mediafs.20190923.btrfs.lz4.gpg.info
> -rw-r--r-- 1 root    root     28G Sep 30 20:16 mediafs.20190930.btrfs.lz4.gpg
> -rw-r--r-- 1 root    root     225 Sep 30 20:16 mediafs.20190930.btrfs.lz4.gpg.info
> -rw-r--r-- 1 root    root    101G Okt  2 22:25 mediafs.20191002.btrfs.lz4.gpg
> -rw-r--r-- 1 root    root     167 Okt  2 22:25 mediafs.20191002.btrfs.lz4.gpg.info
> -rw-r--r-- 1 root    root     17G Okt  7 19:06 mediafs.20191007.btrfs.lz4.gpg
> -rw-r--r-- 1 root    root     225 Okt  7 19:06 mediafs.20191007.btrfs.lz4.gpg.info
> -rw-r--r-- 1 root    root    2,6G Okt 16 19:11 mediafs.20191016.btrfs.lz4.gpg
> -rw-r--r-- 1 root    root     225 Okt 16 19:11 mediafs.20191016.btrfs.lz4.gpg.info
> -rw-r--r-- 1 root    root    1,8G Okt 24 17:48 mediafs.20191024.btrfs.lz4.gpg
> -rw-r--r-- 1 root    root     225 Okt 24 17:48 mediafs.20191024.btrfs.lz4.gpg.info
> -rw-r--r-- 1 root    root    1,2G Okt 31 10:05 mediafs.20191031.btrfs.lz4.gpg
> -rw-r--r-- 1 root    root     225 Okt 31 10:05 mediafs.20191031.btrfs.lz4.gpg.info
> -rw-r--r-- 1 root    root    112G Nov  2 12:39 mediafs.20191102.btrfs.lz4.gpg
> -rw-r--r-- 1 root    root     167 Nov  2 12:39 mediafs.20191102.btrfs.lz4.gpg.info
> -rw-r--r-- 1 root    root    1,5G Nov  9 12:41 mediafs.20191109.btrfs.lz4.gpg

since the hdd goes out of space at some time, I remove old backups with

> find /mnt/vuplus/sysiphus/btrbk  -type f -mtime +365 -delete

which work, but is not smart since it leaves some incremental part, where the parent is deleted.
So the question is, can we mark the parts that belong together so that I can my remove logic make smarter? 
I don't really have an idea how, maybe mark all incrementals with the date from the parent or a checksumor something. Since I don't a programer I don't know if it is possbile or maybe to complicated. What do you think?

TIA Micha

**Comment by Gatak** [comment]
That's a good idea. Ive been thinking something similar. Simply appending '_Fn' for full and '_In' for incremental, where 'n' is a sequence number for the group?

**Comment by digint** [comment]
Incremental backups have `RECEIVED_PARENT_UUID=<uuid>` line in the `.info` file, pointing to `RECEIVED_UUID` of the parent. With this you should have everything needed to make a smart logic.

**Comment by Micha-Btz** [comment]
Thanks for the answer, so I can get the info I need.
