### ISSUE TITLE
Why are snapshots in snapshot_dir not cleaned after sending to target

### ISSUE THREAD

**Issue by cmonty14** [digint/btrbk#325]
Hi,
in my understanding `btrbk `creates snapshots of every configured subvolume in _snapshot_dir_.

My question is:
Why is this _snapshot_dir_ not cleaned up after sending the relevant subvolume to _target_?

In my opinion there's a risk of insufficient free space in filesystem when snapshots in _snapshot_dir_ are not cleaned up.
(Snapper uses a function to cleanup snapshots on a relative simple algorithm.)

THX

**Comment by Gatak** [comment]
https://digint.ch/btrbk/doc/btrbk.conf.5.html

Look at the following settings:
```
snapshot_preserve
snapshot_preserve_min
target_preserve
target_preserve_min
```
