### ISSUE TITLE
Feature request - integrate differential backup for raw targets

### ISSUE THREAD

**Issue by Micha-Btz** [digint/btrbk#326]
Hi threre,
I would ask if you can add the possibility to create differential backups for external backups with ssh? 
I do not know how much work it is, it would be a great benefit.

For me, I create weekly incremental backups and monthly full backups and keep by policy 3 complete backups. So the space I need is about 3 times from the original. I make this because in the emergency case, I have maximal to restore 3/4 files.

Example - my home is about 100GB
20200101 - full backup - 100GB
20200107 - incremental 2 GB
20200114 - incremental 2 GB 
20200121 - incremental 2 GB
There are 106Gb for January, 106GB for February and 106GB for March. If we can create differential backups monthly on Feb and March there will be added 6GB per Month and we can delete the incremental backups. So after 3 Month I have used 118GB and not 318GB.

Since I don't a programmer I would assume to keep the first snapshot as part for the differential and incremental backups and I know this would make the logic more complicated, but we probably can save the snapshot in a config file and so be sure it is never be deleted.

What do you think?

Micha

**Comment by Gatak** [comment]
Isn't this already default?
https://digint.ch/btrbk/doc/btrbk.conf.5.html

> **incremental yes|no|strict**
> If set, incremental backups are created. If set to “strict”, non-incremental (initial) backups are never created, and incremental backups are restricted to related parents (by parent-uuid relationship). Defaults to “**yes**”

**Comment by Micha-Btz** [comment]
No, see:
https://searchdatabackup.techtarget.com/tip/Data-backup-types-explained-Full-incremental-differential-and-incremental-forever-backup

**Comment by digint** [comment]
Are you doing "raw" backups? If not, it does not make much sense to make full backups as long as the snapshots needed for incremental backups are still around. From the user perspective, "incremental" backups are no different than full backups, you always see the full filesystem at the point of the backup. But maybe I got your question wrong?

> [...] but we probably can save the snapshot in a config file and so be sure it is never be deleted.

If you want to make sure a snapshot is not deleted by btrbk, you can simply rename it (e.g. add `.keepme` file suffix).

**Comment by Micha-Btz** [comment]
Yes, I mean raw backups. For local snapshots it makes no sence, but for raw targest it would be a great save of space. And ideal where if btrbk can hadle it automatically. If I rename the snapshot I have to add a logic that create a diff between the snapshots and most of the logic btrbk have allready.

This I mean with don't delete the original snapshot and create than the differential raw backups from this.

**Comment by NeuerUser** [comment]
I would like to second this feature. I have a btrfs PC, which I snapshot with btrbk and which I would like to backup the snapshots on a NAS, which, however, does not run on btrfs. So, I can only send as RAW target. Sending a full backup every day is quite a workload, so a possibility to send diffs to a RAW target would be highly aprreciated.

**Comment by digint** [comment]
Note that incremental raw backups are possible, but not recommended. The problem is that it is not possible to make it 100% reliable as long as there are sporadic failures from upstream btrfs send/receive (e.g. #292), which will silently fail with incremental raw backups.

From btrbk.conf(5):
```
For incremental backups ("incremental yes"), please note that:

•   As soon as a single incremental backup file is lost or
    corrupted, all later incremental backups become invalid, as
    there is no common parent for the subsequent incremental images
    anymore. This might be a good compromise for a vacation backup
    plan, but for the long term make sure that a non-incremental
    backup is triggered from time to time.

•   There is currently no support for rotation of incremental
    backups: if incremental is set, a full backup must be triggered
    manually from time to time in order to be able to delete old
    backups.
```
