### ISSUE TITLE
Skip unchanged subvolumes

### ISSUE THREAD

**Issue by jonjonw** [digint/btrbk#328]
Would it be difficult to add an option to skip snapshots/backups of subvolumes that have not changed since the last snapshot?

A quick way is to test if the metadata has changed: ie, if `btrfs send --no-data -p path/to/subvolume path/to/snapshot` returns no data.

**Comment by digint** [comment]
Sorry for the late reply, I kind of missed that one...

What you are looking for is already implemented:

btrbk.conf:
```
snapshot_create  onchange
```

It compares the transid (gen, cgen) on the latest snapshot and the subvolume, and skips snapshot creation if they are identical.
