### ISSUE TITLE
[question] How incremental is it?

### ISSUE THREAD

**Issue by cogabe** [digint/btrbk#330]
Hello, first of all, thank you for your work, it's amazing and I love it. I have a few questions:
`capabilities to create atomic snapshots and transfer them incrementally to your backup locations.`

Let's say, there are three snapshots": June 1st, 2nd, and 3rd. If I remove my snapshot from June 1st, are 2nd and 3rd will still be reliable? Or incomplete?

Is "incremental" here to say it's only gonna send the "difference" between the snapshots, and not the whole subvolume everytime? I just want to clarify.

Thanks.

**Comment by Gatak** [comment]
They will be complete.  That's the cool thing with btrfs snaps.

**Comment by cogabe** [comment]
Thank you a lot. I will close the issue!
