### ISSUE TITLE
Cannot put archive options immediately after the target option

### ISSUE THREAD

**Issue by willemw12** [digint/btrbk#337]
btrbk.conf:

    ...
    target send-receive         ssh://host/backup

    archive_preserve_min        latest

    volume /mnt/btrfs
      subvolume root
    ...

Run:

    # btrbk run
    ERROR: Option "archive_preserve_min" is only allowed in "root" context in "/etc/btrbk/btrbk.conf" line 3

Workaround: move archive options before the target option.

Btrbk 0.29.1.

**Comment by digint** [comment]
`archive_preserve` and `archive_preserve_min` can only be set in global config. Note that `btrbk archive` does not read volume/subvolume/target sections, it only reads global context (as it is intended to work without config).

**Comment by willemw12** [comment]
I see. Thanks.

Global options must always go before the sections, even options that cannot be used inside a section (i.e. options that are not related to sections). You cannot mix them (i.e. place those options between or after sections).

Basically, there is one global section at the top of the file.

Note: the manual refers to "global context" while the program calls it "root context".

**Comment by digint** [comment]
Thanks, fixed context naming in: 52a823bb93848cdbdbeb0512c725e33f0195171a

**Comment by simonwiles** [comment]
Is there a way to have different `archive_preserve` options for different subvolumes, then?  I would like to use `btrbk archive` to sync backups from a cloud storage server to a local drive, but I want different retention policies for different subvolumes.

Specifically, e.g., I keep all dailies of a `@data` subvolume but only monthlies of a `@root` subvolume on the cloud server.  Using `btrbk archive` with no config I will sync and keep all the available backups for both subvolumes locally, but if I use `archive_preserve` it sets a policy that applies to both `@root` and `@data` backups.

The only thing I can think of is to try to run `btrbk archive` once for each subvolume's backups, supplying a different config each time?
