### ISSUE TITLE
is it possible to have a separate retention for non-backed up (to target) snapshots?

### ISSUE THREAD

**Issue by yarikoptic** [digint/btrbk#349]
My target is external removable device which I would plug in once in a while (home network has only usb2 rpi3 ATM, so do not want to torture sending to it).  So ideally no snapshots should be "purged" locally until they are transmitted to the target.  Then I do not care much -- could keep just a few dailies.  But until they are backed up, I want to keep them all.  I felt like a separate retention policy for "non-transmitted" snapshots would be something like what is needed to fulfill my need. Then I would set that "non-transmitted" snapshot retention to match target retention and then set snapshot retention to just a few dailies. 
But may be it is possible to orchestrate somehow with btrbk already?

**Comment by digint** [comment]
If the target is not attached, btrbk keeps all snapshots, as it can not know which snapshots it can safely "purge" unless the backup disk is present.
Unfortunately, in this case you always get a warning, see #335 

So yes, it is possible with a straight-forward config, if you can live with the warnings. If not, what you can always do is make a saparate config and run it with `btrbk -c mysecondconfig`, but that's usually pretty painful.

**Comment by yarikoptic** [comment]
gotcha -- thank you!  I will see how much warning gets into my way ;-)

**Comment by yarikoptic** [comment]
closing since was answered, but given number of open questions, feel welcome to reopen if that is the preferred way
