### ISSUE TITLE
writeable snapshots

### ISSUE THREAD

**Issue by victor-sudakov** [digint/btrbk#355]
Dear Axel,

Can you please consider an option to make writeable snapshots? Now "-r" is hardcoded for "btrfs subvolume snapshot" , but it does not have to be. It could be a per-volume option.

**Comment by digint** [comment]
Well yes, it kind of has to be: writeable snapshots cannot be used for btrfs send/receive operations. This means that if btrbk would create rw snapshots, no backups and archives could be created from those, which would make such an option pretty meaningless in my opinion.

What would be your use case for such an option?

**Comment by victor-sudakov** [comment]
>  if btrbk would create rw snapshots, no backups and archives could be created from those

I see. Fortunately I can always create any number of writeable snapshots from a readonly snapshot, much like in ZFS you clone a dataset from a snapshot.

> What would be your use case for such an option?

I planned to use btrbk the way I use zfsnap: to maintain a number of snapshots of predefined age automatically, without sending them anywhere, just as a local time machine.

**Comment by digint** [comment]
> Fortunately I can always create any number of writeable snapshots from a readonly snapshot

Exactly. If you want to maintain a time-machine, this is the intended way to go. This way you make sure the contents can not be changed, but you are still able to revert to any point in time by creating a writable snapshot.
