### ISSUE TITLE
How to override configuration file to prevent it from sending snapshots to the target locations?

### ISSUE THREAD

**Issue by ceremcem** [digint/btrbk#356]
I have a configuration that 
1. takes appropriate snapshots inside the primary disk 
2. sends snapshots to the backup disk. 

Sometimes I only need to take snapshots without sending them, so I need to override the `target` keys to set to `null`, but I couldn't figure out how to do that. Is it possible? 

Currently I tried: `btrbk run --override=target=no` (I tried `no`, `null`, `none`).

**Comment by MountainX** [comment]
I have a similar question. I am thinking about trying the following. I will make 2 different config files and using the `--config <file>` command line option to choose between them.

**Comment by digint** [comment]
These days you can use:
 - `btrbk snapshot` to only create snapshots, and
 - `btrbk resume` to run backups

while having all configuration in a single file.

Combine these with filter arguments, e.g. `btrbk resume my-usb-disk-1`

(closing issue, feel free to reopen)
