### ISSUE TITLE
Use btrfs send --no-data instead of btrfs sub find-new 

### ISSUE THREAD

**Issue by ceremcem** [digint/btrbk#361]
`btrfs sub find-new` can not detect empty files, empty folders and deletions, where `btrfs send --no-data` can. Consider using https://github.com/sysnux/btrfs-snapshots-diff approach under the hood.

**Comment by digint** [comment]
Thanks for pointing to this, but I don't think I will implement something like this into btrbk as it requires low-level parsing of the btrfs send stream, which I believe should be implemented in btrfs-progs. So the proper solution would be to have such a feature in btrfs-progs (which should be pretty easy to implement), and have btrbk use it.

This also has the drawback that it only works on snapshots, while `btrfs find-new` also works on r/w subvolumes.

**Comment by ceremcem** [comment]
Okay then.
