### ISSUE TITLE
[cache_dir] inconsistency: documentation v. script

### ISSUE THREAD

**Issue by Kr1ss-XD** [digint/btrbk#363]
First of all, thank you, as well as each end every contributor, for sharing this software. `btrbk` has made my backup procedure so convenient !

So, after updating to 0.31.0 and checking the changes, I noticed that in the `btrbk.conf(5)` manual, the new experimental `ccache_dir` setting is [described](https://github.com/digint/btrbk/blob/7dc827bdc3c23fb839540ff1e41f1186fe5ffa19/doc/btrbk.conf.5.asciidoc#L418) to be accepting either `no` or a file.

The `btrbk` script doesn't [implement](https://github.com/digint/btrbk/blob/7dc827bdc3c23fb839540ff1e41f1186fe5ffa19/btrbk#L150) a `no` option though, causing `btrbk` to throw an error when configured with `cache_dir no`.

**Comment by digint** [comment]
fixed in 87623a80f542aee1f0c038ecaad07da325afd878, thanks!

I think accepting `no` does not make much sense here, as this option can only be set globally, and thus can be simply removed.

**Comment by Kr1ss-XD** [comment]
> I think accepting no does not make much sense here, as this option can only be set globally, and thus can be simply removed.

Totally agreed. Thanks !
