### ISSUE TITLE
question: snapshots of each (non-BTRFS) subfolder to local btrfs drive

### ISSUE THREAD

**Issue by zilexa** [digint/btrbk#364]
With a folder structure like this:
/Users/Local/User1
/Users/Local/User2
/Users/Local/User3
/Users/External/User4
/Users/External/User5
/Users/External/User6

Where the UserX folders are nested subvolumes:
Would it be possible to create a config file that creates 3 daily, 2 weekly and 1 monthly snapshot for each UserX folder inside UserX/snapshots, and backups them all to a secondary harddisk? 
For local users, to a third disk as well.

I believe it is doable after reading the documentation, but I am worried about the fact that I use nested subvolumes. If I have to creat @subvolumes in the BTRFS root /, I have to mount each user folder into /Users/Local/ or Users/External. 
I would like to prevent having to manage User folders via /etc/fstab.

**Comment by digint** [comment]
This is doable, but If I recall correctly some kernel versions did not allow to make snapshots outside subvolumes (i.e. if /Users/Local is a subvolume, you could not snapshot /Users/Local/User1 to /Users).

Just try it, btrbk will complain if it does not work.

You can test it manually by running:
```
btrfs sub snap -r  /Users/Local/User1  /Users/user1_snap_ro
# cleanup:
btrfs sub delete /Users/user1_snap_ro
```
Just tried it on kernel 5.10.5, works for me.

**Comment by zilexa** [comment]
Sorry I made a big mistake: my source (with a single folder `/mnt/pool/Users/Local/` containing several `User folders that I want to backup individually, incrementally) is not BTRFS. My destination is BTRFS. 
I have read through https://github.com/digint/btrbk#example-backup-from-non-btrfs-source

If I understand correctly I should:
1) rsync the source data to the destination
2) create snapshots of the destination

You did not create `target` in this example, should there not be a target or `snapshot_dir` be specified? It is unclear to me where the snapshot will be created.

**Comment by zilexa** [comment]
Closing because I have to try it out myself and haven't had time. If I run into issues I'll open a new question.
