### ISSUE TITLE
btrbk does not set non-zero exit status on error

### ISSUE THREAD

**Issue by ceremcem** [digint/btrbk#369]
`btrbk` does not set the `$exit_status` in https://github.com/digint/btrbk/blob/4c0f7317fd822346b4d0e0e2a4c3020e47e95c6e/btrbk#L6178 so it only prints the error state but  issuing `$?` always returns `0` (no error) regardless of error status.

**Comment by digint** [comment]
It is set here for IS_ABORTED:
https://github.com/digint/btrbk/blob/4c0f7317fd822346b4d0e0e2a4c3020e47e95c6e/btrbk#L5297

**Comment by ceremcem** [comment]
Okay, I'm closing this issue till I create a full reproduction.
