### ISSUE TITLE
command line option to update targets only (-r, --resume_only)

### ISSUE THREAD

**Issue by chaosjug** [digint/btrbk#37]
I have a USB drive as one target for my snapshots which isn't connected most of the time.
What I would like to do, is connect it once in a while and sync the snapshot (copy missing and delete old). At the moment this means that I have to connect the drive, make sure it is mounted and wait for the cron-job to happen. Or start the backup manually which will result in two snapshots for the same day.
What I'm missing is a new command or a option for the "run" command to prevent btrbk from making new snapshots, just making sure all targets are up to date.
This would also be useful in case a remote server was down during the backup.

**Comment by digint** [comment]
If I understand it right, you need something like a "-r  --resume-only" command line option, then you would be able to run btrbk by hand as soon as the USB stick is plugged in:

```
# btrbk -r /mnt/btr_pool/src_subvolume
```

while still having a daily cron job running btrbk.

I've been already thinking of implementing this, this should be pretty straight-forward.

For now, you can solve your problem by creating a separate config file for the manual run:

```
btrbk -c /etc/btrbk/btrbk.conf.usbdrive
```

/etc/btrbk/btrbk.conf.usbdrive:
```
volume /mnt/btr_pool
  subvolume src_subvolume
    snapshot_preserve_daily  all
    snapshot_create          no
    resume_missing           yes

    target_preserve_[...]

    target send-receive  /mnt/usb_stick/btrbk/
```

**Comment by digint** [comment]
I was somehow confused when writing the last comment here, as there already exists a "-r" (resume_only) feature, but the documentation was missing in the man-page.

Updated documentation in 7017e14c328d2f1591278a8e8ce93b05f70a6e76

@chaosjug feel free to reopen this issue if this does not solve your problem

**Comment by chaosjug** [comment]
This mostly solve my issue. The only remaining problem is that no snapshots are deleted on the target.
```
NOTE: Preserved all backups (option -p or -r present)
```
So the snapshot accumulate there, until the USB drive is connected during a regular backup.
(I don't have the rights to reopen the issue)

**Comment by digint** [comment]
If a target is not reachable, btrbk refuses to delete the snapshots. The reason for this is that one of the snapshots is needed as parent for incremental backup, and btrbk can not know which one this is if the target is not reachable.

With the -r option (resume-ONLY), no snapshots or backups are deleted.

For now, the only way to accomplish this is having two configs, one for cron and one for manual, e.g.:

/etc/btrbk/btrbk_cron.conf (only create snapshots):
```
volume /mnt/btr_pool
  subvolume src_subvolume
    snapshot_preserve_daily  all
    snapshot_create          no
```

/etc/btrbk/btrbk_manual.conf (perform backups and cleanup):
```
volume /mnt/btr_pool
  subvolume src_subvolume
    snapshot_preserve_[...]
    target_preserve_[...]

    snapshot_create          no
    resume_missing           yes

    target send-receive  /mnt/usb_stick/btrbk/
```

Maybe I'll implement something like "cleanup-only" option one day, but I think it's not as simple as it sounds...
