### ISSUE TITLE
Documentation does not mention required argument "send-receive" 

### ISSUE THREAD

**Issue by zilexa** [digint/btrbk#373]
I ran btrbk successfully a couple of times, following the example of "Backup from non-BTRFS source". 
Now I added a task, following the example "laptop to usb disk" and I get an error. 

issue 1: 
The documentation is not clear at all whether you can have multiple of such configurations in 1 single .conf file (Please update the doc!). 

issue 2: 
The documention does not mention the requirement of `send-receive` for the `target` variable!
As I googled for hours, I found this page that used the `target` variable with another argument, `send-receive`. 
Nowhere in the Doc or Man page is this mentioned!

It does work with `  target send-receive /mnt/disks/backup1/system.backup`
This does not work
 `ERROR: Ambiguous target configuration, in "/home/asterix/docker/HOST/system-backup.conf" line 24` complaining about `  target /mnt/disks/backup1/system.backup` 
```
# btrbk backup configuration - System drive
# ----------------------------------------- 

# Generic settings
# ----------------
# Enable lock file support: Ensures that only one instance of btrbk can be run at a time.
lockfile                   /var/lock/btrbk.lock
# Enable stream buffer (default) 
stream_buffer              256m
# Enable transaction log (default)
transaction_log            /var/log/btrbk.log


# Backup settings
# -----------------
snapshot_preserve_min  3d
snapshot_preserve      14d 8w 2m
 
target_preserve_min    60d
target_preserve        14d 8w 2m
snapshot_dir snapshots 

volume /mnt/btrfs-root
  target /mnt/disks/backup1/system.backup
  subvolume @
  subvolume @home
  subvolume @docker
```

**Comment by digint** [comment]
> issue 1:
The documentation is not clear at all whether you can have multiple of such configurations in 1 single .conf file (Please update the doc!).

Heh well, the docs also don't tell that it's not allowed to have multiple volume sections ;-)
It states:
```
The btrbk configuration file specifies which btrfs subvolumes on the
filesystem are to be processed, what target subvolumes should be used
to create the backups, and where the snapshots should be
generated.
```
In my opinion it is pretty obvious that multiple sections are allowed. I have to admit the documentation text is not super clear here, and it's a bit complicated to explain the SECTIONS well. Any suggestions?

> issue 2:
The documention does not mention the requirement of send-receive for the target variable!
As I googled for hours, I found this page that used the target variable with another argument, send-receive.
Nowhere in the Doc or Man page is this mentioned!

Target type `send-receive` is optional (the default) as of btrbk-0.28.0. On earlier versions this was required. You are probably looking at the documentation on github on the "master" branch, which always reflects the newset version. I maintain a documentation archive on the btrbk home page, what you are looking for is probably:
https://digint.ch/btrbk/doc/archive/btrbk-0.27.2/readme.html

See also #353

**Comment by zilexa** [comment]
Aha! That makes sense, the versions. 

Regarding "SECTIONS", I have been scrolling up and down but can't find any part in the documentation mentioning this?
It does seem to be present in one of the examples, but no explaination. 

In my case, would it be possible to combine the above config with the below? I don't see how?

The config above is to snapshots and backup 3 subvolumes from the os/system drive. 
The config below is to backup a non-BTRFS pool (the disks are BTRFS but with different pooling software (MergerFS) so I have to rsync to the backup disk first):

```
# btrbk backup configuration - Users data
# --------------------------------------- 
# Make sure data @MergerFS pool is rsynced to backup disk first. 

# Generic settings
# ----------------
# Enable lock file support: Ensures that only one instance of btrbk can be run at a time.
lockfile                   /var/lock/btrbk.lock
# Enable stream buffer (default) 
stream_buffer              256m
# Enable transaction log (default)
transaction_log            /home/asterix/docker/HOST/logs/btrbk.log


# Backup settings
# ---------------------------------------------
volume /mnt/disks/backup1
  subvolume users.backup
    snapshot_dir            users.snapshots
    snapshot_name           users

    snapshot_preserve_min   3d
    snapshot_preserve       14d 8w 2m
```
