### ISSUE TITLE
How does btrbk know the snapshot creation date?

### ISSUE THREAD

**Issue by SuperSamus** [digint/btrbk#374]
For its deletion retention policy btrbk needs to know the date in which the snapshots were created. How does it get it? From the subvolume name, from the Unix timestamps (atime, mtime, ctime), or something else entirely?
In case it's the former, what happens if the subvolume is renamed and doesn't have a timestamp anymore in its name?
I think that this should be specified in the docs.

**Comment by digint** [comment]
> For its deletion retention policy btrbk needs to know the date in which the snapshots were created. How does it get it?

From the subvolume file name. ctime is not reliable, as it reflects the ctime from the source subvolume.

> In case it's the former, what happens if the subvolume is renamed and doesn't have a timestamp anymore in its name?

If a file name does not match `<snapshot-name>.<timestamp>[_N]`, it is not touched by btrbk any more, so it will stay there forever until you delete it manually (but will still be used as parent or clone-source for send/receive operation if applicable).

>  I think that this should be specified in the docs.

True. Added documentation in: fe75b336be928c1014b557f5d5802502b64bdc2d

**Comment by SuperSamus** [comment]
Thanks!
Closing.
