### ISSUE TITLE
Ondemand behaviour and nesting of (retention policy) settings

### ISSUE THREAD

**Issue by zilexa** [digint/btrbk#380]
1. when my external disk (see `/media/backup2`, my secondary target in the config below) is not connected:
   - I get lot's of warnings even though `ondemand` has been set. Worse, the snapshots are not cleaned up. 
   - This means, if I don't connect the USB disk for 6 months, they will start to pile up. Is there a way to force all tasks to perform normally, independent whether the secondary target is connected or not?
2. I am not certain the `preserve` settings are applied correctly, because there is no explanation how nesting works, perhaps the documentation assumes the user knows Perl? Could you have please a quick look? I would be highly grateful!

I have different snapshot dir and preserve settings for SYSTEM (`timeline`) vs USERS (`.timeline`). This goes well. Different targets also seems to work: 

```
# Generic settings
# ----------------
# Enable lock file support: Ensures that only one instance of btrbk can be run at a time.
lockfile                            /var/lock/btrbk.lock
# Enable stream buffer (default)
stream_buffer                       256m
# Enable transaction log (default)
transaction_log                     /home/asterix/docker/HOST/logs/btrbk.log

# Default settings & retention policy
# --------------------------------------------------
snapshot_create        ondemand
snapshot_dir           .timeline
snapshot_preserve_min  latest
snapshot_preserve      3d 3w 2m
target_preserve_min    14d
target_preserve        14d 6w 3m

# SYSTEM Backup with custom settings & retention policy
# --------------------------------------------------------------
volume /mnt/btrfs-root
    snapshot_create        ondemand
    snapshot_dir           timeline
    snapshot_preserve_min  latest
    snapshot_preserve      3d 3w 2m
    target_preserve_min    14d
    target_preserve        14d 6w 3m
    target /mnt/disks/backup1/system
    target /media/backup2/system
  subvolume @
  subvolume @home
  subvolume @docker

# USERS Backup with default settings & retention policy
# -----------------------------------------------------------
volume /mnt/disks/cache
  subvolume Users
  target /mnt/disks/backup1/cache
  target /media/backup2/cache

volume /mnt/disks/data1
  subvolume Users
  target /mnt/disks/backup1/data1
  target /media/backup2/data1

volume /mnt/disks/data2
  subvolume Users
  target /mnt/disks/backup1/data2
  target /media/backup2/data2
```

The output: 
```
$ sudo btrbk run -n -c $HOME/docker/HOST/btrbk-backup.conf
WARNING: Skipping target "/media/backup2/system": Failed to fetch subvolume detail
WARNING: ... Command execution failed (exitcode=1)
WARNING: ... sh: readlink -v -e /media/backup2/system
WARNING: ... readlink: /media/backup2/system: No such file or directory
WARNING: Skipping target "/media/backup2/system": Failed to fetch subvolume detail
WARNING: Skipping target "/media/backup2/system": Failed to fetch subvolume detail
WARNING: Skipping target "/media/backup2/cache": Failed to fetch subvolume detail
WARNING: ... Command execution failed (exitcode=1)
WARNING: ... sh: readlink -v -e /media/backup2/cache
WARNING: ... readlink: /media/backup2/cache: No such file or directory
WARNING: Skipping target "/media/backup2/data1": Failed to fetch subvolume detail
WARNING: ... Command execution failed (exitcode=1)
WARNING: ... sh: readlink -v -e /media/backup2/data1
WARNING: ... readlink: /media/backup2/data1: No such file or directory
WARNING: Skipping target "/media/backup2/data2": Failed to fetch subvolume detail
WARNING: ... Command execution failed (exitcode=1)
WARNING: ... sh: readlink -v -e /media/backup2/data2
WARNING: ... readlink: /media/backup2/data2: No such file or directory
WARNING: Skipping cleanup of snapshots for subvolume "/mnt/btrfs-root/@", as at least one target aborted earlier
WARNING: Skipping cleanup of snapshots for subvolume "/mnt/btrfs-root/@home", as at least one target aborted earlier
WARNING: Skipping cleanup of snapshots for subvolume "/mnt/btrfs-root/@docker", as at least one target aborted earlier
WARNING: Skipping cleanup of snapshots for subvolume "/mnt/disks/cache/Users", as at least one target aborted earlier
WARNING: Skipping cleanup of snapshots for subvolume "/mnt/disks/data1/Users", as at least one target aborted earlier
WARNING: Skipping cleanup of snapshots for subvolume "/mnt/disks/data2/Users", as at least one target aborted earlier
--------------------------------------------------------------------------------
Backup Summary (btrbk command line client, version 0.31.2)

    Date:   Fri Mar 26 23:09:53 2021
    Config: /home/asterix/docker/HOST/btrbk-backup.conf
    Dryrun: YES

Legend:
    ===  up-to-date subvolume (source snapshot)
    +++  created subvolume (source snapshot)
    ---  deleted subvolume
    ***  received subvolume (non-incremental)
    >>>  received subvolume (incremental)
--------------------------------------------------------------------------------
/mnt/btrfs-root/@
+++ /mnt/btrfs-root/timeline/@.20210326
*** /mnt/disks/backup1/system/@.20210326
!!! Target "/media/backup2/system" aborted: Failed to fetch subvolume detail

/mnt/btrfs-root/@home
+++ /mnt/btrfs-root/timeline/@home.20210326
*** /mnt/disks/backup1/system/@home.20210326
!!! Target "/media/backup2/system" aborted: Failed to fetch subvolume detail

/mnt/btrfs-root/@docker
+++ /mnt/btrfs-root/timeline/@docker.20210326
*** /mnt/disks/backup1/system/@docker.20210326
!!! Target "/media/backup2/system" aborted: Failed to fetch subvolume detail

/mnt/disks/cache/Users
+++ /mnt/disks/cache/.timeline/Users.20210326
*** /mnt/disks/backup1/cache/Users.20210326
!!! Target "/media/backup2/cache" aborted: Failed to fetch subvolume detail

/mnt/disks/data1/Users
+++ /mnt/disks/data1/.timeline/Users.20210326
*** /mnt/disks/backup1/data1/Users.20210326
!!! Target "/media/backup2/data1" aborted: Failed to fetch subvolume detail

/mnt/disks/data2/Users
+++ /mnt/disks/data2/.timeline/Users.20210326
*** /mnt/disks/backup1/data2/Users.20210326
!!! Target "/media/backup2/data2" aborted: Failed to fetch subvolume detail

NOTE: Some errors occurred, which may result in missing backups!
Please check warning and error messages above.

NOTE: Dryrun was active, none of the operations above were actually executed!
```

The only thing I am not sure of: are the SYSTEM backup specific `preserve` settings applied for all subvolumes of SYSTEM?
And are the default (at the top) `preserve` settings applied for USERS?

**Comment by digint** [comment]
1.
btrbk refuses to clean up the snapshots if a target can not be accessed (this is because it can not know what subvolumes are present on the target, and thus cannot know what snapshots it needs to keep for incremental backup)

If you add the `noauto` option to `backup2`, btrbk will not try to access this target unless you specify it as filter arguments (e.g. `btrbk run /media/backup2/data1`). Note that even with `noauto` set the snapshots will not be deleted unless all targets are accessible.

2.
options are always inherited by their sub-sections (volume inherits from global, subvolume from volume, target from subvolume).
use `btrbk -S` to print the schedule (which will show the preserve settings used), or if you are unsure, use `btrbk config print-all` which will print the complete config as btrbk parsed it.

you are right, the documentation does not say much about setting inheritance:
```
The options specified always apply to the last section encountered,
superseding the values set in upper-level sections. This means that
global options must be set before any sections are defined.
```
will have to think of a less confusing text here...

**Comment by zilexa** [comment]
>thus cannot know what snapshots it needs to keep for incremental backup
Aha now it makes total sense, thanks!

Regarding documentation, for me it was confusing, the readme.md (homepage) is wat I used but later realized you have more documention a few levels deeper. By then I was already wasting lots of precious time trial&err'ing lots of versions of a conf file with dryruns. Suddenly, there were no errors :) 

I will def verify wih config print-all.

I understand options are inherited from parents to childs, but was not sure if "sub-options", like the indented ones under `btrfs-root` in my example, override the options of the higher entities (like my default options) if indented the way I did? 
That is wat I missed in the documentation.
A big, complex example would at least help to get an idea. 

BTW I am promoting btrbk everywhere I can. I also asked the creator of snapraid-btrfs to adjust his tool to use btrbk instead of Snapper: https://github.com/automorphism88/snapraid-btrfs/issues/17

**Comment by digint** [comment]
> I understand options are inherited from parents to childs, but was not sure if "sub-options", like the indented ones under btrfs-root in my example, override the options of the higher entities (like my default options) if indented the way I did?

yes, the override the default ones, and are inherited by   `subvolume @`, `subvolume @home` and `subvolume @docker`. The indentation has no effect, it's completely ignored by btrbk.

**Comment by zilexa** [comment]
Thanks, I haven't had a chance to do a config print-all yet but I am already seeing things more clear now!
The fact that indentation is ignored, that's really interesting as with other languages that I touched it is absolutely crucial to get it right, like Python. 
Now I understand it's actually much more simple! Thanks again. I really hope btrbk will get some more attention because it rocks. Should be the default backup tool for anyone using btrfs!
