### ISSUE TITLE
Why is btrbk failing to "fetch subvolume detail"?

### ISSUE THREAD

**Issue by KodyVB** [digint/btrbk#382]
I've been trying to make the switch from Snapper to btrbk after learning about btrfs send/receive, and wanted to test btrbk out with my home subvolume backed up to the same drive before making the switch, but have encountered a problem. Whenever I try to run it, I get an error such as "Failed to fetch subvolume data", and don't know if I have my configuration wrong, the way I have my subvolumes set up is incompatible, or what.
When I installed Arch, I used [Snapper's recommended layout](https://wiki.archlinux.org/index.php/Snapper#Suggested_filesystem_layout) which resulted in this for the output of `doas btrfs subvolume list / | grep -v "snapshot"`:
```
ID 257 gen 1291 top level 5 path @home
ID 259 gen 1291 top level 5 path @var_log
ID 260 gen 1155 top level 5 path @swap
ID 318 gen 1283 top level 5 path @
```
The config file I used to test it out was:
```
incremental				yes
btrfs_commit_delete			each
snapshot_create				ondemand
transaction_log				/var/log/btrbk.log
lockfile				/var/lock/btrbk.lock
timestamp_format			long
snapshot_preserve_min		        1d
snapshot_preserve			10h 8d 3w 1m 0y

volume /
	subvolume				@home
	snapshot_dir				_btrbk_snap
```
And the error message I got was:
```
WARNING: Skipping subvolume "/@home": Failed to fetch subvolume detail
WARNING: ... Command execution failed (exitcode=1)
WARNING: ... sh: readlink -v -e //@home
WARNING: ... readlink: //@home: No such file or directory
--------------------------------------------------------------------------------
Backup Summary (btrbk command line client, version 0.31.2)

    Date:   Tue Apr 13 11:07:44 2021
    Config: /etc/btrbk/btrbk.conf
    Dryrun: YES

Legend:
    ===  up-to-date subvolume (source snapshot)
    +++  created subvolume (source snapshot)
    ---  deleted subvolume
    ***  received subvolume (non-incremental)
    >>>  received subvolume (incremental)
--------------------------------------------------------------------------------
/@home
!!! Aborted: Failed to fetch subvolume detail

NOTE: Some errors occurred, which may result in missing backups!
Please check warning and error messages above.
```
If someone could help me figure out what I'm doing wrong, I'd appreciate it.

**Comment by digint** [comment]
@KodyVB You don't have the btrfs root subvolume mounted (the one containing `@` and `@home` subvolumes). I added some more documentation regarding this in e6cec73c8f443d7ce445170569c97ef10c8f7e91 and fb792f67a3bcbac25c8c2d275bdd192b3800413e.

Hope that helps.

Also note that `btrfs subvolume list` shows you the internal representation of your btrfs filesystem, which is not always the same as the mounted structure. Hint: try `lsbtr -l /`

**Comment by digint** [comment]
@assasukasse You can't use a device as `volume` declaration. You first need to mount it somewhere (/mnt/btr_pool in examples), and use the mount point as `volume`.

**Comment by assasukasse** [comment]
Thanks for the clarification but I am still struggling.
I have now mounted the btrfs root of the root partition mounted on /root-snapshot and the btrfs root of the home partition mounted in /home-snapshot.
I can see my two subvolumes @ and @root-snapshot inside /root-snapshot
and the two @home and @home-snapshot inside /home-snapshot

I have also edited the .conf file accordingly and I am trying to backup inside @root-snapshot and @home-snapshot

```
timestamp_format	long
snapshot_preserve_min	5d
snapshot_preserve	30d

volume /root-snapshot
    snapshot_dir	@root-snapshot
    subvolume		@
    

volume /home-snapshot
    snapshot_dir	@home-snapshot
    subvolume		@home
```

Unfortunately I still get the same error:
```
btrbk -n run
WARNING: Skipping volume "/home-snapshot": Failed to fetch subvolume detail
--------------------------------------------------------------------------------
Backup Summary (btrbk command line client, version 0.27.1)

    Date:   Wed Apr 21 10:46:52 2021
    Config: /etc/btrbk/btrbk.conf
    Dryrun: YES

Legend:
    ===  up-to-date subvolume (source snapshot)
    +++  created subvolume (source snapshot)
    ---  deleted subvolume
    ***  received subvolume (non-incremental)
    >>>  received subvolume (incremental)
--------------------------------------------------------------------------------
/root-snapshot/@
+++ /root-snapshot/@root-snapshot/@.20210421T1046

/home-snapshot/@home
!!! Volume "/home-snapshot" aborted: Failed to fetch subvolume detail

NOTE: Some errors occurred, which may result in missing backups!
Please check warning and error messages above.

NOTE: Dryrun was active, none of the operations above were actually executed!
```

I guess either backing up into another subvolume (@root-snapshot and @home-snapshot) is not allowed or I have not configured things correctly.

**Comment by assasukasse** [comment]
Nevermind, found the issue.
It was a typo in my fstab
