### ISSUE TITLE
Why a patchset for btrfs-progs-btrbk rather than individual scripts?

### ISSUE THREAD

**Issue by DiagonalArg** [digint/btrbk#389]
I am confused why we patch btrfs-progs to create individual binaries, btrfs-subvolume-show, btrfs-subvolume-list, etc. I see that the point of these binaries is to allow privilege separation using capabilities(7) so btrfs itself doesn't need to be given root privileges when btrbk is run as a cron script, only a few subcommands.  Why not just a series of scripts for each of these commands?  After all, btrbk itself is a pearl script.

I'm new at btrbk so please forgive me if this is an untutored question.

**Comment by digint** [comment]
> Why not just a series of scripts for each of these commands?

It's about security: enabling setcap on scripts is a bad idea (you really don't want to setcap your shell interpreter, I think it's not even possible on most systems), and you would need to set the "Inheritable" capabilities(7) bit.

I know it's a bit of a hassle building these things yourself, and distro packages only exists for gentoo for now:

https://github.com/digint/btrfs-progs-btrbk#gentoo-linux


I'd love to see my patches upstream, did not get much feedback
yet on this:

https://lore.kernel.org/linux-btrfs/?q=%22btrfs-progs%3A+build+distinct+binaries+for+specific+btrfs+subcommands%22

**Comment by DiagonalArg** [comment]
I read the thread and it helped.  Thanks.  Closing this.
