### ISSUE TITLE
Ability to set ssh port in btrbk config.

### ISSUE THREAD

**Issue by TH3L0N3WOLF** [digint/btrbk#39]
Right now I'm setting identity files via the config and port numbers via ssh_config. It would be nice to have the ability to specify ssh's port number via btrbk's config for servers that use a non-standard port.

**Comment by digint** [comment]
I think a "ssh_port" config option would do the trick. Will be implemented soon.

**Comment by digint** [comment]
Implemented in d09d81fbeb14bfffc146bc1fe5029017c7f9a4b4

@TH3L0N3WOLF : please confirm if it works for you as expected.

**Comment by TH3L0N3WOLF** [comment]
Currently away from my computer. I'll give it a shot tonight.

**Comment by TH3L0N3WOLF** [comment]
It works as expected, thanks.
I'm a little bit concerned on how to do selective runs (ex, btrbk run [hostname]) when multiple computers share a hostname but use different ports to communicate. However, I can work around this using ssh_config hostnames and it isn't something that worries me too much.

**Comment by digint** [comment]
> I'm a little bit concerned on how to do selective runs (ex, btrbk run [hostname]) when multiple computers share a hostname but use different ports to communicate. However, I can work around this using ssh_config hostnames and it isn't something that worries me too much.

Another approach would be to announce the hostnames system-wide by adding them to `/etc/hosts`. Or of course record them by real DNS if you have access to a DNS server.
