### ISSUE TITLE
Freenode - apparently some sort of hostile coporate takeover (?)

### ISSUE THREAD

**Issue by DiagonalArg** [digint/btrbk#390]
I know know anything about internal Freenode politics, but this seems serious.  [All ops have resigned](https://fuchsnet.ch/freenode-resign-letter.txt).  It's been taken over by ~~I don't know who~~ Andrew Lee, owner of VPN provider, Private Internet Access.  The previous staff retain the [@FreenodeStaff Twitter](https://twitter.com/freenodestaff) feed.

> In the past few weeks, this has changed[2], and the existance of a legal threat to freenode has become apparent. We cannot know the substance of this legal threat as it contains some kind of gag order preventing its broader discussion within staff.

I'm posting this because I was actually waiting for a response back from Alex/ @digint  on #btrbk when the news broke.

**Comment by DiagonalArg** [comment]
It appears they've moved to libera.chat.  On registering a channel:

https://libera.chat/chanreg

**Comment by DiagonalArg** [comment]
[This FAQ](https://gist.github.com/joepie91/df80d8d36cd9d1bde46ba018af497409) is written by someone unconnected to the staff, but appears useful:

> Since the relations of server sponsors are with the staff team, not with Andrew Lee, it is very likely that the entire network infrastructure will come along with wherever the staff decides to go.

**Comment by digint** [comment]
I created #btrbk channel on irc.libera.chat, and will observe the situation with freenode.
 I guess ultimatively we will switch to libera.chat.

Libera.chat promises independence, FOSS as well as

**Comment by digint** [comment]
Added announcement about the move to libera.chat in #391. Also added a "302 Moved Temporarily: irc.libera.chat #btrbk" topic in irc.freenode.net ;-)

closing this ticket, please comment on #391
