### ISSUE TITLE
Create raw backups on non-btrfs targets

### ISSUE THREAD

**Issue by digint** [digint/btrbk#40]
There is a new branch adding a feature to create raw backups on non-btrfs targets (["target_raw" branch](https://github.com/digint/btrbk/tree/target_raw)). This is very useful if you want to make backups to some cloud storage or your backup file server does not support btrfs. This will probably be merged (as an experimental feature) into the next release.

The idea is to do a `btrfs send` directly to a file, which can then be restored by `cat <file> | btrfs receive`.

Features so far:
- Create raw backup images on non-btrfs target
- Compression support (gzip, xz, bzip2)
- Encryption support (gpg)

Bugs:
- Target preserve mechanism is disabled, as we cannot simply delete incremental files here. This must be done by hand
- No rotation of incremental backups: in order to be able to delete old backups, a full backup must be triggered from time to time. I have no simple solution for this, maybe something like an "incremental monthly" config would do the trick.
- Creates buggy (zero-sized) output files if gpg fails

btrbk.conf:
```
raw_target_compress  xz
raw_target_encrypt   gpg
gpg_keyring          /etc/btrbk/gpg/pubring.gpg
gpg_recipient        btrbk@mydomain.com

volume /mnt/btr_pool
  subvolume home
    target raw ssh://myserver.mydomain.com/non-btrfs-directory
```

This will create encrypted/compressed raw files on myserver.mydomain.com:
- `/non-btrfs-directory/home.20150101.<received_uuid>.<parent_uuid>.btrfs.xz.gpg`

**Comment by digint** [comment]
Implemented (all except rotation of incremental backups) in: e177ae1c87e3074ad75b097f7e6034ed2cce7e89

Seems to work fine, see updated btrbk.conf(5) man-page for details.

**Comment by digint** [comment]
implemented (mostly) in btrbk-0.21.0

**Comment by Micha-Btz** [comment]
Hi there,

thanks for the great script. I have tried yesterday to set it up. Backup Target is my linux receiver
http://linux-tv.com/receiver/vu-uno-review/ over ssh.

> > [btrfs]   target: vuplus:/media/hdd/sysiphus/btrbk
> ### 'btrfs' 'send' '-v' '/mnt/homealt/btrbk_snapshots/btrfs_vuuno.20160411' | 'xz' | 'gpg' '--batch' '--no-tty' '--trust-model' 'always' '--no-default-keyring' '--keyring' '/etc/btrbk/pubring.gpg' '--default-recipient' 'mail@gmx.de' '--encrypt' | '/usr/bin/ssh' '-C' '-i' '/root/.ssh/id_rsa' 'root@vuplus' 'dd' 'status=none' 'of=/media/hdd/sysiphus/btrbk/btrfs_vuuno.20160411--06cf54d6-354b-1f48-bbc1-994b27a3bea3.btrfs.xz.gpg'
> At subvol /mnt/homealt/btrbk_snapshots/btrfs_vuuno.20160411
> BusyBox v1.23.2 (2016-01-19 01:28:06 CET) multi-call binary.
> 
> Usage: dd [if=FILE] [of=FILE] [ibs=N] [obs=N] [bs=N] [count=N] [skip=N]
> 	[seek=N] [conv=notrunc|noerror|sync|fsync]
> 
> Copy a file with converting and formatting
> 
> 	if=FILE		Read from FILE instead of stdin
> 	of=FILE		Write to FILE instead of stdout
> 	bs=N		Read and write N bytes at a time
> 	ibs=N		Read N bytes at a time
> 	obs=N		Write N bytes at a time
> 	count=N		Copy only N input blocks
> 	skip=N		Skip N input blocks
> 	seek=N		Skip N output blocks
> 	conv=notrunc	Don't truncate output file
> 	conv=noerror	Continue after read errors
> 	conv=sync	Pad blocks with zeros
> 	conv=fsync	Physically write data out before finishing
> 	conv=swab	Swap every pair of bytes
> 
> N may be suffixed by c (1), w (2), b (512), kD (1000), k (1024), MD, M, GD, G
> 
> gpg: [stdout]: write error: Datenübergabe unterbrochen (broken pipe)
> gpg: DBG: deflate: iobuf_write failed
> gpg: build_packet failed: Dateischreibfehler
> gpg: [stdout]: write error: Datenübergabe unterbrochen (broken pipe)
> gpg: DBG: deflate: iobuf_write failed
> gpg: [stdout]: write error: Datenübergabe unterbrochen (broken pipe)
> gpg: iobuf_flush failed on close: Dateischreibfehler
> gpg: [stdin]: encryption failed: Dateischreibfehler
> Command execution failed (exitcode=1): "'btrfs' 'send' '-v' '/mnt/homealt/btrbk_snapshots/btrfs_vuuno.20160411' | 'xz' | 'gpg' '--batch' '--no-tty' '--trust-model' 'always' '--no-default-keyring' '--keyring' '/etc/btrbk/pubring.gpg' '--default-recipient' 'mail@gmx.de' '--encrypt' | '/usr/bin/ssh' '-C' '-i' '/root/.ssh/id_rsa' 'root@vuplus' 'dd' 'status=none' 'of=/media/hdd/sysiphus/btrbk/btrfs_vuuno.20160411--06cf54d6-354b-1f48-bbc1-994b27a3bea3.btrfs.xz.gpg'"
> ERROR: Failed to send btrfs subvolume to raw file: /mnt/homealt/btrbk_snapshots/btrfs_vuuno.20160411  -> vuplus:/media/hdd/sysiphus/btrbk/btrfs_vuuno.20160411--06cf54d6-354b-1f48-bbc1-994b27a3bea3.btrfs.xz.gpg
> ERROR: Error while resuming backups, aborting
> Resumed 0/3 missing backups
> WARNING: Skipping cleanup of snapshots for subvolume "/mnt/homealt/btrfs_vuuno", as at least one target aborted earlier
> Completed within: 2s  (Mon Apr 11 20:57:13 2016)
> Closing transaction log

The problem I think is that the busybox dd command the parameter "status=none" don't understand.
As far as i see this is only to suppress everything but error messages. So can i safely remove this parameter?

**Comment by Micha-Btz** [comment]
All i need is to remove this parameter in this line
https://github.com/digint/btrbk/blob/master/btrbk#L1042
correct?

**Comment by digint** [comment]
Yes, correct.

+1 for making backups to a tv-receiver!

Good to know that busybox does not understand this, if possible I'll make some adaptions that also work with busybox.

**Comment by Micha-Btz** [comment]
don't  know if it is for all receivers. i use the vti image. would be great, if you can modify it.
thanks
