### ISSUE TITLE
Snapshots not pruning if snapshot_preserve_min omitted

### ISSUE THREAD

**Issue by tinglis1** [digint/btrbk#402]
I found some behavior that doesn't seem to align with the docs or how I understand btrbk to operate.

I run btrbk on unraid 6.9.2 with Perl 5.32.0.
I noticed that my snapshots weren't always pruning for some of my btrbk instances.
After getting tired of manually pruning I went looking and found that the instances that omitted snapshot_preserve_min no were not pruning. I tried using snapshot_preserve_min no but got validation errors, I didn't bother investigating and just tried 1d and they worked.
Now my snapshots are pruning. 

Not sure if this is a bug or not. If it is expected behavior or just my instance then no need to take this further. I have my work around and am happy.

**Comment by tinglis1** [comment]
Here is a sample of one of the btrbk conf that I fixed to work. The only change was the snapshot_preserve_min line.


`timestamp_formatlong

snapshot_preserve_min  1d
snapshot_preserve14d 10w *m

volume /mnt/disk3
snapshot_dir snapshots/onedrive
subvolume rclone/onedrive`

**Comment by tinglis1** [comment]
Here is an example of a btrbk conf that I needed to update. 


```
timestamp_formatlong

snapshot_preserve_min  1d
snapshot_preserve14d 10w *m

volume /mnt/disk3
snapshot_dir snapshots/onedrive
subvolume rclone/onedrive
```

**Comment by digint** [comment]
Looks like this is "functions as designed".

> I tried using snapshot_preserve_min no but got validation errors, I didn't bother investigating and just tried 1d and they worked.

You should have investigate: a quick look into the man page tells shows that the default for `snapshot_preserve_min` is "all". If you want no snapshots to be preserved, set it to "latest".

I'm thinking of printing a warning like "snapshot_preserve_min is not configured, keeping all snapshots forever". This would probably have helped?

**Comment by tinglis1** [comment]
I think there should be a warning validation if the snapshot_preserve is configured but not snapshot_preserve_min.

I expected that as I had set a preserve retention policy but not the preserve_min the behavior to be latest. Others may be expecting the same.

I will close my issue and thank you for clarifying this.
