### ISSUE TITLE
Simple configurations without "volume" section, allowing absolute paths

### ISSUE THREAD

**Issue by digint** [digint/btrbk#407]
Allow setups without "volume" sections (for simple setups, if no grouping by "volume" is desired). Implement by allowing absolute paths for "snapshot_dir" and "subvolume" sections, which will implicitely also allow to snapshot/backup the root filesystem `/` without the need of mounting subvolid=5.

Allow configurations like this:
```
snapshot_dir /btrbk_snapshots
subvolume    /
subvolume    /home
```

**Comment by digint** [comment]
Implemented in the [optional-volume-section](https://github.com/digint/btrbk/tree/optional-volume-section) branch, and will most probably go into btrbk-0.32.0.

There is still some documentation missing, but first tests shows that it works as expected.

Try it out, all comments are welcome!

```
wget https://raw.githubusercontent.com/digint/btrbk/optional-volume-section/btrbk
chmod +x btrbk

cat > /tmp/btrbktest.conf << EOL
snapshot_dir /
subvolume    /
subvolume    /home
EOL

sudo ./btrbk run -c /tmp/btrbktest.conf -n
```

**Comment by digint** [comment]
Merged to master, and added more documentation (hopefully did not miss anything).

**Comment by MountainX** [comment]
Is this change in version 0.31.3? If I install from https://aur.archlinux.org/packages/btrbk/, will I get this feature, or do I need to clone this repo and build it? Sorry if this is a dumb question. 

Thanks for implementing this feature. I look forward to trying it.  My use case is not the simple case you highlight here, but one with multiple volumes. I'm hoping to use it in that case to avoid "toplevel subvolume mount" as we discussed in issue #408 

BTW, I don't see the documentation change reflected on https://digint.ch/btrbk/index.html yet.

**Comment by digint** [comment]
closing this issue, "optional-volume-section" branch has made it into btrbk-0.32.0.

**Comment by ledlamp** [comment]
What about absolute subvolume path on remote ssh host???????
