### ISSUE TITLE
The same mount point repeatedly mounted in nested manner after using btrbk along with NFS

### ISSUE THREAD

**Issue by MountainX** [digint/btrbk#408]
I recently switched to btrbk and I really like it. Thank you so much for the great tool. However, I am running into one issue. I suspect it is simple user error.

[Background](https://digint.ch/btrbk/doc/faq.html) - from your FAQ

> Btrbk is designed to operate on the subvolumes within a root subvolume. The author recommend booting linux from a btrfs subvolume, and using the btrfs root only as a container for subvolumes (i.e. NOT booting from "subvolid=5").

That's exactly what I'm doing.

The key point for this conversation seems related to the fact that btrbk **requires** mounting the toplevel subvolume to perform its tasks.

I'm using btrbk via a systemd timer. I have a daily and hourly timer set up. Each timer starts by mounting the btrfs root, performing the btrbk task, and unmounting the btrfs root.

I create hourly snapshots and on a daily basis I use btrbk to transfer those to two different USB HDD's as well as to a remote server via SSH.

**Here's the problem.** I now end up (after some time) with a nested list of mounts for one particular mount point as shown below. I don't understand why or how this is happening. It does have side effects (disk access can hang or be very slow). The apparent "cure" is to restart the nfs server service, but I'm still trying to understand the issue fully.

The relevant parts of my fstab:
```
# cat /etc/fstab
UUID=28D099A-9D92-487C-8113-A231CAD0EEF2  /     btrfs       rw,noatime,nodiratime,compress=lzo,space_cache,subvol=/@btrtop/snapshot 0 0 #mounts my root filesystem
UUID=28D099A-9D92-487C-8113-A231CAD0EEF2  /mnt/btrtop/root  btrfs   noauto,nofail,rw,noatime,nodiratime,compress=lzo,space_cache    0 0 #mounts the top btrfs volume for btrbk access to all snapshots
/var/cache/pacman       /srv/nfs/var/cache/pacman       none  bind  0 0
```

The relevant parts of this output:

```
# findmnt -t btrfs
TARGET                                      SOURCE                                                            FSTYPE OPTIONS
/                                           /dev/mapper/xyz[/@btrtop/snapshot]                     btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot
├─/srv/nfs/var/cache/pacman                 /dev/mapper/xyz[/@btrtop/snapshot/var/cache/pacman]    btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot
│ └─/srv/nfs/var/cache/pacman               /dev/mapper/xyz[/@btrtop/snapshot/var/cache/pacman]    btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot
│   └─/srv/nfs/var/cache/pacman             /dev/mapper/xyz[/@btrtop/snapshot/var/cache/pacman]    btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot
│     └─/srv/nfs/var/cache/pacman           /dev/mapper/xyz[/@btrtop/snapshot/var/cache/pacman]    btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot
│       └─/srv/nfs/var/cache/pacman         /dev/mapper/xyz[/@btrtop/snapshot/var/cache/pacman]    btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot
│         └─/srv/nfs/var/cache/pacman       /dev/mapper/xyz[/@btrtop/snapshot/var/cache/pacman]    btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot
│           └─/srv/nfs/var/cache/pacman     /dev/mapper/xyz[/@btrtop/snapshot/var/cache/pacman]    btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot
│             └─/srv/nfs/var/cache/pacman   /dev/mapper/xyz[/@btrtop/snapshot/var/cache/pacman]    btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot
├─/var/cache/pacman                         /dev/mapper/xyz[/@btrtop/snapshot/var/cache/pacman]    btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot
│ └─/var/cache/pacman                       /dev/mapper/xyz[/@btrtop/snapshot/var/cache/pacman]    btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot
│   └─/var/cache/pacman                     /dev/mapper/xyz[/@btrtop/snapshot/var/cache/pacman]    btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot
│     └─/var/cache/pacman                   /dev/mapper/xyz[/@btrtop/snapshot/var/cache/pacman]    btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot
│       └─/var/cache/pacman                 /dev/mapper/xyz[/@btrtop/snapshot/var/cache/pacman]    btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot
│         └─/var/cache/pacman               /dev/mapper/xyz[/@btrtop/snapshot/var/cache/pacman]    btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot
│           └─/var/cache/pacman             /dev/mapper/xyz[/@btrtop/snapshot/var/cache/pacman]    btrfs  rw,noatime,nodiratime,compress=lzo,space_cache,subvolid=3194,subvol=/@btrtop/snapshot



```

**Comment by digint** [comment]
Looks like your linux system (what distro? using systemd?) is misbehaving here: this is not directly related to btrbk, as btrbk never mounts any filesystem. There is some magic in the code which handles `autofs` (check debug log), but all it does there is doing an extra read on the subvolume to trigger autofs mount (which is done transparently by the system).

btrfs seems to have problems with NFS I did not follow the whole discussion, as a starting point here is a link to the btrfs mailing list:
https://lore.kernel.org/linux-btrfs/162742546556.32498.16708762469227881912.stgit@noble.brown/T/

I suggest to file a bug in the btrfs mailing list unless this is already a known problem

**Comment by digint** [comment]
> The key point for this conversation seems related to the fact that btrbk requires mounting the toplevel subvolume to perform its tasks.

You might want to have a look at the brand new code removing this "toplevel subvolume mount" requirement in the [optional-volume-section](/digint/btrbk/tree/optional-volume-section) branch. See #407 for details.

```
wget https://raw.githubusercontent.com/digint/btrbk/optional-volume-section/btrbk
chmod +x btrbk
```

**Comment by MountainX** [comment]
> You might want to have a look at the brand new code removing this "toplevel subvolume mount" requirement in the [optional-volume-section](https://github.com/digint/btrbk/tree/optional-volume-section) branch. See [#407](https://github.com/digint/btrbk/issues/407) for details.

Thank you! This looks very useful. 👍 
btrbk is a great tool!

**Comment by digint** [comment]
closing this issue, "optional-volume-section" branch has made it into btrbk-0.32.0.
feel free to reopen it if you still get problems.
