### ISSUE TITLE
Btrbk runs backups just fine, but no files are actually backed up.

### ISSUE THREAD

**Issue by ThoriumTextile** [digint/btrbk#426]
Hello, as the title says, only (some?) folders are backed up.
Here's [my configuration file.](https://gist.github.com/ThoriumTextile/28a73e5d3b901204e5c4fcd029417bf4)

Currently I'm using OpenSUSE Tumbleweed, with kernel: `5.14.14-1-default`

**Comment by digint** [comment]
Are you sure all your folders specified in `subvolume` configs are actually btrfs subvolumes? You can list your subvolumes using `lsbtr /mnt/btroot` (as of btrbk-0.30.0), or `btrfs sub list -a /mnt/btroot`.

Also note that nested btrfs subvolumes will not be included in snapshots/backups.

**Comment by ThoriumTextile** [comment]
[Here](https://gist.github.com/ThoriumTextile/5c3a9a4ce13ce31ee9aafca0f91df3f3)'s lsbtr's output. 
Note that it includes both "/" and "/mnt/btroot" outputs.

I'm not totally sure, but i think that "/" is a subvolume labeled "@", from which "@boot", "@opt", etc... nest under. Those were automatically created by the openSUSE installer.

**Comment by digint** [comment]
Oh I messed something, you have a (sadly quite common) mistake in your btrbk.conf:

What you do here is defining a target for `subvolume @/usr/local` only (btrbk does not care about leading whitspaces, in your config the `target` only affects `subvolume @/usr/local`. 

btrbk.conf.5:
> Multiple 'target' sections are allowed, in any context: a 'target'
> defined in 'volume' or global context will be used for all underlying
> 'subvolume' sections (hint: run "btrbk list" or "btrbk config print"
> to see the resulting configuration).


In the btrbk
```
volume /mnt/btroot/
	snapshot_dir @/.snapshots/btrbk
	subvolume @
	...
	subvolume @/usr/local
	
target send-receive /mnt/backups/@snapshots/btrbk
```

should be:

```
target send-receive /mnt/backups/@snapshots/btrbk
volume /mnt/btroot/
	snapshot_dir @/.snapshots/btrbk
	subvolume @
	...
	subvolume @/usr/local
```
This way the `target` is inherited in all contexts (volume / subvolume)

**Comment by digint** [comment]
>I'm not totally sure, but i think that "/" is a subvolume labeled "@", from which "@boot", "@opt", etc... nest under. Those were automatically created by the openSUSE installer.

Yes `@` is a common alias for the root filesystem mounted a `/`.
`/.snapshots` is probably created by you the packet manager, (or snapper?) 

Run `lsbtr -l /`, which will print the mount points as well.

**Comment by ThoriumTextile** [comment]
Okay so, i fixed the config file and now it seems like it kinda works (binaries and things like /etc do get backed up), however as you said with:
> Also note that nested btrfs subvolumes will not be included in snapshots/backups.
directories like @opt, @root, @srv, etc... Do not get backed up (or at least their contents.

Also now i get [a bunch of warnings](https://gist.github.com/ThoriumTextile/0df3844b8d08f8e13058af7f90f12d6c) when running `btrbk run` or my script at @cron.daily.
