### ISSUE TITLE
Multiple target problem

### ISSUE THREAD

**Issue by H0w4rd** [digint/btrbk#433]
Hi, I'm new to btrbk. It looks promising, but I run into some problems.

My laptop has 2 partitions: /home  and / with several subvolumes
I need to backup all of them to two destinations - 1) my external disk, 2) another pc

This is my config:
```
timestamp_format        long

snapshot_preserve_min   2d
snapshot_preserve      14d

target_preserve_min    no
target_preserve        20d 10w *m

snapshot_dir           .snapshots_btrbk
snapshot_create        always


volume /home
  subvolume .
    target /mnt/data2/zaloha/vrana/IdeaPad_5_Pro_16ACH6
    target ssh://192.168.0.26:35143/data3/zaloha/vrana/IdeaPad_5_Pro_16ACH6

volume /
  subvolume .
  subvolume opt
  subvolume root
  subvolume srv
  subvolume usr/local
  subvolume var
    target /mnt/data2/zaloha/vrana/IdeaPad_5_Pro_16ACH6
    target ssh://192.168.0.26:35143/data3/zaloha/vrana/IdeaPad_5_Pro_16ACH6
```

Btrbk only creates local snapshots and that's all.

```
/home
+++ /home/.snapshots_btrbk/home.20211208T2213_1

/
+++ /.snapshots_btrbk/ROOT.20211208T2213_1

/opt
+++ /.snapshots_btrbk/opt.20211208T2213

/root
+++ /.snapshots_btrbk/root.20211208T2213

/srv
+++ /.snapshots_btrbk/srv.20211208T2213

/usr/local
+++ /.snapshots_btrbk/local.20211208T2213

/var
+++ /.snapshots_btrbk/var.20211208T2213
```

I've tried to move both 'target' to the top above the first volume. The result is that the first target is ignored and my snapshots are sent only to the second target.

Version 0.32.0-dev. 

I tried 0.31-3, but there was another problem:
```
/home/.
+++ /home/.snapshots_btrbk/home.20211208T2227

/.
+++ /.snapshots_btrbk/ROOT.20211208T2227

/opt
!!! Aborted: Not a child subvolume of: /

/root
!!! Aborted: Not a child subvolume of: /

/srv
!!! Aborted: Not a child subvolume of: /

/usr/local
!!! Aborted: Not a child subvolume of: /

/var
!!! Aborted: Not a child subvolume of: /
```

I can't really make it work.
What am I doing wrong?

**Comment by digint** [comment]
In the above config it should send `/home/.` and `/var` to both targets. If you want the targets for all your subvolumes, move them on top (before `volume /home`).

I'm wondering why it does not mention any targets, do you get any errors (on stderr)?

**Comment by H0w4rd** [comment]
Thank you for your answer. I moved both targets above the first volume and btrbk did everything what I expected - created all snapshots and sent them to both targets.

But it looks that it works that way only once a day :)
When I run btrfs again, it only creates snapshots. It doesn't send them to the targets.
I expect it will work tomorrow again.
Is this behavior intended?

I would think that it should create snapshots and send them to all targets with every 'btrbk run'.

**Comment by digint** [comment]
> Is this behavior intended?

yes. this is how you configured it: "keep one daily backup, for 20 days, ..."
```
target_preserve_min    no
target_preserve        20d 10w *m
```
If you want all latest backup for a period of time, set `target_preserve_min`

see:
https://digint.ch/btrbk/doc/btrbk.conf.5.html#_retention_policy_options
https://digint.ch/btrbk/doc/btrbk.conf.5.html#_retention_policy

**Comment by H0w4rd** [comment]
I'm sorry, I haven't found this page before. It is more detail, I need to read it, thanks.

**Comment by H0w4rd** [comment]
Just one more remark, it not easy to understand the difference between target_preserve and target_preserve_min.
