### ISSUE TITLE
btrbk-verify requires btrbk 0.32, which isn't even released

### ISSUE THREAD

**Issue by bdaase** [digint/btrbk#435]
btrbk-verify requires btrbk 0.32, which isn't even released. See https://github.com/digint/btrbk/blob/c5273a8745fa60fc52b3180fa210ec3048e6a419/contrib/cron/btrbk-verify#L80.

Is this a mistake and should require an older version instead?

**Comment by digint** [comment]
it was on purpose, as I could not use "master" as a version. 0.32.0 is out now, closing ticket
