### ISSUE TITLE
Version printed via stderr

### ISSUE THREAD

**Issue by chrenderle** [digint/btrbk#452]
I wanted to pipe the version message to grep to extract the version number. In the process I found out, that the version message is printed to stderr instead of stdout. Is there a particular reason why the version number is printed to stderr? In my opinion it doesn't make sense because it is not an error.
```
sub VERSION_MESSAGE
{
  print STDERR $VERSION_INFO . "\n\n";
}
```

Because of this one needs to use `btrbk --version 2>&1 | grep <expression>` instead of `btrbk --version | grep <expression>`

**Comment by digint** [comment]
included in btrbk-0.32.2
