### ISSUE TITLE
Error during transfer

### ISSUE THREAD

**Issue by Azertooth** [digint/btrbk#453]
A backup transfer to remote target get aborted during transfer and I got this errors:

journal log
`BTRFS error (device nvme0n1p3): send: IO error at offset 23248896 for inode 16030 root 337`

btrbk log
`ERROR: Failed to send/receive subvolume: <path_to_subvolume>  -> <target>:<path_to_subvolume>`
`ERROR: ... Command execution failed (exitcode=1)`
`ERROR: ... send ioctl failed with -5: Input/output error`
`ERROR: ... unexpected EOF in stream`

I can pinpoint that inode to a specific file with the command
`btrfs inspect-internal inode-resolve 16030 <subvolume>`

but I can't wrap my head around the problem, I need to delete that file? Is that recoverable?

**Comment by digint** [comment]
There seems to be a problem with your btrfs filesystem, it probably helps if you delete that file. Ask on the btrfs mailing list or irc if the problem persists, there is nothing that btrbk can do in this regard.

Sorry for the late reply, was very busy lately...

**Comment by Azertooth** [comment]
do not worry, thank you for the support anyway, later I indeed managed to solve that migrating the fs to a more stable setup!
