### ISSUE TITLE
Doc: Clarify what happens if a filter matches multiple times

### ISSUE THREAD

**Issue by camoz** [digint/btrbk#460]
What happens if a filter matches multiple times? E.g. when there's a group `xy`, but also a volume directory and target directory named `xy`?

Referring to <https://digint.ch/btrbk/doc/btrbk.1.html#_filter_statements>

Do they all match?

IMO it would be useful to clarify that in the linked section of the man page.

**Comment by digint** [comment]
fixed in: 267cbcacdcfbac43f1803642efb057bdacb818c4, thanks!
