### ISSUE TITLE
btrbk.conf(5): Option `btrfs_commit_delete` needs explanation of possible values

### ISSUE THREAD

**Issue by camoz** [digint/btrbk#465]
In the man page `btrbk.conf(5)`, the option `btrfs_commit_delete` lacks explanation of its possible values. I think although they sound intuitive for a person familiar with btrfs, a short explicit description can't hurt.

Also maybe a reminder that the subvols aren't actually deleted/removed completely, even with `each` just the deletion is committed to disk (AFAIK).

**Comment by digint** [comment]
thanks, clarified in 90c5d119f6c9667b8b703f1c9f1e9eb1fb23ab08
