### ISSUE TITLE
Feature request: multiple recipients for gpg encryption

### ISSUE THREAD

**Issue by sbrudenell** [digint/btrbk#471]
`gpg --encrypt` may have multiple `--recipient` options. This allows multiple people to decrypt the file, without sharing keys.

I'd like to do this for my backups. I think it would make sense to have space-separated recipients, like `gpg_recipient 0x1234aaaa 0x5678bbbb`.

Thanks!

**Comment by digint** [comment]
Good point, should be easy to implement. For some reason I'm calling gpg with `--default-recipient`, I believe this had something to do with gpg always trying to do user interaction or using it's configured default.
Probably I will have to change it to `--no-default-recipient --recipient A --recipient B`.

**Comment by digint** [comment]
included in btrbk-0.32.2
