### ISSUE TITLE
Backups not transfer to the portable drive

### ISSUE THREAD

**Issue by vanarok** [digint/btrbk#478]
Why do my backups stay on the local drive and not transfer to the backup portable drive? I have tried: run, resume, clean and no errors. The backups that did't transfer are the days when my portable drive was not connected.
![2022-06-04T13:14:23,621525069+04:00](https://user-images.githubusercontent.com/6105977/171992839-7c10a923-2f3b-4f7e-be4b-d6fb5cf75a54.png)
-------
![2022-06-04T13:15:04,857145574+04:00](https://user-images.githubusercontent.com/6105977/171992869-2d4749d5-769d-47db-aae6-b63073a4b1a0.png)
-------
![2022-06-04T13:12:12,296627628+04:00](https://user-images.githubusercontent.com/6105977/171992817-c10fb77d-cd0a-4879-b343-71e47540263f.png)
-------
![2022-06-04T13:12:58,752735433+04:00](https://user-images.githubusercontent.com/6105977/171992818-ce068750-12e8-4f2b-8139-124996f2ce5a.png)

**Comment by digint** [comment]
Sorry for the late reply, I kind of missed that one.
Looks like you changed your configuration in between, as the snapshots should be in `/mnt/btr_pool/btrbk_snapshots`, but you listing shows them in `/mnt/btr_pool`.

Is this still a problem? if not, please close the issue.

**Comment by vanarok** [comment]
> Sorry for the late reply, I kind of missed that one. Looks like you changed your configuration in between, as the snapshots should be in `/mnt/btr_pool/btrbk_snapshots`, but you listing shows them in `/mnt/btr_pool`.
> 
> Is this still a problem? if not, please close the issue.

 It looks like you are right, what should I do now with the snapshots in different dir. Delete the old ones? I tried moving them to the same folder, but that didn't work.

**Comment by digint** [comment]
Recent kernels/binutils do not allow moving subvolumes into folders using `mv`. Instead, you can create new snapshots and then delete the old one:
```
btrfs subvolume snapshot -r /mnt/btr_pool/@.20220101 /mnt/btr_pool/btrbk_snapshots/@.20220101
btrfs subvolume delete /mnt/btr_pool/@.20220101
```
this will change the parent_uuid, but btrbk is perfectly fine with that
