### ISSUE TITLE
Subvolume targets are ignored when resuming a group also containing a target

### ISSUE THREAD

**Issue by luxagen** [digint/btrbk#479]
Apologies in advance if this is already known/fixed, but I'm too strapped for time right now to do a comprehensive search or test a newer version.

I had a configuration something like this, running for months:

```
volume /btr/a
  group mygroup
  target ssh://first-target.net/btr/a/.btrbk

  subvolume sv
    target ssh://second-target.net/btr/a/.btrbk
```

...and discovered today that my cron job, containing:

`btrbk resume mygroup`

...has been ignoring `second-target` all this time. I had to move the target associated with the group inside the subvolume section to get the intended behaviour.

Is this a bug or a feature? If the latter, perhaps the documentation could be amended to make it clear.

**Comment by digint** [comment]
I was not able to reproduce this, tried a couple of versions down to v0.27.2.
I guess there must be some other reason why the second-target is not sent, maybe some specific target_preserve configs?

Please try the latest version, and provide some more logging output:
```
# cd /tmp/
# wget https://raw.githubusercontent.com/digint/btrbk/v0.32.1/btrbk
# chmod +x btrbk
# ./btrbk resume mygroup -n -S -v -v
```

**Comment by luxagen** [comment]
It turns out I reported this on 0.31.3. I'll try a ```git pull``` and retest.

**Comment by luxagen** [comment]
I, too, can no longer replicate this. Either there's some complicating factor or I must simply have been wrong. Sorry for the confusion!

**Comment by luxagen** [comment]
Let's close again but with the right resolution!

**Comment by luxagen** [comment]
Let's close again but with the right resolution!
