### ISSUE TITLE
[Bug] Command execution failed (Argument list too long)

### ISSUE THREAD

**Issue by Wunderharke** [digint/btrbk#481]
I had an error in my configuration, which is why no snapshots were deleted for a long time.
When I ran btrbk, and it tried to delete a large number of subvolumes, I got the btrfs subvolume delete error: `Command execution failed (Argument list too long)` following `ERROR: Failed to match error messages from delete command, assuming nothing deleted` from btrbk.

I then had to delete some of the subvolumes manually.
Unfortunately, I cannot give any exact information about the number of volumes, but the command that was to be executed had over 130 thousand characters.

I consider this  a bug and suggest splitting the commands after a maximum number of volumes, even within a single target.

**Comment by zatricky** [comment]
Dup of #476 I think where I had the same problem.

Is this on a 64bit or 32bit system? The system-default limits are supposed to be different between the two.

**Comment by digint** [comment]
duplicate, closing issue
