### ISSUE TITLE
Ability to set backup name

### ISSUE THREAD

**Issue by grondinm** [digint/btrbk#5]
I think it would be a great feature to be able to set custom backup names instead of it always being date created. It could be done with a command line option like -n or in the config file or both.

**Comment by digint** [comment]
The date suffix is used internally for the backup retention calculation, and cannot be removed without breaking this feature.
Configurable snapshot/backup names could be implemented, but I don't think this could cause more confusion than being useful (e.g. what happens if you rename two backups to the same name?).

**Comment by grondinm** [comment]
2 good points i was not considering. Still think it could be nice to have the option to name a backup and maybe exclude it from regular retention periods incase you want to keep this specific backup for longer...Could be a seldomly used feature...

**Comment by digint** [comment]
Implemented `subvolume_name` configuration option.
Fixed in: 01a25ad4df4c5e3c0fa43798f0b86ab43a9f09ea

**Comment by digint** [comment]
Fix included in btrbk-0.17.0

**Comment by grondinm** [comment]
so is this set once in the config file or on the command line?

**Comment by digint** [comment]
It's in the config file, simply specify `snapshot_name <basename>`  in your `subvolume` section. (also check the man-page: btrbk.conf(5) for details)

See btrbk.conf.example:
```
volume ssh://my-remote-host.com/mnt/btr_pool
  subvolume data_0
    snapshot_dir  snapshots/btrbk
    snapshot_name data_main
    target send-receive    /mnt/btr_backup/_btrbk/my-remote-host.com
```

In this example, the snapshot will be named `/mnt/btr_pool/snapshots/btrbk/data_main.20150501`. **The backups always get the same basename as the snapshot,** and will be ` /mnt/btr_backup/_btrbk/my-remote-host.com/data_main.20150501` in the example.

**Comment by grondinm** [comment]
Great thank you. I was looking in the commits for the update to the man page but for some reason i did not think to look at the actual man page lol. Thank you again for all your work on this
