### ISSUE TITLE
ssh_filter_btrbk.sh: filter snapshot names

### ISSUE THREAD

**Issue by BLu85** [digint/btrbk#507]
Hi,

First of all I'd like to thank you all for the great job you have done and do.

My question, maybe already answered, is: is it possible to filter the name of incremental backups?
For example is there a way to only accept backups named _data.xyz_ and drop everything else?

Thanks

**Comment by digint** [comment]
Not sure what you are trying to achieve here. The most straight-forward way is to set the `group` config option, then you can call `btrbk run mygroup`. You can also filter for source and targets, see manpage btrbk(1) "FILTER STATEMENTS"

**Comment by BLu85** [comment]
The idea is to filter the backups at the receiving side (remote).
The backups on the remote cannot be deleted from the client (sender). The client can only send backups.
I set `ssh_filter_btrbk.sh --doas --receive` in the `authorized_keys` file. So the idea is to only receive backups that have a name that matches a pattern.

**Comment by digint** [comment]
The problem here is that `btrfs receive` takes a directory as argument (not a full file path). This means that `ssh_filter_btrbk.sh` does not know about the filename to be created, this is encoded in the send-stream.

The directory can be restricted by `ssh_filter_btrbk.sh --restrict-path`.

**Comment by BLu85** [comment]
I understand.
Thanks

**Comment by digint** [comment]
added a note in the man page: fa7ef1bf63d376270d9afaee1cb3c7d3dcda9bc6
