### ISSUE TITLE
"Sneakernet" seeding

### ISSUE THREAD

**Issue by ktims** [digint/btrbk#51]
I'd like to seed the remote backup target with snapshot(s) delivered on a USB drive. What I'm thinking is to run 'btrbk' with a temporary target of the USB mount point. I can then move the USB drive to the target server and 'btrfs send | btrfs receive' into the backup volume. It's not clear to me if this will cause the parent relationships to be preserved and incremental backups to happen from then on. Does this work? Is there another way to accomplish the same thing if not?

When I tried a dry run of this by send/receiving the 'root' snapshot to the USB drive and then running btrbk resume targeting it, it seemed to be copying the entire thing again.

**Comment by digint** [comment]
This should work. The important thing is that the received_uuid on the backup side must point to the _original_ subvolume (on the source host, NOT the one on the USB disk). You can check this with `btrfs subvolume show <subvol>`.

Note that kernels >=4.1 have a bug when re-sending subvolumes, see this thread:
http://thread.gmane.org/gmane.comp.file-systems.btrfs/48798
This patch is scheduled for the 4.4 kernel.

So if you have one of these kernels, the received_uuid will probably point to the subvolume on your USB disk, loosing the original relationship.

If this is the case, I'm afraid you'll have to patch your kernel with the patch provided in the thread mentioned above (works fine, I used it for 4.2.x and 4.3).

**Comment by ktims** [comment]
So I tried this today, and it looks like doing a send / received from the USB HDD to the target btrfs volume causes the critical `received_uuid` to be changed to the UUID of the USB HDD subvolume. Trying to figure out if there's a way around that.

**Comment by ktims** [comment]
I just realized I'm being incredibly stupid here. I used btrfs send and then 'received' the filesystem on the USB disk's btrfs. I should have just saved the output of btrfs send to a file and replayed that on the server. D'oh. Will go through the motions again... that will work, I'm sure of it. Thanks.

**Comment by digint** [comment]
Yes that will work, and would be the real "sneakernet" approach :)

**Comment by williamstlr** [comment]
@ktims Would you mind detailing your process here? I'm very interesting in doing this myself. Thanks

**Comment by digint** [comment]
Just wrote a FAQ entry on this topic. Hope it helps!

https://github.com/digint/btrbk/blob/master/doc/FAQ.md#what-is-the-most-efficient-way-to-clone-btrfs-storage

**Comment by williamstlr** [comment]
Fantastic. Thank you very much. So after transferring subvolumes to my removable storage and receiving them on the remote side, how do I link the subvolume that is now on the remote side with btrbk so that it will continue to make incremental backups to the remote site?

**Comment by digint** [comment]
No need to link anything, btrfs has already done that for you. Just point your target to the location where you restored the streams. For the examples in the FAQ this would then be something like:

```
volume /source
  subvolume subvolX
    target send-receive ssh://backup-host.tld/target
```

btrbk will find the restored subvolumes there, and take them into account for incremental backups (no matter of the subvolume names, btrfs keeps track of the source in the "received_uuid").

If you want to be certain, run `btrbk -l debug dryrun`, and grep for "Latest common snapshots for: /source/subvolX ...".

**Comment by williamstlr** [comment]
Awesome. Thanks
