### ISSUE TITLE
Ubuntu Server Backup Snapshot

### ISSUE THREAD

**Issue by asomer46** [digint/btrbk#52]
Hello, I have set up for BTRBK snapshot and backup a Ubuntu server. I'm not sure if I did it right. I believe that I have a flaw. In particular diie logic to create the Subvolumes was not easy to recognize. I have the home- and Rootpartionionen from Standard "/" after "/mnt/c" reverse hanging. Would I dri can restore? Does the snapshot without error even when the current root partition?

/etc/fstab:
UUID=..... /mnt/c/rootfs               btrfs   defaults,subvol=@ 0       1
UUID=.... /mnt/c/home           btrfs   defaults,subvol=@home 0       2
UUID=.... none            swap    sw              0       0
/dev/sda1 /mnt/c/server btrfs defaults 0 0

/etc/btrbk/backup.conf:
snapshot_preserve_daily    14
snapshot_preserve_weekly   0
snapshot_preserve_monthly  0
target_preserve_daily      20
target_preserve_weekly     10
target_preserve_monthly    all

snapshot_dir               btrbk_snapshots

volume /mnt/c
  subvolume rootfs
    target send-receive    /mnt/c/server

  subvolume home
    target send-receive    /mnt/c/server

**Comment by digint** [comment]
You need a mountpoint for the btrfs filesystem *containing* your subvolumes "@" and "@home", which is probably the partition you created the btrfs filesystem. Assuming this partion is "/dev/sdb1", you need to:

1. Add a mountpoint in fstab for the complete btrfs tree (subvolid=0)

```
/dev/sdb1 /mnt/btr_pool btrfs defaults,subvolid=0
```
If you want to mount this by-uuid also, check `lsblk -f` which gives you the corresponding UUID.

When mounted, you should see something like this:
```
# ls /mnt/btr_pool
@   @home   [...other subvolumes...]
```

2. In btrbk.conf, use /mnt/btr_pool as volume:

```
volume /mnt/btr_pool
  subvolume @
    target send-receive [...]
  subvolume @home
    target send-receive [...]
```

hope this helps,

- Axel

**Comment by asomer46** [comment]
I have it copied to a computer. Where /dev/sda1, the computer hard drive and /dev/sdb1 disk in USB drive. Is that correct? The configuration certainly works to create the snapshot.

UUID=8 /               btrfs   defaults,subvol=@          0  1        (#sda1) 
UUID=8 /home      btrfs   defaults,subvol=@home 0  2        (#sda1) 
/dev/sda1 /mnt/btr_pool btrfs defaults,subvolid=0

snapshot_dir btrbk_snapshots

volume /mnt/btr_pool
  subvolume @
    target send-receive /media/r7598/backup (#sdb1)  
  subvolume @home
    target send-receive /media/r7598/backup (#sdb1)

**Comment by digint** [comment]
yes this should work. Don't forget to create your snapshot_dir (`mkdir /mnt/btr_pool/btrbk_snapshots`). Then run `btrbk -v dryrun`, and see if everything is created where you want it to.

**Comment by asomer46** [comment]
Just as it has worked. Many thanks. That helped me alot.
Now I have to mount on the server Subvolumes. I hope that it just works and I can boot normally again.

**Comment by digint** [comment]
@asomer46 what ubuntu version do you use? Did ubuntu installer create one partition on your disk with btrfs and subvolumes "@" and "@home" as described in: "Ubuntu-specific subvolume layout in 11.04 and later" on the [ubuntu help page](https://help.ubuntu.com/community/btrfs)

@asomer46 could you please paste the output of `btrfs subvolume list -auq /mnt/btr_pool/` (this would help me to write a little ubuntu howto)

**Comment by asomer46** [comment]
﻿Hi,



I hope that you are satisfied with it. I would be very happy about the instructions. Actually I wanted to write a self.





Version: Ubuntu 14.04.3 LTS 



btrfs subvolume list -auq /mnt/c/btr_pool/
ID 257 gen 17642 top level 5 parent_uuid - uuid x path @
ID 258 gen 17642 top level 5 parent_uuid - uuid x path @home
ID 289 gen 15934 top level 257 parent_uuid - uuid x path <FS_TREE>/@/mnt/c
ID 317 gen 15854 top level 289 parent_uuid - uuid x path <FS_TREE>/@/mnt/c/btr_pool

ID 320 gen 15888 top level 5 parent_uuid x uu    id x path btrbk_snapshots/@.20151119
ID 321 gen 15888 top level 5 parent_uuid a x uu     id x path btrbk_snapshots/@home.20151119
ID 322 gen 16344 top level 5 parent_uuid x uu     id 3 x path btrbk_snapshots/@.20151120
ID 323 gen 16344 top level 5 parent_uuid x uu       id x path btrbk_snapshots/@home.20151120




# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sdc1 during installation
UUID=xxxxx /               btrfs   defaults,subvol=@ 0       1
# /home was on /dev/sdc1 during installation
UUID=xxxxx /home           btrfs   defaults,subvol=@home 0       2
# swap was on /dev/sdd5 during installation
UUID=xxxxx none            swap    sw              0       0



### thus far, the configuration is unchanged


/dev/sda1 /mnt/a btrfs defaults 0 0

/dev/sdb1 /mnt/b btrfs defaults 0 2
/mnt/b/images /var/cache/xxxxxx/x none defaults,bind  0 2
/mnt/b/events /var/cache/xxxxxx/x none defaults,bind 0 2

/dev/sdc1 /mnt/c/btr_pool btrfs defaults,subvolid=0

/dev/sdd1 /mnt/d ext4 defaults 0 0



-----Ursprüngliche Nachricht-----
Von: Axel Burri <notifications@github.com>
Gesendet: Fre 20 November 2015 12:37
An: digint/btrbk <btrbk@noreply.github.com>
CC: asomer46 <563757@gleisnetze.de>
Betreff: Re: [btrbk] Ubuntu Server Backup Snapshot (#52)

@asomer46 what ubuntu version do you use? Did ubuntu installer create one partition on your disk with btrfs and subvolumes "@" and "@home" as described in: "Ubuntu-specific subvolume layout in 11.04 and later" on the ubuntu help page

@asomer46 could you please paste the output of btrfs subvolume list -auq /mnt/btr_pool/ (this would help me to write a little ubuntu howto)

**Comment by asomer46** [comment]
/etc/btrbk/backup.conf:
snapshot_preserve_daily 14
snapshot_preserve_weekly 0
snapshot_preserve_monthly 0
target_preserve_daily 20
target_preserve_weekly 10
target_preserve_monthly all

The source drive is now 14 snapshots. But on the target can be seen only 21 total snapshots. There is no weekly and monthly backups? Why is that?

**Comment by asomer46** [comment]
/etc/btrbk/backup.conf:
snapshot_preserve_daily 14
snapshot_preserve_weekly 0
snapshot_preserve_monthly 0
target_preserve_daily 20
target_preserve_weekly 10
target_preserve_monthly all

The source drive is now 14 snapshots. But on the target can be seen only 21 total snapshots. There is no weekly and monthly backups? Why is that?

**Comment by digint** [comment]
Sorry for the late reply...
I can't really tell what's going on, since I'm pretty sure the preserve mechanism works correctly (as it has been there since the beginning and did not change much).

- If you have enabled the **transaction_log** config option, there is a log.
- If you run `btrbk -v dryrun`, you get a table showing what's going on in the scheduler, maybe this helps

**Comment by asomer46** [comment]
No problem due to the delay. "BTR BK -c -V dry run" has helped. Everything works correctly. Thank you.

**Comment by asomer46** [comment]
I had to use to restore a backup. This was possible. It is however important to know that you have to install the new Bottloader. In the near future I will report on my side http://gleisnetze.de about it.
