### ISSUE TITLE
broken link in online documentation

### ISSUE THREAD

**Issue by ian-kelling** [digint/btrbk#53]
from: http://www.digint.ch/btrbk/doc/readme.html
A link exists to: http://www.digint.ch/btrbk/doc/doc/FAQ.md, which is broken

**Comment by digint** [comment]
Thanks for reminding me...
This link was made to work for GitHub pages (which process .md files automatically), but then breaks on the webserver...

Fixed  www.digint.ch/btrbk/doc/readme.html (Now replacing "doc/FAQ.md" by "faq.html" at html page creation time in filewiki vars)
