### ISSUE TITLE
btrfs-mail: declare the associative arrays

### ISSUE THREAD

**Issue by aleksejrs** [digint/btrbk#530]
It does not work for me without this ([the blocks](https://github.com/digint/btrbk/blob/master/contrib/cron/btrbk-mail#L24) overwrite each other):

```
declare -A rsync_src
declare -A rsync_dst
declare -A rsync_log
declare -A rsync_rsh
declare -A rsync_opt
```

**Comment by digint** [comment]
Added declare statements in: b63609c29871c9ab5f16bf1726b2541f0e73ff7f

my version of bash seems to be fine without declaring associative arrays:
```
# bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```

> the blocks overwrite each other

not sure what you mean with than, works for me

**Comment by aleksejrs** [comment]
bash 5.2 had some changes related to arrays.

**Comment by digint** [comment]
I have checked master (db45f0b09c3cda49aca5b3cc6b1150bac3e87fad) with and without declare, strangely (?) works fine for me with both bash-5.1 and bash-5.2.

should be fine, @aleksejrs please reopen if not
