### ISSUE TITLE
btrfs-mail: iterate over the keys of $rsync_src instead of using $rsync_enable

### ISSUE THREAD

**Issue by aleksejrs** [digint/btrbk#531]
`$rsync_enable` can become huge and it is much easier to comment a block out instead, if the script [iterates over the keys](https://stackoverflow.com/questions/3112687/how-to-iterate-over-associative-arrays-in-bash) of `$rsync_src` in both cases. Note that `$rsync_enable` is also checked [here](https://github.com/digint/btrbk/blob/master/contrib/cron/btrbk-mail#L232).

**Comment by digint** [comment]
> $rsync_enable can become huge

Why? a list of keys defined above?

I guess I don't understand exactly what you mean here.

**Comment by aleksejrs** [comment]
Am I correct that I need to put the keys into it manually? I have lots of keys to add.

**Comment by digint** [comment]
I have added an example on how to enable all defined rsync sources in db45f0b09c3cda49aca5b3cc6b1150bac3e87fad.

Closing issue, feel free to reopen if this does not help.
