### ISSUE TITLE
Add compatibility option for btrfs-progs v3.14

### ISSUE THREAD

**Issue by digint** [digint/btrbk#6]
Add support for btrfs-progs v3.14.1 (stable on Ubuntu 14.10 / Debian wheezy backport).

btrfs-progs 3.14 do not support "btrfs subvolume list -R" flag, which makes it impossible to check send/receive relationship between source and backup subvolume.

**Comment by digint** [comment]
added branch btrfs-tools-compat for testing:

https://github.com/digint/btrbk/tree/btrfs-tools-compat

**Comment by pschoeni** [comment]
Thanks for your prompt action! Works as expected.

**Comment by digint** [comment]
removed branch `btrfs-progs-compat`, the fix has been merged to master: 28ed7d65e817f344076f06c69f8ca398017d3722

**Comment by digint** [comment]
Merged in v0.15
