### ISSUE TITLE
[FR] Tweak options for compressed raws

### ISSUE THREAD

**Issue by Anthony25** [digint/btrbk#60]
Hello,
Could you think about an option that specifies the parameters sent to the compression tool for compressed raws backups ? It would be great to use, for example, multithreading with xz (with the "-T" option), or tweak the compression level.

I thought about something like, for example : 
```
raw_target_compress_opt  -T 0 -3
```

Thanks!

**Comment by digint** [comment]
Added configuration options "raw_target_compress_level", "raw_target_compress_threads": a82c1f533a0737a1a58fd9574cd4195fa6c9e4af

**Comment by digint** [comment]
Implemented in btrbk v0.22.0
