### ISSUE TITLE
btrbk added to Alpine Linux today

### ISSUE THREAD

**Issue by itoffshore** [digint/btrbk#62]
`btrbk` [added to Alpine Linux](https://pkgs.alpinelinux.org/package/testing/x86_64/btrbk) today.

**Comment by digint** [comment]
Nice to hear that!

Do you want me to add installation instructions for this on the README file? If yes, please tell me how packages are installed in Alpine Linux or create a pull request.

Should I trigger you on new releases?

**Comment by itoffshore** [comment]
see https://github.com/digint/btrbk/pull/63

I should get an email from [Sibbell](https://sibbell.com/about/) on new releases but if you can update me too that would be very helpful.
