### ISSUE TITLE
--progress option not showing anything

### ISSUE THREAD

**Issue by akurei** [digint/btrbk#64]
When run with --progress option on ZSH on Arch Linux x86_64 the progress is not visible.

I have found the offending line is 1288. If I comment it out, the problem is gone.

**Comment by akurei** [comment]
Also passing ```-traeb``` to ```pv``` will disable the non-functional progress bar and show the average speed counter and written bytes.

**Comment by digint** [comment]
bug introduced in: f526d454f7abec2d4d29affdbe688d1d7bbd55b3 (btrbk-v0.21)

stderr gets redirected to stdout: while this is correctly catching `btrfs send/receive` messages, it also redirects the output of `pv` (progress viewer).

**Comment by akurei** [comment]
Works now in 614438183f77338b068aa5bb4f7f59c6087f17dd
But you forgot the pv options.

**Comment by digint** [comment]
fixed in: 614438183f77338b068aa5bb4f7f59c6087f17dd

> But you forgot the pv options.
fixed in: 14c5c41e723968da1fae40743f7ca9e18c1fe73e

@akurei Thanks for reporting!

**Comment by akurei** [comment]
@digint No, thanks to you for the fast fix! Thank you!
