### ISSUE TITLE
btrbk crashing with btrfs-progs v4.4

### ISSUE THREAD

**Issue by kolcon** [digint/btrbk#66]
When running with btrfs-progs 4.4.1 :

ERROR: process died unexpectedly (btrbk v0.22.0)
Please contact the author: Axel Burri <axel@tty0.ch>

Stack Trace:
----------------------------------------
Use of uninitialized value in hash element at /usr/bin/btrbk line 1532.
 at /usr/bin/btrbk line 186.
	main::__ANON__("Use of uninitialized value in hash element at /usr/bin/btrbk "...) called at /usr/bin/btrbk line 1532
	main::btr_tree(HASH(0x1a4a628)) called at /usr/bin/btrbk line 1562
	main::vinfo_subvol_list(HASH(0x1a4a628)) called at /usr/bin/btrbk line 500
	main::vinfo_root(HASH(0x1a4a628)) called at /usr/bin/btrbk line 2707

Dump for parent volume with 4.3.2 

$VAR1 = \{
            'NAME' => 'a',
            'PATH' => '/mnt/a',
            'PRINT' => '/mnt/a',
            'REAL_PATH' => '/mnt/a',
            'REAL_URL' => '/mnt/a',
            'URL' => '/mnt/a',
            'id' => 5,
            'is_root' => 1
          };

with 4.4.1 

$VAR1 = \{
            'NAME' => 'a',
            'PATH' => '/mnt/a',
            'PRINT' => '/mnt/a',
            'REAL_PATH' => '/mnt/a',
            'REAL_URL' => '/mnt/a',
            'URL' => '/mnt/a'
          };

ie. the id and is_root is incorrectly fetched from the output.

3.4.1: /mnt/a is btrfs root
4.4.1: /mnt/a is toplevel subvolume

**Comment by kolcon** [comment]
fix :

if ($ret =~ /^\Q$real_path\E is btrfs root/) change to 
if ( ($ret =~ /^\Q$real_path\E is btrfs root/) or ($ret =~ /^\Q$real_path\E is toplevel subvolume/) )

**Comment by digint** [comment]
fixed in: 7a4aa4b650cbab9a0f309b62a4f16161c40e70ec

**Comment by digint** [comment]
Fixed in btrbk v0.22.1
