### ISSUE TITLE
Backup fails when mounting btrfs subvolume directly instead of btrfs root

### ISSUE THREAD

**Issue by akurei** [digint/btrbk#67]
When I backup, btrbk fails when I mount a subvolume via the ```subvol=subvolname``` mount option and use the mount as a target. When I mount the default (root) "subvolume" and then backup there (with the config file adapted to the now longer backup path), I am having no problems.

Example:

### What fails
- ```mount /dev/mapper/ooo /mnt/backup -o defaults,relatime,compress=lzo,subvol=btrbk```
- ```btrbk -v -c /etc/btrbk/work.conf clean; btrbk --progress -v -c /etc/btrbk/work.conf run```

### What works
- ```mount /dev/mapper/ooo /mnt/backup -o defaults,relatime,compress=lzo```
- ```btrbk -v -c /etc/btrbk/work2.conf clean; btrbk --progress -v -c /etc/btrbk/work2.conf run```

Attached are the config files and error message. [bug.zip](https://github.com/digint/btrbk/files/100921/bug.zip)

In the root subvolume there are three other subvolumes. Two unrelated and the ```btrbk``` subvolume.

**Comment by akurei** [comment]
Also I am not certain, if this is not an upstream bug in btrfs send/receive itself.

**Comment by digint** [comment]
This looks like an error in your filesystem:

> ERROR: failed to open btrbk/pantalaimon_root.20160122T1528/var/log/journal/a7afe64e28ab467aa48a02f69537befc/user-1000.journal. No such file or directory

Something seems wrong with this file. Look at `dmesg` for btrfs errors and try running `btrfs scrub start -B <mountpath>`, and maybe also `btrfs check <device>`, this might give you hints of what is going on.

Note: if you run `btrbk -l debug`, it will show you the command that causes the error, so you can replay this by hand (try adding -v to `btrfs send`).

PS: I'm away until next saturday, so don't expect any mor answers before that

**Comment by akurei** [comment]
Thanks! I will investigate this some more and keep posting updates in this bug report.

**Comment by akurei** [comment]
No it turned out the ATA error messages were a loose cable. Did not fix it. Also the destructuive read/write test showed no errors at all. Next one is a non-descructive of source file system

**Comment by digint** [comment]
closing issue, as this is not btrbk related

@akurel please reopen if your issue is not yet resolved

**Comment by akurei** [comment]
I have not yet been able to test on the affected disk as it is still running tests. I will reopen if the error remains.
