### ISSUE TITLE
Format for new preserve options?

### ISSUE THREAD

**Issue by digint** [digint/btrbk#70]
I have added new configuration options (in 9eb38ac9d0a8fc5507666608e238477a6b9a7d46):
```
snapshot_preserve [<daily>d] [<weekly>w] [<monthly>m] [<yearly>y]
target_preserve   [<daily>d] [<weekly>w] [<monthly>m] [<yearly>y]
```
These are shortcuts to the `snapshot_preserve_*` options. Both old and new options can be used interchangeably in the configuration file.

Before changing all the docs, I am wondering what is more intuitive / readable. Here's an example from the documentation:

### Old representation
```
snapshot_preserve_daily    14
snapshot_preserve_weekly   0
snapshot_preserve_monthly  0

target_preserve_daily      20
target_preserve_weekly     10
target_preserve_monthly    all

snapshot_dir               btrbk_snapshots

volume /mnt/btr_pool
  subvolume rootfs
    target send-receive    /mnt/btr_backup/mylaptop

  subvolume home
    target send-receive    /mnt/btr_backup/mylaptop
```

### New representation:
```
snapshot_preserve          14d   0w  0m
target_preserve            20d  10w  *m

snapshot_dir               btrbk_snapshots

volume /mnt/btr_pool
  subvolume rootfs
    target send-receive    /mnt/btr_backup/mylaptop

  subvolume home
    target send-receive    /mnt/btr_backup/mylaptop
```

### Questions
  * Which representation is more intuitive / readable?
  * Currently, the asterisk character is used for "all", would it be more intuitive to use an alternative? What is the most common/intuitive character describing "all"?
```
target_preserve            20d  10w  *m
target_preserve            20d  10w  +m
target_preserve            20d  10w  -m
target_preserve            20d  10w  %m
```

Please vote by simply commenting on this issue, thanks!

**Comment by LollenJumplan** [comment]
The new preservation layouts remind me of crontab entries, which is a good thing in my mind, because that way, it is easy to understand what is meant and to quickly understand a given config file.
Also, I would much prefer the asterisk character for "all", as it is used basically everywhere with exactly that meaning, so it just makes sense for me to use it here, too.
