### ISSUE TITLE
Ability to send all missed snapshots after x amount of days.

### ISSUE THREAD

**Issue by TH3L0N3WOLF** [digint/btrbk#8]
It would be nice to have the ability to configure BTRBK to send all snapshots that were unable to be sent to a backup volume once the volume appears again. Currently, it'll only send the current day's snapshots, without attempting to re-send previously failed transfers.

**Comment by digint** [comment]
Thank you for the input. I already thought of this and I will implement this in a future version. I even think this should be enabled by default, but configurable with an `resume_missing` option.

**Comment by digint** [comment]
Implemented `resume_missing` option in branch:
https://github.com/digint/btrbk/tree/resume_missing

For now it's only working for incremental backups, and it might behave strangely if `snapshot_preserve_daily` is greater than `target_preserve_daily`.

**Comment by digint** [comment]
removed branch `resume_missing`, the fix has been merged to master: 2a65895d186300e994c2d977b033a2e7a97afe42

**Comment by digint** [comment]
Merged in v0.15
