### ISSUE TITLE
btrbk fails after restoring backups

### ISSUE THREAD

**Issue by zalaare** [digint/btrbk#80]
I've used btrbk for the past year to maintain my backups on a remote server.  I have had to use these backups within the last month to restore my production server and all went as planned.  However, btrbk is now failing to send my snapshots to my backup server since the restore.

I've dumped ALL snapshots on BOTH my production server and backup server for a specific subvolume to test and recorded the results [here](http://pastebin.com/raw/k6yeZaFP).

The system is "Linux maizy 4.4.0-1-amd64 #1 SMP Debian 4.4.6-1 (2016-03-17) x86_64 GNU/Linux"

Please tell me what is happening here so I can get this fixed.

**Comment by digint** [comment]
Yeah, this is a known problem. After restoring, the parent_uuid of the old snapshots still point to the old (replaced) subvolume.
I just implemented some changes in this regard, could you please try the newest version on the [devel](/digint/btrbk/tree/devel) branch:

https://github.com/digint/btrbk/blob/devel/btrbk

**Comment by zalaare** [comment]
Fastest response ever!  Thank you so much!  That worked perfectly for me.

Keep up the great work, your doing good stuff!

**Comment by digint** [comment]
Heh well, I was just working on btrbk anyways :)

I forgot to ask: do you have a debug output of the latest run (the first run with the devel version)? If yes, could you please send it to me (via email to keep some privacy)?

**Comment by zalaare** [comment]
Sent. :)

**Comment by zalaare** [comment]
A successful run of btrbk in this state results in a status code=10 exit vs the 0 exit systemd would expect, btw.  Many warnings in the output, which makes sense maybe the first time, but not after.

**Comment by digint** [comment]
This should now all be resolved in [btrbk-0.23.0-rc1](/digint/btrbk/releases/tag/v0.23.0-rc1).

@zalaare I would be interested in the results from the new version, do you still have this setup?
