### ISSUE TITLE
target_preserve* not overridable in subvolume sections

### ISSUE THREAD

**Issue by marcecj** [digint/btrbk#85]
I just upgraded to btrbk 0.23.0, and it seems that I can't override the `target_preserve` settings in `subvolume` sections (though overriding it in a `volume` section still works, strangely enough).  In my limited testing, this appeared to also be the case with `target_preserve_min`.  On the other hand, `snapshot_preserve` behaves as expected.

For example, my laptop now has the following configuration:

    snapshot_preserve_min   1h
    snapshot_preserve       24h
    
    target_preserve_min     1h
    target_preserve         31d
    
    timestamp_format        long
    snapshot_dir            .snapshot
    ssh_identity            /root/.ssh/id_rsa
    
    volume /mnt/rootfs
      target send-receive    ssh://diefledermaus/media/MARCEC_BACKUP/arthur
      subvolume rootfs
      subvolume home
        snapshot_preserve    14d
      subvolume portage_distfiles
        target_preserve   1d
      subvolume var

Looking at the output of ` btrbk --print-schedule dryrun` then shows:

    # btrbk --print-schedule dryrun
    SNAPSHOT SCHEDULE
    action  host  subvol                                                 scheme   reason
    ------  ----  -----------------------------------------------------  -------  --------------------------------------------
    delete  -     /mnt/rootfs/.snapshot/rootfs.20160422                  1h+ 24h  -
    delete  -     /mnt/rootfs/.snapshot/rootfs.20160423                  1h+ 24h  -
    -       -     /mnt/rootfs/.snapshot/rootfs.20160424                  1h+ 24h  preserve hourly: first of hour, 14 hours ago
    -       -     /mnt/rootfs/.snapshot/rootfs.20160424T1417             1h+ 24h  preserve hourly: first of hour, 0 hours ago
    -       -     /mnt/rootfs/.snapshot/home.20160410                    1h+ 14d  preserve daily: first of day, 14 days ago
    -       -     /mnt/rootfs/.snapshot/home.20160411                    1h+ 14d  preserve daily: first of day, 13 days ago
    -       -     /mnt/rootfs/.snapshot/home.20160412                    1h+ 14d  preserve daily: first of day, 12 days ago
    -       -     /mnt/rootfs/.snapshot/home.20160413                    1h+ 14d  preserve daily: first of day, 11 days ago
    -       -     /mnt/rootfs/.snapshot/home.20160414                    1h+ 14d  preserve daily: first of day, 10 days ago
    -       -     /mnt/rootfs/.snapshot/home.20160415                    1h+ 14d  preserve daily: first of day, 9 days ago
    -       -     /mnt/rootfs/.snapshot/home.20160416                    1h+ 14d  preserve daily: first of day, 8 days ago
    -       -     /mnt/rootfs/.snapshot/home.20160417                    1h+ 14d  preserve daily: first of day, 7 days ago
    -       -     /mnt/rootfs/.snapshot/home.20160418                    1h+ 14d  preserve daily: first of day, 6 days ago
    -       -     /mnt/rootfs/.snapshot/home.20160419                    1h+ 14d  preserve daily: first of day, 5 days ago
    -       -     /mnt/rootfs/.snapshot/home.20160421                    1h+ 14d  preserve daily: first of day, 3 days ago
    -       -     /mnt/rootfs/.snapshot/home.20160422                    1h+ 14d  preserve daily: first of day, 2 days ago
    -       -     /mnt/rootfs/.snapshot/home.20160423                    1h+ 14d  preserve daily: first of day, 1 days ago
    -       -     /mnt/rootfs/.snapshot/home.20160424                    1h+ 14d  preserve daily: first of day, 0 days ago
    -       -     /mnt/rootfs/.snapshot/home.20160424T1417               1h+ 14d  preserve min: 0 hours ago
    delete  -     /mnt/rootfs/.snapshot/portage_distfiles.20160422       1h+ 24h  -
    delete  -     /mnt/rootfs/.snapshot/portage_distfiles.20160423       1h+ 24h  -
    -       -     /mnt/rootfs/.snapshot/portage_distfiles.20160424       1h+ 24h  preserve hourly: first of hour, 14 hours ago
    -       -     /mnt/rootfs/.snapshot/portage_distfiles.20160424T1417  1h+ 24h  preserve hourly: first of hour, 0 hours ago
    delete  -     /mnt/rootfs/.snapshot/var.20160422                     1h+ 24h  -
    delete  -     /mnt/rootfs/.snapshot/var.20160423                     1h+ 24h  -
    -       -     /mnt/rootfs/.snapshot/var.20160424                     1h+ 24h  preserve hourly: first of hour, 14 hours ago
    -       -     /mnt/rootfs/.snapshot/var.20160424T1417                1h+ 24h  preserve hourly: first of hour, 0 hours ago
    
    BACKUP SCHEDULE
    action  host           subvol                                                       scheme   reason
    ------  -------------  -----------------------------------------------------------  -------  -----------------------------------------
    delete  diefledermaus  /media/MARCEC_BACKUP/arthur/rootfs.20160323                  1h+ 31d  -
    -       diefledermaus  /media/MARCEC_BACKUP/arthur/rootfs.20160324                  1h+ 31d  preserve daily: first of day, 31 days ago
    [...]
    -       diefledermaus  /media/MARCEC_BACKUP/arthur/home.20160424T1417               1h+ 31d  preserve min: 0 hours ago
    -       diefledermaus  /media/MARCEC_BACKUP/arthur/portage_distfiles.20160422       1h+ 31d  preserve daily: first of day, 2 days ago
    -       diefledermaus  /media/MARCEC_BACKUP/arthur/portage_distfiles.20160423       1h+ 31d  preserve daily: first of day, 1 days ago
    -       diefledermaus  /media/MARCEC_BACKUP/arthur/portage_distfiles.20160424       1h+ 31d  preserve daily: first of day, 0 days ago
    -       diefledermaus  /media/MARCEC_BACKUP/arthur/portage_distfiles.20160424T1417  1h+ 31d  preserve min: 0 hours ago
    delete  diefledermaus  /media/MARCEC_BACKUP/arthur/var.20160323                     1h+ 31d  -
    -       diefledermaus  /media/MARCEC_BACKUP/arthur/var.20160324                     1h+ 31d  preserve daily: first of day, 31 days ago
    [...]
    -       diefledermaus  /media/MARCEC_BACKUP/arthur/var.20160424T1417                1h+ 31d  preserve min: 0 hours ago
    
    --------------------------------------------------------------------------------
    Backup Summary (btrbk command line client, version 0.23.0)
    
        Date:   Sun Apr 24 14:17:00 2016
        Config: /etc/btrbk/btrbk.conf
        Dryrun: YES
    
    Legend:
        ===  up-to-date subvolume (source snapshot)
        +++  created subvolume (source snapshot)
        ---  deleted subvolume
        ***  received subvolume (non-incremental)
        >>>  received subvolume (incremental)
    --------------------------------------------------------------------------------
    /mnt/rootfs/rootfs
    +++ /mnt/rootfs/.snapshot/rootfs.20160424T1417
    --- /mnt/rootfs/.snapshot/rootfs.20160422
    --- /mnt/rootfs/.snapshot/rootfs.20160423
    >>> diefledermaus:/media/MARCEC_BACKUP/arthur/rootfs.20160424
    >>> diefledermaus:/media/MARCEC_BACKUP/arthur/rootfs.20160424T1417
    --- diefledermaus:/media/MARCEC_BACKUP/arthur/rootfs.20160323
    --- diefledermaus:/media/MARCEC_BACKUP/arthur/rootfs.20160402_1
    --- diefledermaus:/media/MARCEC_BACKUP/arthur/rootfs.20160405_1
    
    /mnt/rootfs/home
    +++ /mnt/rootfs/.snapshot/home.20160424T1417
    >>> diefledermaus:/media/MARCEC_BACKUP/arthur/home.20160424
    >>> diefledermaus:/media/MARCEC_BACKUP/arthur/home.20160424T1417
    --- diefledermaus:/media/MARCEC_BACKUP/arthur/home.20160323
    --- diefledermaus:/media/MARCEC_BACKUP/arthur/home.20160402_1
    --- diefledermaus:/media/MARCEC_BACKUP/arthur/home.20160405_1
    
    /mnt/rootfs/portage_distfiles
    +++ /mnt/rootfs/.snapshot/portage_distfiles.20160424T1417
    --- /mnt/rootfs/.snapshot/portage_distfiles.20160422
    --- /mnt/rootfs/.snapshot/portage_distfiles.20160423
    >>> diefledermaus:/media/MARCEC_BACKUP/arthur/portage_distfiles.20160424
    >>> diefledermaus:/media/MARCEC_BACKUP/arthur/portage_distfiles.20160424T1417
    
    /mnt/rootfs/var
    +++ /mnt/rootfs/.snapshot/var.20160424T1417
    --- /mnt/rootfs/.snapshot/var.20160422
    --- /mnt/rootfs/.snapshot/var.20160423
    >>> diefledermaus:/media/MARCEC_BACKUP/arthur/var.20160424
    >>> diefledermaus:/media/MARCEC_BACKUP/arthur/var.20160424T1417
    --- diefledermaus:/media/MARCEC_BACKUP/arthur/var.20160323
    --- diefledermaus:/media/MARCEC_BACKUP/arthur/var.20160402_1
    --- diefledermaus:/media/MARCEC_BACKUP/arthur/var.20160405_1

So while the snapshot retention policy was correctly overridden, the target retention policy was not.

**Comment by digint** [comment]
Thanks for reporting, that's a bug in the new target propagation feature that was not covered by my test cases.

Fixed in: 191284cd4377ae879869a312395b91fcc108bf23

**Comment by marcecj** [comment]
Gladly, and thanks for responding so quickly!

**Comment by digint** [comment]
Fixed in [btrbk-v0.23.1](/digint/btrbk/releases/tag/v0.23.1)
