### ISSUE TITLE
Allow storing subvolume snapshots in different directories

### ISSUE THREAD

**Issue by tornewuff** [digint/btrbk#86]
I'd like to be able to keep the snapshots of each subvolume in a different subdirectory of snapshot_dir, ending up with something like `/mnt/btrfsroot/snapshots/home/20160425T1807` instead of `/mnt/btrfsroot/snapshots/home-20160425T1807`.

The reason I want this is so that I can set the permissions on the subdirectory to not always be readable by all users - I'd prefer that users can only get directory listings for snapshots that they are able to access, and not see a bunch of snapshots they don't have permission to get into in the first place. This would also allow me to symlink subvolume/.snapshots or similar to the directory containing the snapshots for that subvolume.

**Comment by digint** [comment]
This is already possible: simply set `snapshot_dir` in each `subvolume` section.

something like this:
```
volume /mnt/btrfsroot
  subvolume home
    snapshot_dir snapshots/home
  subvolume blah
    snapshot_dir snapshots/blah
```

The resulting files will still be named `home-<timestamp>`, but they will be created in the dir you specified.
