### ISSUE TITLE
If no targets are defined local snapshots are not completed

### ISSUE THREAD

**Issue by timharton** [digint/btrbk#9]
I wanted  to use btrbk to create managed local snapshots and not backup to a different btrfs pool.  I thought that I should be able to do this by not defining a target.

So I just left the target out of the subvolume I wanted to snapshot. I received this error:
 
```
/mnt/btrfs/vm_images
!!! Subvolume "vm_images" aborted: No targets defined for subvolume: /mnt/btrfs/vm_images
```

Is there any way to do this? Or am I missing something? 

It's also fine if this is not how it's intended to be used, but I would think it would be an easy enhancement to add.

**Comment by timharton** [comment]
Sorry I just experimented with the snapshot create always config. I did have it set to:
```
snapshot_create_always     no
```
I now have it set to:
```
snapshot_create_always     yes
```
And it now works.

**Comment by digint** [comment]
Thanks for the input! Nice to see that btrbk can cope with this without compaining (It's a pretty straight-forward usecase I never thought of :)

Added an example configuration for this in: 920b7821ce9c5765c9b62f247d719b012b029739
