### ISSUE TITLE
Resume / partial send question

### ISSUE THREAD

**Issue by Bladtman242** [digint/btrbk#94]
Is there any way I can resume a cancelled backup, or split backups into smaller parts?
I'm backing up a remote system, and the initial snapshot is going to take several days, which is clearly not an option, unless I can interrupt and assume the backup.

Equivalently; if I btrfs-send to a file locally, and manually transfer it to the remote, can I "trick" btrbk into accepting the remote version as a backup of the local snapshot?

Thank you.

**Comment by moben** [comment]
btrbk will recognize your snapshot if you transfer it manually, it's exactly what I did when I started doing remote backups over a slow connection.

**Comment by digint** [comment]
If you want a *file* to transfer, either configure a `target raw` in btrbk.conf (see TARGET TYPES in [btrbk.conf(5)](https://digint.ch/btrbk/doc/btrbk.conf.html) ), or use bare btrfs-progs for this (see [FAW: Use external storage as "stream-fifo"](https://github.com/digint/btrbk/blob/master/doc/FAQ.md#answer-2-use-external-storage-as-stream-fifo)).

Either way, btrbk will recognize the subvolume on the target side and use it for further incremental backups.

For splitting, you can use the `split` shell command, and glue it back on the target using `cat`.

If you want to turn a "raw" target back to a subvolume, simply `gunzip <infile> | btrfs receive /mnt/btr_backup/`.

**Comment by Bladtman242** [comment]
That's awesome.
I thought btrbk had to keep a record of snapshot/backup correspondences.
It must use the filenames then?

Thanks for the fast response!
(and for btrbk as well)

**Comment by digint** [comment]
btrbk uses the uuid relations from the filesystem, the file names are basically only used for the timestamp information. Every subvolume has a `uuid`, `parent_uuid` and `received_uuid`, which keeps track of the relationships between them. These can be shown using:
```
btrfs subvolume list -u -q -R <path>
```

**Comment by Bladtman242** [comment]
That's nice.
I guess that means that as long as the subvolume is send-received to a remote, btrbk will be able to recognise it.

**Comment by digint** [comment]
Exactly.

More technically spoken: "the subvolume is recognized as a backup if `received_uuid` matches `uuid` of the source". And the `received_uuid` is always set correctly by `btrfs receive`.

**Comment by Bladtman242** [comment]
Thanks for the explanation!
I think I'll rsync them to the remote than.
Are there any plans to use a backup transfer method that can resume broken transfers? (like rsync)
It would to immensely useful.

**Comment by digint** [comment]
I'm afraid this is not possible with `btrfs send/receive` (which btrbk relies on). btrfs-progs does not provide a mechanism for resuming partial send/receives, and I have not seen any tools with this functionality.

So no, this is not planned.

**Comment by Bladtman242** [comment]
Ahh, i see. You would have to `send` it first to a file, and then transfer, needing extra space and time, and probably requiring extra logic to manage interrupted `send` _and_ transfer operations.
Makes a lot of sense, too bad though. Could have saved a lot of manual `btrbk clean` calls :)

Anyway, thanks for the explanations, I can do what I wanted to now.

**Comment by solarkraft** [comment]
> I have not seen any tools with this functionality

[Apparently buttersync does support resuming an interrupted send](https://unix.stackexchange.com/a/155748/319687), but I haven't gotten it to run, so I can't verify the claim.

**Comment by tbertels** [comment]
> > I have not seen any tools with this functionality
> 
> [Apparently buttersync does support resuming an interrupted send](https://unix.stackexchange.com/a/155748/319687), but I haven't gotten it to run, so I can't verify the claim.

It just transfers the file, then uses btrfs receive on it, so it requires double the size on the receiving end.
